In [4]:
# ============================================================
# 0) CONFIG (edit these paths / knobs)
# ============================================================
from pathlib import Path
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

DATA_DIR = Path("/Data/in Use")

ROUNDS_PATH = DATA_DIR / "combined_rounds_all_2017_2026.csv"
ODDS_PATH  = DATA_DIR / "Odds_and_Results.xlsx"         # field for upcoming events
SCHED_2024 = DATA_DIR / "OAD_2024.xlsx"
SCHED_2025 = DATA_DIR / "OAD_2025.xlsx"
SCHED_2026 = DATA_DIR / "OAD_2026.xlsx"

# Modeling years
TRAIN_START_YEAR = 2017
TRAIN_END_YEAR   = 2024   # "driver analysis" and base training window
BACKTEST_YEAR    = 2025

# Pre-event cutoff = start_date - 1 day
CUTOFF_LAG_DAYS = 1

# Rolling windows (rounds)
WINDOWS = (40, 24, 12)

# Stats we will consider (all exist in your screenshot)
# NOTE: We'll create derived birdie_eagle = birdies + eagles_or_better
BASE_STATS = [
    "sg_total", "sg_t2g", "sg_ott", "sg_app", "sg_arg", "sg_putt",
    "round_score",
    "birdies", "eagles_or_better",
    "driving_dist", "driving_acc",
    "gir", "scrambling",
    "prox_fw", "prox_rgh",
    "great_shots", "poor_shots",
    "bogies", "doubles_or_worse", "pars",
]

# Minimum rounds required to trust rolling window values
# (we’ll still keep rows with fewer rounds; these control when rolling values become non-null)
MIN_PERIODS_BY_W = {40: 20, 24: 12, 12: 6}


# ============================================================
# 1) LOAD SCHEDULE (OAD events define the event_id universe)
# ============================================================
def load_sched(path: Path) -> pd.DataFrame:
    df = pd.read_excel(path)
    # expected cols: course_name, course_num, event_id, event_name, purse, rank, start_date, winner_share, year
    df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")
    df["event_id"] = pd.to_numeric(df["event_id"], errors="coerce").astype("Int64")
    df["start_date"] = pd.to_datetime(df["start_date"], errors="coerce")
    return df

sched_24 = load_sched(SCHED_2024)
sched_25 = load_sched(SCHED_2025)
sched_26 = load_sched(SCHED_2026)

sched_all = pd.concat([sched_24, sched_25, sched_26], ignore_index=True)
oad_event_ids = sorted(sched_all["event_id"].dropna().astype(int).unique().tolist())

print("OAD event_ids:", len(oad_event_ids), "examples:", oad_event_ids[:10])


# ============================================================
# 2) LOAD ROUNDS (filter to OAD event_ids only)
# ============================================================
use_cols = [
    "year","event_id","event_name","course_num","course_name",
    "round_date","round_num","dg_id","player_name",
    "finish_num","fin_text","event_completed",
] + BASE_STATS

rounds = pd.read_csv(ROUNDS_PATH, usecols=lambda c: c in set(use_cols))

# types
rounds["year"] = pd.to_numeric(rounds["year"], errors="coerce").astype("Int64")
rounds["event_id"] = pd.to_numeric(rounds["event_id"], errors="coerce").astype("Int64")
rounds["dg_id"] = pd.to_numeric(rounds["dg_id"], errors="coerce").astype("Int64")
rounds["round_date"] = pd.to_datetime(rounds["round_date"], errors="coerce")

# keep only OAD event universe + usable rows
rounds = rounds[
    rounds["year"].notna()
    & rounds["event_id"].notna()
    & rounds["dg_id"].notna()
    & rounds["round_date"].notna()
].copy()

rounds["event_id"] = rounds["event_id"].astype(int)
rounds["dg_id"] = rounds["dg_id"].astype(int)
rounds["year"] = rounds["year"].astype(int)

rounds = rounds[rounds["event_id"].isin(oad_event_ids)].copy()

# derived stat
if "birdies" in rounds.columns and "eagles_or_better" in rounds.columns:
    rounds["birdie_eagle"] = pd.to_numeric(rounds["birdies"], errors="coerce").fillna(0) + \
                             pd.to_numeric(rounds["eagles_or_better"], errors="coerce").fillna(0)
    if "birdie_eagle" not in BASE_STATS:
        BASE_STATS.append("birdie_eagle")

# ensure numeric stats are numeric
for c in BASE_STATS + ["finish_num"]:
    if c in rounds.columns:
        rounds[c] = pd.to_numeric(rounds[c], errors="coerce")

print("Rounds rows:", len(rounds), "Years:", (rounds["year"].min(), rounds["year"].max()))


# ============================================================
# 3) BUILD PLAYER-EVENT-YEAR TABLE (labels)
#    finish_num is tournament finish (repeated per round); take first non-null per player-event-year
# ============================================================
pe = (
    rounds.groupby(["year","event_id","dg_id"], as_index=False)
    .agg(
        player_name=("player_name","first"),
        course_num=("course_num","first"),
        course_name=("course_name","first"),
        finish_num=("finish_num", lambda s: s.dropna().iloc[0] if s.dropna().shape[0] else np.nan),
        fin_text=("fin_text", lambda s: s.dropna().iloc[0] if s.dropna().shape[0] else np.nan),
    )
)

# labels (binary)
pe["y_win"]   = (pe["finish_num"] == 1).astype(int)
pe["y_top5"]  = (pe["finish_num"] <= 5).astype(int)
pe["y_top10"] = (pe["finish_num"] <= 10).astype(int)

# keep within modeling years we care about
pe = pe[(pe["year"] >= TRAIN_START_YEAR) & (pe["year"] <= BACKTEST_YEAR)].copy()

print("Player-event rows:", len(pe), "Unique events:", pe[["year","event_id"]].drop_duplicates().shape[0])


# ============================================================
# 4) EVENT START DATES:
#    Prefer schedule start_date for 2024-2026; otherwise infer as min(round_date) per year/event_id
# ============================================================
sched_key = sched_all[["year","event_id","start_date","rank"]].dropna(subset=["year","event_id","start_date"]).copy()
sched_key["year"] = sched_key["year"].astype(int)
sched_key["event_id"] = sched_key["event_id"].astype(int)

# inferred start_date
ev_infer = (
    rounds.groupby(["year","event_id"], as_index=False)
    .agg(infer_start_date=("round_date","min"))
)

ev = pe[["year","event_id"]].drop_duplicates().merge(ev_infer, on=["year","event_id"], how="left")
ev = ev.merge(sched_key, on=["year","event_id"], how="left")

ev["event_start_date"] = ev["start_date"].where(ev["start_date"].notna(), ev["infer_start_date"])
ev["cutoff_date"] = (pd.to_datetime(ev["event_start_date"]) - pd.to_timedelta(CUTOFF_LAG_DAYS, unit="D")).dt.normalize()

# attach cutoff to player-event table
pe = pe.merge(ev[["year","event_id","event_start_date","cutoff_date","rank"]], on=["year","event_id"], how="left")

assert pe["cutoff_date"].notna().mean() > 0.99, "Too many missing cutoff_date; check start_date logic."


# ============================================================
# 5) ROLLING FEATURES PER ROUND (per player), then merge-asof to cutoff_date
#    This avoids per-row slicing and keeps things fast enough.
# ============================================================
roll_stats = [c for c in BASE_STATS if c in rounds.columns]  # only those present

rounds_sorted = rounds.sort_values(["dg_id","round_date"]).copy()

# compute rolling means at each round for each stat/window
for w in WINDOWS:
    minp = MIN_PERIODS_BY_W.get(w, max(3, w//3))
    for stat in roll_stats:
        out_col = f"{stat}_L{w}"
        rounds_sorted[out_col] = (
            rounds_sorted.groupby("dg_id")[stat]
            .rolling(window=w, min_periods=minp)
            .mean()
            .reset_index(level=0, drop=True)
        )

# add "missing split" flags (so missing sg_app etc is not treated as bad performance)
for stat in ["sg_ott","sg_app","sg_arg","sg_putt","sg_t2g"]:
    if stat in rounds_sorted.columns:
        rounds_sorted[f"has_{stat}"] = rounds_sorted[stat].notna().astype(int)

# merge last available rolling snapshot before cutoff_date, per dg_id
feat_cols = [c for c in rounds_sorted.columns if any(c.endswith(f"_L{w}") for w in WINDOWS)]
feat_cols += [c for c in rounds_sorted.columns if c.startswith("has_sg_")]

left = pe.sort_values(["dg_id","cutoff_date"]).copy()
right = rounds_sorted.sort_values(["dg_id","round_date"])[["dg_id","round_date"] + feat_cols].copy()

# --- HARDEN merge_asof inputs ---
left = pe.copy()
right = rounds_sorted[["dg_id", "round_date"] + feat_cols].copy()

# ensure datetimes are comparable + not timezone-aware
left["cutoff_date"] = pd.to_datetime(left["cutoff_date"], errors="coerce").dt.tz_localize(None)
right["round_date"] = pd.to_datetime(right["round_date"], errors="coerce").dt.tz_localize(None)

# enforce int keys
left["dg_id"] = pd.to_numeric(left["dg_id"], errors="coerce").astype("Int64")
right["dg_id"] = pd.to_numeric(right["dg_id"], errors="coerce").astype("Int64")

# drop null keys (merge_asof cannot handle these)
left = left.dropna(subset=["dg_id", "cutoff_date"]).copy()
right = right.dropna(subset=["dg_id", "round_date"]).copy()

left["dg_id"] = left["dg_id"].astype(int)
right["dg_id"] = right["dg_id"].astype(int)

# critical: sort by the "on" key FIRST (global), then the "by" key
left  = left.sort_values(["cutoff_date", "dg_id"], kind="mergesort").reset_index(drop=True)
right = right.sort_values(["round_date", "dg_id"], kind="mergesort").reset_index(drop=True)

X = pd.merge_asof(
    left,
    right,
    by="dg_id",
    left_on="cutoff_date",
    right_on="round_date",
    direction="backward",
    allow_exact_matches=True,
)


# (optional) sanity checks
assert left[["dg_id","cutoff_date"]].isna().sum().sum() == 0
assert right[["dg_id","round_date"]].isna().sum().sum() == 0

X = pd.merge_asof(
    left,
    right,
    by="dg_id",
    left_on="cutoff_date",
    right_on="round_date",
    direction="backward",
    allow_exact_matches=True,
)

X = pd.merge_asof(
    left,
    right,
    by="dg_id",
    left_on="cutoff_date",
    right_on="round_date",
    direction="backward",
    allow_exact_matches=True,
)

# drop helper round_date from merge
X = X.drop(columns=["round_date"], errors="ignore")

print("Feature rows:", len(X), "Feature cols:", len(feat_cols))
print("Non-null rate (sg_total_L40):", X.get("sg_total_L40", pd.Series(dtype=float)).notna().mean())

OAD event_ids: 31 examples: [2, 3, 4, 5, 6, 7, 9, 10, 11, 12]
Rounds rows: 50526 Years: (np.int64(2022), np.int64(2026))
Player-event rows: 16250 Unique events: 123
Feature rows: 16250 Feature cols: 68
Non-null rate (sg_total_L40): 0.7579692307692307

In [5]:
# ============================================================
# 6) EVENT HISTORY FEATURES (known pre-event; no leakage)
#    - prior top10 rate at this event_id
#    - prior mean finish at this event_id
# ============================================================
hist = X[["year","event_id","dg_id","finish_num","y_top10"]].copy()
hist = hist.sort_values(["dg_id","event_id","year"])

# expanding stats, shifted so only PRIOR years are used
hist["prior_top10_rate_event"] = (
    hist.groupby(["dg_id","event_id"])["y_top10"]
    .apply(lambda s: s.expanding().mean().shift(1))
    .reset_index(level=[0,1], drop=True)
)

hist["prior_mean_finish_event"] = (
    hist.groupby(["dg_id","event_id"])["finish_num"]
    .apply(lambda s: s.expanding().mean().shift(1))
    .reset_index(level=[0,1], drop=True)
)

X = X.merge(
    hist[["year","event_id","dg_id","prior_top10_rate_event","prior_mean_finish_event"]],
    on=["year","event_id","dg_id"],
    how="left",
)

# ============================================================
# 7) OPTIONAL: ODDS MERGE (for baseline + maybe later calibration/blending)
#    We will NOT force it into the model unless you choose to later.
# ============================================================
try:
    odds = pd.read_excel(ODDS_PATH)
    # normalize common columns
    for c in ["year","event_id","dg_id"]:
        if c in odds.columns:
            odds[c] = pd.to_numeric(odds[c], errors="coerce")
    if "year" in odds.columns: odds["year"] = odds["year"].astype("Int64")
    if "event_id" in odds.columns: odds["event_id"] = odds["event_id"].astype("Int64")
    if "dg_id" in odds.columns: odds["dg_id"] = odds["dg_id"].astype("Int64")

    # pick an odds column if present
    candidate_odds_cols = ["close_odds","decimal_odds","odds","win_odds","close_odds_decimal"]
    odds_col = next((c for c in candidate_odds_cols if c in odds.columns), None)

    if odds_col:
        odds_small = odds[["year","event_id","dg_id",odds_col]].copy()
        odds_small = odds_small.dropna(subset=["year","event_id","dg_id"])
        odds_small["year"] = odds_small["year"].astype(int)
        odds_small["event_id"] = odds_small["event_id"].astype(int)
        odds_small["dg_id"] = odds_small["dg_id"].astype(int)

        X = X.merge(odds_small, on=["year","event_id","dg_id"], how="left")
        print("Merged odds column:", odds_col, "Non-null rate:", X[odds_col].notna().mean())
    else:
        odds_col = None
        print("No recognized odds column found in Odds_and_Results.xlsx; skipping.")
except Exception as e:
    odds_col = None
    print("Odds merge skipped due to error:", repr(e))


# ============================================================
# 8) DEFINE FEATURE SET (stats-heavy; odds excluded by default)
# ============================================================
id_cols = ["year","event_id","dg_id","player_name","course_num","course_name","event_start_date","cutoff_date","rank","finish_num","fin_text"]
label_cols = ["y_win","y_top5","y_top10"]

# Start with all rolling features + history
feature_cols = [c for c in X.columns if any(c.endswith(f"_L{w}") for w in WINDOWS)]
feature_cols += [c for c in X.columns if c.startswith("has_sg_")]
feature_cols += ["prior_top10_rate_event","prior_mean_finish_event"]

# drop obviously unusable
feature_cols = [c for c in feature_cols if c not in id_cols + label_cols]

# Keep a "sg_total only" baseline feature list for comparisons
sg_total_only = [c for c in feature_cols if c.startswith("sg_total_L")]

print("Full feature count:", len(feature_cols))
print("sg_total-only features:", sg_total_only)


# ============================================================
# 9) MAKE TRAIN/TEST FRAMES (2017-2024 train, 2025 used for walk-forward)
# ============================================================
train_df = X[(X["year"] >= TRAIN_START_YEAR) & (X["year"] <= TRAIN_END_YEAR)].copy()
bt_df    = X[X["year"] == BACKTEST_YEAR].copy()

# sanity
print("Train rows:", len(train_df), "Backtest rows:", len(bt_df))
print("Train positive rates:",
      train_df["y_win"].mean(), train_df["y_top5"].mean(), train_df["y_top10"].mean())

Merged odds column: close_odds Non-null rate: 0.7286769230769231
Full feature count: 70
sg_total-only features: ['sg_total_L40', 'sg_total_L24', 'sg_total_L12']
Train rows: 12380 Backtest rows: 3870
Train positive rates: 0.007431340872374798 0.04426494345718902 0.08707592891760904

In [17]:
# ============================================================
# 10) MODELING: gradient boosting that tolerates NaNs
# ============================================================
from sklearn.experimental import enable_hist_gradient_boosting  # noqa
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import roc_auc_score, brier_score_loss
from sklearn.inspection import permutation_importance

RANDOM_SEED = 42

def fit_hgb(Xtr, ytr):
    # conservative, stable defaults; editable
    model = HistGradientBoostingClassifier(
        loss="log_loss",
        learning_rate=0.05,
        max_depth=6,
        max_iter=400,
        min_samples_leaf=40,
        l2_regularization=0.0,
        random_state=RANDOM_SEED,
    )
    model.fit(Xtr, ytr)
    return model

def safe_auc(y_true, y_prob):
    # handle cases with no positives in a slice
    if len(np.unique(y_true)) < 2:
        return np.nan
    return roc_auc_score(y_true, y_prob)

def summarize_driver_analysis(df, feat_cols, label_col="y_top10"):
    # simple held-out year: train 2017-2023, validate 2024
    tr = df[df["year"] <= 2023].copy()
    va = df[df["year"] == 2024].copy()

    Xtr, ytr = tr[feat_cols], tr[label_col].astype(int)
    Xva, yva = va[feat_cols], va[label_col].astype(int)

    m = fit_hgb(Xtr, ytr)
    p = m.predict_proba(Xva)[:, 1]

    auc = safe_auc(yva, p)
    brier = brier_score_loss(yva, p) if len(np.unique(yva)) > 1 else np.nan

    # permutation importance on validation (slower but interpretable)
    perm = permutation_importance(
        m, Xva, yva,
        n_repeats=8,
        random_state=RANDOM_SEED,
        scoring="roc_auc" if len(np.unique(yva)) > 1 else None
    )
    imp = pd.DataFrame({
        "feature": feat_cols,
        "perm_importance_mean": perm.importances_mean,
        "perm_importance_std": perm.importances_std,
    }).sort_values("perm_importance_mean", ascending=False)

    return {"model": m, "val_auc": auc, "val_brier": brier, "perm_importance": imp}

# ============================================================
# 11) DRIVER ANALYSIS (run for top10; repeat for top5/win if you want)
# ============================================================
da_top10 = summarize_driver_analysis(train_df, feature_cols, "y_top10")
print("Driver analysis (Top10) - val AUC:", da_top10["val_auc"], "val Brier:", da_top10["val_brier"])
display(da_top10["perm_importance"].head(25))


# ============================================================
# 12) BASELINES: sg_total-only vs full stats-heavy
# ============================================================
def fit_and_eval_simple(df_train, df_test, feat_cols, label_col):
    Xtr = df_train[feat_cols]
    ytr = df_train[label_col].astype(int)
    Xte = df_test[feat_cols]
    yte = df_test[label_col].astype(int)

    m = fit_hgb(Xtr, ytr)
    p = m.predict_proba(Xte)[:, 1]
    return {
        "auc": safe_auc(yte, p),
        "brier": brier_score_loss(yte, p) if len(np.unique(yte)) > 1 else np.nan,
        "pred": p,
        "model": m,
    }

# quick static check: train<=2024, test=2025 (not walk-forward yet)
static_res = {}
for lab in ["y_win","y_top5","y_top10"]:
    static_res[(lab,"full")] = fit_and_eval_simple(train_df, bt_df, feature_cols, lab)
    static_res[(lab,"sg_total")] = fit_and_eval_simple(train_df, bt_df, sg_total_only, lab)

for lab in ["y_win","y_top5","y_top10"]:
    print(lab,
          "AUC full:", static_res[(lab,"full")]["auc"],
          "AUC sg_total:", static_res[(lab,"sg_total")]["auc"],
          "Brier full:", static_res[(lab,"full")]["brier"],
          "Brier sg_total:", static_res[(lab,"sg_total")]["brier"])


# ============================================================
# 13) 2025 WALK-FORWARD BACKTEST (event-by-event)
#    Train on all events prior to each 2025 event date, then predict that event.
# ============================================================
# Use schedule order if present; else by inferred event_start_date
sched_2025_key = sched_25[["year","event_id","start_date","rank"]].copy()
sched_2025_key["year"] = sched_2025_key["year"].astype(int)
sched_2025_key["event_id"] = sched_2025_key["event_id"].astype(int)
sched_2025_key["start_date"] = pd.to_datetime(sched_2025_key["start_date"], errors="coerce")

event_order_2025 = (
    bt_df[["event_id","event_start_date"]].drop_duplicates()
    .merge(sched_2025_key[["event_id","start_date","rank"]], on="event_id", how="left")
)
event_order_2025["order_date"] = event_order_2025["start_date"].where(
    event_order_2025["start_date"].notna(), event_order_2025["event_start_date"]
)
event_order_2025 = event_order_2025.sort_values(["order_date","rank","event_id"]).reset_index(drop=True)

def walk_forward_2025(label_col, feat_cols):
    rows = []
    for _, evrow in event_order_2025.iterrows():
        ev_id = int(evrow["event_id"])
        ev_date = pd.to_datetime(evrow["order_date"])
        print(f"\n=== Event {ev_id} | {ev_date.date()} ===")


        # training: all years < 2025 plus 2025 events strictly before this event date
        df_tr = X[
            (X["year"] < BACKTEST_YEAR)
            | ((X["year"] == BACKTEST_YEAR) & (pd.to_datetime(X["event_start_date"]) < ev_date))
        ].copy()

        df_te = X[(X["year"] == BACKTEST_YEAR) & (X["event_id"] == ev_id)].copy()
        if df_te.empty:
            continue

        m = fit_hgb(df_tr[feat_cols], df_tr[label_col].astype(int))
        p = m.predict_proba(df_te[feat_cols])[:, 1]

        df_te = df_te[["year","event_id","dg_id","player_name","finish_num",label_col]].copy()
        df_te["pred"] = p

        # event-level evaluation
        auc = safe_auc(df_te[label_col].astype(int).values, df_te["pred"].values)
        brier = brier_score_loss(df_te[label_col].astype(int).values, df_te["pred"].values) \
                if len(np.unique(df_te[label_col].astype(int).values)) > 1 else np.nan

        # "pick quality": did top predicted player actually achieve the target?
        top_pick = df_te.sort_values("pred", ascending=False).iloc[0]
        rows.append({
            "event_id": ev_id,
            "event_date": ev_date,
            "label": label_col,
            "auc": auc,
            "brier": brier,
            "top_pick_name": top_pick["player_name"],
            "top_pick_dg_id": int(top_pick["dg_id"]),
            "top_pick_pred": float(top_pick["pred"]),
            "top_pick_hit": int(top_pick[label_col]),
            "top_pick_finish": float(top_pick["finish_num"]) if pd.notna(top_pick["finish_num"]) else np.nan,
        })

    return pd.DataFrame(rows).sort_values("event_date")

wf_full = {}
wf_sg   = {}
for lab in ["y_win","y_top5","y_top10"]:
    wf_full[lab] = walk_forward_2025(lab, feature_cols)
    wf_sg[lab]   = walk_forward_2025(lab, sg_total_only)

for lab in ["y_win","y_top5","y_top10"]:
    print("\n====", lab, "====")
    print("Full:   mean hit@1 =", wf_full[lab]["top_pick_hit"].mean(),
          "| mean AUC =", wf_full[lab]["auc"].mean(),
          "| mean Brier =", wf_full[lab]["brier"].mean())
    print("SGonly: mean hit@1 =", wf_sg[lab]["top_pick_hit"].mean(),
          "| mean AUC =", wf_sg[lab]["auc"].mean(),
          "| mean Brier =", wf_sg[lab]["brier"].mean())

# view the per-event picks/results for top10 (most OAD-relevant)
display(wf_full["y_top10"].head(30))

Driver analysis (Top10) - val AUC: 0.7371385417966781 val Brier: 0.07970979459994251

                    feature  perm_importance_mean  perm_importance_std
0              sg_total_L40              0.074739             0.005787
42             sg_total_L12              0.024974             0.002169
21             sg_total_L24              0.015065             0.001939
43               sg_t2g_L12              0.010907             0.002657
9          driving_dist_L40              0.010865             0.002174
30         driving_dist_L24              0.010811             0.002874
1                sg_t2g_L40              0.010620             0.002968
4                sg_arg_L40              0.009931             0.005365
69  prior_mean_finish_event              0.009925             0.003479
34              prox_fw_L24              0.008450             0.002298
38               bogies_L24              0.006269             0.001615
22               sg_t2g_L24              0.005970             0.000933
5               sg_putt_L40              0.005874             0.002972
55              prox_fw_L12              0.005665             0.001779
58           poor_shots_L12              0.005490             0.001365
25               sg_arg_L24              0.005123             0.002511
2                sg_ott_L40              0.005024             0.001331
23               sg_ott_L24              0.004893             0.001667
63               has_sg_ott              0.004654             0.003677
33           scrambling_L24              0.004581             0.002039
59               bogies_L12              0.004522             0.000500
47              sg_putt_L12              0.003925             0.001758
11                  gir_L40              0.003536             0.001856
29     eagles_or_better_L24              0.003433             0.000714
54           scrambling_L12              0.003237             0.001669

y_win AUC full: 0.9924963658210724 AUC sg_total: 0.9903872816341621 Brier full: 0.004081104771220021 Brier sg_total: 0.00622631103416534
y_top5 AUC full: 0.9584067172969274 AUC sg_total: 0.8937136118371605 Brier full: 0.031022467939375915 Brier sg_total: 0.040263144535028814
y_top10 AUC full: 0.8995856331168832 AUC sg_total: 0.8574204545454545 Brier full: 0.06026244718817251 Brier sg_total: 0.06679931268731866

=== Event 6 | 2025-01-12 ===

=== Event 2 | 2025-01-19 ===

=== Event 4 | 2025-01-25 ===

=== Event 5 | 2025-02-02 ===

=== Event 3 | 2025-02-09 ===

=== Event 7 | 2025-02-16 ===

=== Event 540 | 2025-02-23 ===

=== Event 10 | 2025-03-02 ===

=== Event 9 | 2025-03-09 ===

=== Event 11 | 2025-03-16 ===

=== Event 475 | 2025-03-23 ===

=== Event 20 | 2025-03-30 ===

=== Event 41 | 2025-04-06 ===

=== Event 14 | 2025-04-13 ===

=== Event 12 | 2025-04-20 ===

=== Event 19 | 2025-05-04 ===

=== Event 480 | 2025-05-11 ===

=== Event 33 | 2025-05-18 ===

=== Event 21 | 2025-05-25 ===

=== Event 23 | 2025-06-01 ===

=== Event 32 | 2025-06-08 ===

=== Event 26 | 2025-06-15 ===

=== Event 34 | 2025-06-22 ===

=== Event 524 | 2025-06-29 ===

=== Event 30 | 2025-07-06 ===

=== Event 541 | 2025-07-13 ===

=== Event 100 | 2025-07-20 ===

=== Event 525 | 2025-07-27 ===

=== Event 13 | 2025-08-03 ===

=== Event 27 | 2025-08-10 ===

=== Event 28 | 2025-08-17 ===

=== Event 6 | 2025-01-12 ===

=== Event 2 | 2025-01-19 ===

=== Event 4 | 2025-01-25 ===

=== Event 5 | 2025-02-02 ===

=== Event 3 | 2025-02-09 ===

=== Event 7 | 2025-02-16 ===

=== Event 540 | 2025-02-23 ===

=== Event 10 | 2025-03-02 ===

=== Event 9 | 2025-03-09 ===

=== Event 11 | 2025-03-16 ===

=== Event 475 | 2025-03-23 ===

=== Event 20 | 2025-03-30 ===

=== Event 41 | 2025-04-06 ===

=== Event 14 | 2025-04-13 ===

=== Event 12 | 2025-04-20 ===

=== Event 19 | 2025-05-04 ===

=== Event 480 | 2025-05-11 ===

=== Event 33 | 2025-05-18 ===

=== Event 21 | 2025-05-25 ===

=== Event 23 | 2025-06-01 ===

=== Event 32 | 2025-06-08 ===

=== Event 26 | 2025-06-15 ===

=== Event 34 | 2025-06-22 ===

=== Event 524 | 2025-06-29 ===

=== Event 30 | 2025-07-06 ===

=== Event 541 | 2025-07-13 ===

=== Event 100 | 2025-07-20 ===

=== Event 525 | 2025-07-27 ===

=== Event 13 | 2025-08-03 ===

=== Event 27 | 2025-08-10 ===

=== Event 28 | 2025-08-17 ===

=== Event 6 | 2025-01-12 ===

=== Event 2 | 2025-01-19 ===

=== Event 4 | 2025-01-25 ===

=== Event 5 | 2025-02-02 ===

=== Event 3 | 2025-02-09 ===

=== Event 7 | 2025-02-16 ===

=== Event 540 | 2025-02-23 ===

=== Event 10 | 2025-03-02 ===

=== Event 9 | 2025-03-09 ===

=== Event 11 | 2025-03-16 ===

=== Event 475 | 2025-03-23 ===

=== Event 20 | 2025-03-30 ===

=== Event 41 | 2025-04-06 ===

=== Event 14 | 2025-04-13 ===

=== Event 12 | 2025-04-20 ===

=== Event 19 | 2025-05-04 ===

=== Event 480 | 2025-05-11 ===

=== Event 33 | 2025-05-18 ===

=== Event 21 | 2025-05-25 ===

=== Event 23 | 2025-06-01 ===

=== Event 32 | 2025-06-08 ===

=== Event 26 | 2025-06-15 ===

=== Event 34 | 2025-06-22 ===

=== Event 524 | 2025-06-29 ===

KeyboardInterrupt:

In [7]:
# # ============================================================
# # ADD-ON: Field-relative features + event/course encodings
# #   - No future info (uses pre-event features + known field only)
# #   - Rolling stats already include ALL tours (your choice)
# # ============================================================
# import numpy as np
# import pandas as pd
# from sklearn.experimental import enable_hist_gradient_boosting  # noqa
# from sklearn.ensemble import HistGradientBoostingClassifier
# from sklearn.metrics import roc_auc_score, brier_score_loss
#
# RANDOM_SEED = 42
#
# # -------------------------
# # EDIT THESE: which base stats to make field-relative
# # Keep small-ish to start. Add more later if it helps.
# # -------------------------
# FIELD_RELATIVE_BASE = [
#     "sg_total_L40", "sg_total_L24", "sg_total_L12",
#     "sg_t2g_L12",
#     "sg_putt_L40",
#     "driving_dist_L40",
#     "round_score_L40",
# ]
#
# # Encodings (optional): which categorical-ish columns
# ENCODE_COLS = ["event_id", "course_num"]  # you can add "rank" later if it’s stable/meaningful
#
# # smoothing strength for target encoding
# TE_M = 50  # higher = more shrink to global prior
#
# def fit_hgb(Xtr, ytr):
#     return HistGradientBoostingClassifier(
#         loss="log_loss",
#         learning_rate=0.05,
#         max_depth=6,
#         max_iter=400,
#         min_samples_leaf=40,
#         l2_regularization=0.0,
#         random_state=RANDOM_SEED,
#     ).fit(Xtr, ytr)
#
# def safe_auc(y_true, y_prob):
#     if len(np.unique(y_true)) < 2:
#         return np.nan
#     return roc_auc_score(y_true, y_prob)
#
# def add_field_relative_features(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
#     """
#     For each (year,event_id), compute field mean/std of specified cols,
#     then add:
#       - {col}_field_z
#       - {col}_field_mean
#       - {col}_field_std
#     Uses only df values (pre-event features) => no label leakage.
#     """
#     out = df.copy()
#     grp = out.groupby(["year", "event_id"], as_index=False)
#
#     for c in cols:
#         if c not in out.columns:
#             continue
#
#         mean_name = f"{c}_field_mean"
#         std_name  = f"{c}_field_std"
#         z_name    = f"{c}_field_z"
#
#         out[mean_name] = grp[c].transform("mean")
#         out[std_name]  = grp[c].transform("std")
#
#         # avoid div by zero
#         denom = out[std_name].replace(0, np.nan)
#         out[z_name] = (out[c] - out[mean_name]) / denom
#
#     return out
#
# def build_target_encoding_train(df_tr: pd.DataFrame, y_col: str, group_col: str, m: float) -> pd.Series:
#     """
#     Leave-one-out target encoding for TRAIN rows:
#       enc_i = (sum_y_g - y_i + prior*m) / (count_g - 1 + m)
#     This avoids "peeking at its own label" inside training.
#     """
#     prior = df_tr[y_col].mean()
#
#     g = df_tr.groupby(group_col)[y_col].agg(["sum", "count"]).rename(columns={"sum":"sum_y","count":"n"})
#     df = df_tr[[group_col, y_col]].join(g, on=group_col)
#
#     denom = (df["n"] - 1 + m)
#     numer = (df["sum_y"] - df[y_col] + prior * m)
#
#     # handle groups of size 1
#     enc = np.where(df["n"] > 1, numer / denom, prior)
#     return pd.Series(enc, index=df_tr.index)
#
# def build_target_encoding_apply(df_te: pd.DataFrame, df_tr: pd.DataFrame, y_col: str, group_col: str, m: float) -> pd.Series:
#     """
#     Target encoding for TEST rows using TRAIN stats only:
#       enc = (sum_y_g + prior*m) / (count_g + m)
#     Unseen groups -> prior.
#     """
#     prior = df_tr[y_col].mean()
#     g = df_tr.groupby(group_col)[y_col].agg(["sum", "count"]).rename(columns={"sum":"sum_y","count":"n"})
#     df = df_te[[group_col]].join(g, on=group_col)
#     enc = (df["sum_y"] + prior * m) / (df["n"] + m)
#     enc = enc.fillna(prior)
#     return enc
#
# def add_encodings(df_tr: pd.DataFrame, df_te: pd.DataFrame, y_col: str, encode_cols: list[str], m: float):
#     """
#     Adds TE_* columns to both train and test.
#     """
#     tr = df_tr.copy()
#     te = df_te.copy()
#
#     for c in encode_cols:
#         if c not in tr.columns or c not in te.columns:
#             continue
#
#         tr[f"TE_{c}"] = build_target_encoding_train(tr, y_col=y_col, group_col=c, m=m)
#         te[f"TE_{c}"] = build_target_encoding_apply(te, tr, y_col=y_col, group_col=c, m=m)
#
#     return tr, te
#
# # ============================================================
# # 1) Build three feature sets to compare
# # ============================================================
#
# # start from your existing frames
# base_train = train_df.copy()
# base_bt    = bt_df.copy()
#
# # Add field-relative features (safe)
# fr_train = add_field_relative_features(base_train, FIELD_RELATIVE_BASE)
# fr_bt    = add_field_relative_features(base_bt, FIELD_RELATIVE_BASE)
#
# # Helper to collect new field-relative feature columns
# field_rel_cols = []
# for c in FIELD_RELATIVE_BASE:
#     for suf in ["_field_z", "_field_mean", "_field_std"]:
#         cc = f"{c}{suf}"
#         if cc in fr_train.columns:
#             field_rel_cols.append(cc)
#
# print("Field-relative cols added:", len(field_rel_cols))
#
# # Define feature sets (editable)
# FEAT_SG_ONLY              = [c for c in sg_total_only if c in base_train.columns]
# FEAT_SG_ONLY_PLUS_FIELD   = FEAT_SG_ONLY + field_rel_cols
# FEAT_FULL_PLUS_FIELD_BASE = [c for c in feature_cols if c in base_train.columns] + field_rel_cols
#
# # We’ll add TE columns per-label inside walk-forward, since they depend on y_col.
#
# # ============================================================
# # 2) Walk-forward (2025) comparing sets
# # ============================================================
# def walk_forward_2025_compare(
#     X_all: pd.DataFrame,
#     year_bt: int,
#     event_order_df: pd.DataFrame,
#     y_col: str,
#     feat_set_name_to_cols: dict[str, list[str]],
#     use_encodings: bool = False,
#     encode_cols: list[str] = None,
#     te_m: float = 50,
# ):
#     rows = []
#     encode_cols = encode_cols or []
#
#     for _, evrow in event_order_df.iterrows():
#         ev_id = int(evrow["event_id"])
#         ev_date = pd.to_datetime(evrow["order_date"])
#
#         df_tr = X_all[
#             (X_all["year"] < year_bt)
#             | ((X_all["year"] == year_bt) & (pd.to_datetime(X_all["event_start_date"]) < ev_date))
#         ].copy()
#
#         df_te = X_all[(X_all["year"] == year_bt) & (X_all["event_id"] == ev_id)].copy()
#         if df_te.empty or df_tr.empty:
#             continue
#
#         ytr = df_tr[y_col].astype(int)
#         yte = df_te[y_col].astype(int).values
#
#         # For each feature set, fit+predict
#         for name, cols in feat_set_name_to_cols.items():
#             tr_use = df_tr.copy()
#             te_use = df_te.copy()
#
#             # add target encodings if requested (uses TRAIN only; LOO inside train)
#             if use_encodings and encode_cols:
#                 tr_use, te_use = add_encodings(tr_use, te_use, y_col=y_col, encode_cols=encode_cols, m=te_m)
#                 te_cols = [f"TE_{c}" for c in encode_cols if f"TE_{c}" in tr_use.columns]
#                 cols_use = [c for c in cols if c in tr_use.columns] + te_cols
#             else:
#                 cols_use = [c for c in cols if c in tr_use.columns]
#
#             # model
#             m = fit_hgb(tr_use[cols_use], ytr)
#             p = m.predict_proba(te_use[cols_use])[:, 1]
#
#             auc = safe_auc(yte, p)
#             brier = brier_score_loss(yte, p) if len(np.unique(yte)) > 1 else np.nan
#
#             te_tmp = te_use[["year","event_id","dg_id","player_name","finish_num",y_col]].copy()
#             te_tmp["pred"] = p
#             top_pick = te_tmp.sort_values("pred", ascending=False).iloc[0]
#
#             rows.append({
#                 "feature_set": name,
#                 "event_id": ev_id,
#                 "event_date": ev_date,
#                 "label": y_col,
#                 "auc": auc,
#                 "brier": brier,
#                 "top_pick_name": top_pick["player_name"],
#                 "top_pick_dg_id": int(top_pick["dg_id"]),
#                 "top_pick_pred": float(top_pick["pred"]),
#                 "top_pick_hit": int(top_pick[y_col]),
#                 "top_pick_finish": float(top_pick["finish_num"]) if pd.notna(top_pick["finish_num"]) else np.nan,
#             })
#
#     return pd.DataFrame(rows).sort_values(["label","feature_set","event_date"])
#
# # Build event_order_2025 exactly like you already did earlier:
# # event_order_2025 must have columns: event_id, order_date
# # If you already have event_order_2025, skip this section.
# if "event_order_2025" not in globals():
#     sched_2025_key = sched_25[["year","event_id","start_date","rank"]].copy()
#     sched_2025_key["year"] = sched_2025_key["year"].astype(int)
#     sched_2025_key["event_id"] = sched_2025_key["event_id"].astype(int)
#     sched_2025_key["start_date"] = pd.to_datetime(sched_2025_key["start_date"], errors="coerce")
#
#     event_order_2025 = (
#         bt_df[["event_id","event_start_date"]].drop_duplicates()
#         .merge(sched_2025_key[["event_id","start_date","rank"]], on="event_id", how="left")
#     )
#     event_order_2025["order_date"] = event_order_2025["start_date"].where(
#         event_order_2025["start_date"].notna(), event_order_2025["event_start_date"]
#     )
#     event_order_2025 = event_order_2025.sort_values(["order_date","rank","event_id"]).reset_index(drop=True)
#
# # Compare feature sets:
# # - SG-only
# # - SG-only + field-relative
# # - Full + field-relative + target encodings (event/course)
# feat_sets_no_te = {
#     "SG_only": FEAT_SG_ONLY,
#     "SG_only+FieldRel": FEAT_SG_ONLY_PLUS_FIELD,
# }
# feat_sets_full_te = {
#     "Full+FieldRel(+TE)": FEAT_FULL_PLUS_FIELD_BASE,
# }
#
# # For walk-forward we want X_all to include field-relative features.
# # We’ll use fr_all (train+bt combined), computed from X (your master table).
# fr_all = add_field_relative_features(X.copy(), FIELD_RELATIVE_BASE)
#
# results = []
# for y_col in ["y_win","y_top5","y_top10"]:
#     r1 = walk_forward_2025_compare(
#         X_all=fr_all,
#         year_bt=BACKTEST_YEAR,
#         event_order_df=event_order_2025,
#         y_col=y_col,
#         feat_set_name_to_cols=feat_sets_no_te,
#         use_encodings=False,
#     )
#     r2 = walk_forward_2025_compare(
#         X_all=fr_all,
#         year_bt=BACKTEST_YEAR,
#         event_order_df=event_order_2025,
#         y_col=y_col,
#         feat_set_name_to_cols=feat_sets_full_te,
#         use_encodings=True,
#         encode_cols=ENCODE_COLS,
#         te_m=TE_M,
#     )
#     results.append(pd.concat([r1, r2], ignore_index=True))
#
# res = pd.concat(results, ignore_index=True)
#
# # Summary
# summary = (
#     res.groupby(["label","feature_set"], as_index=False)
#     .agg(
#         mean_hit_at1=("top_pick_hit","mean"),
#         mean_auc=("auc","mean"),
#         mean_brier=("brier","mean"),
#         n_events=("event_id","nunique"),
#     )
#     .sort_values(["label","mean_hit_at1","mean_auc"], ascending=[True, False, False])
# )
#
# display(summary)
#
# # Inspect per-event picks for top10 (most relevant)
# display(res[res["label"]=="y_top10"].sort_values(["feature_set","event_date"]).head(60))

Field-relative cols added: 21

     label         feature_set  mean_hit_at1  mean_auc  mean_brier  n_events
2  y_top10    SG_only+FieldRel      0.645161  0.785644    0.078567        31
1  y_top10             SG_only      0.645161  0.785284    0.078908        31
0  y_top10  Full+FieldRel(+TE)      0.580645  0.730817    0.185054        31
3   y_top5  Full+FieldRel(+TE)      0.451613  0.761765    0.092072        31
4   y_top5             SG_only      0.387097  0.787262    0.047898        31
5   y_top5    SG_only+FieldRel      0.354839  0.799698    0.047763        31
7    y_win             SG_only      0.129032  0.856306    0.008357        31
8    y_win    SG_only+FieldRel      0.096774  0.847356    0.008605        31
6    y_win  Full+FieldRel(+TE)      0.096774  0.797884    0.015768        31

,feature_set,event_id,event_date,label,auc,brier,top_pick_name,top_pick_dg_id,top_pick_pred,top_pick_hit,top_pick_finish
248,Full+FieldRel(+TE),6,2025-01-12,y_top10,0.691406,0.103103,"Spaun, J.J.",17536,0.039160,1,3.0
249,Full+FieldRel(+TE),2,2025-01-19,y_top10,0.452740,0.258869,"Spaun, J.J.",17536,0.993616,0,29.0
250,Full+FieldRel(+TE),4,2025-01-25,y_top10,0.575510,0.089432,"Manassero, Matteo",11460,0.259404,0,25.0
251,Full+FieldRel(+TE),5,2025-02-02,y_top10,0.728590,0.136510,"Davis, Cam",17786,0.008459,1,5.0
252,Full+FieldRel(+TE),3,2025-02-09,y_top10,0.637115,0.083248,"Thomas, Justin",14139,0.001385,1,6.0
253,Full+FieldRel(+TE),7,2025-02-16,y_top10,0.523100,0.135402,"Morikawa, Collin",22085,0.446713,0,17.0
254,Full+FieldRel(+TE),540,2025-02-23,y_top10,0.835417,0.090624,"Bhatia, Akshay",26096,0.003676,1,9.0
255,Full+FieldRel(+TE),10,2025-03-02,y_top10,0.767910,0.069036,"Clanton, Luke",32330,0.008542,0,18.0
256,Full+FieldRel(+TE),9,2025-03-09,y_top10,0.645161,0.138753,"McIlroy, Rory",10091,0.001446,0,15.0
257,Full+FieldRel(+TE),11,2025-03-16,y_top10,0.825701,0.075421,"McIlroy, Rory",10091,0.014830,1,1.0
258,Full+FieldRel(+TE),475,2025-03-23,y_top10,0.728562,0.907731,"Bridgeman, Jacob",29433,0.997401,1,3.0
259,Full+FieldRel(+TE),20,2025-03-30,y_top10,0.790909,0.065308,"Scheffler, Scottie",18417,0.001156,1,2.0
260,Full+FieldRel(+TE),41,2025-04-06,y_top10,0.759398,0.075996,"Conners, Corey",17576,0.018901,0,18.0
261,Full+FieldRel(+TE),14,2025-04-13,y_top10,0.857143,0.115701,"DeChambeau, Bryson",19841,0.000965,1,5.0
262,Full+FieldRel(+TE),12,2025-04-20,y_top10,0.833871,0.137824,"Scheffler, Scottie",18417,0.009165,1,8.0
263,Full+FieldRel(+TE),19,2025-05-04,y_top10,0.749421,0.068252,"Gerard, Ryan",29767,0.248601,0,NaN
264,Full+FieldRel(+TE),480,2025-05-11,y_top10,0.750000,0.137742,"McIlroy, Rory",10091,0.011248,1,7.0
265,Full+FieldRel(+TE),33,2025-05-18,y_top10,0.803125,0.090061,"Scheffler, Scottie",18417,0.383515,1,1.0
266,Full+FieldRel(+TE),21,2025-05-25,y_top10,0.645161,0.904209,"Salinda, Isaiah",27183,0.997497,0,NaN
267,Full+FieldRel(+TE),23,2025-06-01,y_top10,0.694486,0.151681,"Scheffler, Scottie",18417,0.013608,1,1.0
268,Full+FieldRel(+TE),32,2025-06-08,y_top10,0.828671,0.065422,"Pendrith, Taylor",17780,0.508539,0,27.0
269,Full+FieldRel(+TE),26,2025-06-15,y_top10,0.848903,0.059931,"Scheffler, Scottie",18417,0.218721,1,7.0
270,Full+FieldRel(+TE),34,2025-06-22,y_top10,0.696970,0.150213,"Scheffler, Scottie",18417,0.056926,1,6.0
271,Full+FieldRel(+TE),524,2025-06-29,y_top10,0.876736,0.076429,"Griffin, Ben",24968,0.010803,0,13.0
272,Full+FieldRel(+TE),30,2025-07-06,y_top10,0.615068,0.063863,"Champ, Cameron",23542,0.005332,0,27.0
273,Full+FieldRel(+TE),541,2025-07-13,y_top10,0.814483,0.062588,"Scheffler, Scottie",18417,0.049544,1,8.0
274,Full+FieldRel(+TE),100,2025-07-20,y_top10,0.891877,0.066168,"McIlroy, Rory",10091,0.248130,1,7.0
275,Full+FieldRel(+TE),525,2025-07-27,y_top10,0.704702,0.927752,"Hisatsune, Ryo",22760,0.999745,0,NaN
276,Full+FieldRel(+TE),13,2025-08-03,y_top10,0.840411,0.060900,"Fitzpatrick, Matt",17646,0.080665,1,8.0
277,Full+FieldRel(+TE),27,2025-08-10,y_top10,0.776099,0.188098,"Scheffler, Scottie",18417,0.003504,1,3.0
278,Full+FieldRel(+TE),28,2025-08-17,y_top10,0.466667,0.180418,"Harman, Brian",8825,0.627456,0,19.0
186,SG_only,6,2025-01-12,y_top10,0.679427,0.090733,"Clanton, Luke",32330,0.415771,0,NaN
187,SG_only,2,2025-01-19,y_top10,0.786986,0.053984,"Spaun, J.J.",17536,0.348615,0,29.0
188,SG_only,4,2025-01-25,y_top10,0.656888,0.083540,"Matsuyama, Hideki",13562,0.387185,0,32.0
189,SG_only,5,2025-02-02,y_top10,0.762846,0.106702,"Straka, Sepp",17511,0.306507,1,7.0
190,SG_only,3,2025-02-09,y_top10,0.664162,0.070783,"Thomas, Justin",14139,0.407843,1,6.0
191,SG_only,7,2025-02-16,y_top10,0.728763,0.121007,"Berger, Daniel",17606,0.281938,0,12.0
192,SG_only,540,2025-02-23,y_top10,0.839583,0.074871,"Bhatia, Akshay",26096,0.296450,1,9.0
193,SG_only,10,2025-03-02,y_top10,0.785075,0.057960,"Spaun, J.J.",17536,0.332389,1,2.0
194,SG_only,9,2025-03-09,y_top10,0.580645,0.120085,"McIlroy, Rory",10091,0.318162,0,15.0
195,SG_only,11,2025-03-16,y_top10,0.800410,0.062813,"Spaun, J.J.",17536,0.376209,1,2.0
196,SG_only,475,2025-03-23,y_top10,0.860090,0.055387,"Conners, Corey",17576,0.425244,1,8.0
197,SG_only,20,2025-03-30,y_top10,0.823776,0.053369,"Scheffler, Scottie",18417,0.415265,1,2.0
198,SG_only,41,2025-04-06,y_top10,0.772727,0.068248,"Valimaki, Sami",23816,0.431019,0,12.0
199,SG_only,14,2025-04-13,y_top10,0.850649,0.082007,"McIlroy, Rory",10091,0.465365,1,1.0
200,SG_only,12,2025-04-20,y_top10,0.770968,0.107721,"Hovland, Viktor",18841,0.436674,0,13.0
201,SG_only,19,2025-05-04,y_top10,0.730035,0.064811,"Scheffler, Scottie",18417,0.570105,1,1.0
202,SG_only,480,2025-05-11,y_top10,0.730645,0.108261,"Thomas, Justin",14139,0.294592,1,2.0
203,SG_only,33,2025-05-18,y_top10,0.830580,0.076416,"Scheffler, Scottie",18417,0.561968,1,1.0
204,SG_only,21,2025-05-25,y_top10,0.822581,0.058505,"Scheffler, Scottie",18417,0.590444,1,4.0
205,SG_only,23,2025-06-01,y_top10,0.646796,0.115987,"Scheffler, Scottie",18417,0.603253,1,1.0
206,SG_only,32,2025-06-08,y_top10,0.827506,0.065504,"Conners, Corey",17576,0.342171,0,27.0
207,SG_only,26,2025-06-15,y_top10,0.913480,0.048909,"Scheffler, Scottie",18417,0.624857,1,7.0
208,SG_only,34,2025-06-22,y_top10,0.784091,0.109400,"Scheffler, Scottie",18417,0.603565,1,6.0
209,SG_only,524,2025-06-29,y_top10,0.898727,0.060692,"Hubbard, Mark",16333,0.353710,0,13.0
210,SG_only,30,2025-07-06,y_top10,0.722603,0.058389,"Lawrence, Thriston",18105,0.268210,0,44.0
211,SG_only,541,2025-07-13,y_top10,0.794138,0.052480,"Scheffler, Scottie",18417,0.592399,1,8.0
212,SG_only,100,2025-07-20,y_top10,0.899408,0.057532,"Scheffler, Scottie",18417,0.651093,1,1.0
213,SG_only,525,2025-07-27,y_top10,0.825078,0.056109,"Gotterup, Chris",27774,0.406590,1,10.0
214,SG_only,13,2025-08-03,y_top10,0.865753,0.054409,"Matsuyama, Hideki",13562,0.400759,0,19.0

In [21]:
# ============================================================
# WIN-ONLY MODEL (P(win)) — 2025 walk-forward, NO FUTURE INFO
# Assumes you already built X with:
#   columns: year, event_id, event_start_date, player_name, dg_id, finish_num, y_win
#   and rolling features like sg_total_L40/L24/L12
# ============================================================
import numpy as np
import pandas as pd

from sklearn.experimental import enable_hist_gradient_boosting  # no
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import brier_score_loss, roc_auc_score

# -----------------------------
# EDIT: feature set (SG-only)
# -----------------------------
WIN_FEATURES = ["sg_total_L40", "sg_total_L24", "sg_total_L12"]

# Optional: add simple recency shape features (often helps a bit)
# Uncomment if you want:
# WIN_FEATURES += ["sg_total_L12_minus_L40"]
# (we'll build it below if used)

# -----------------------------
# Calibration
# -----------------------------
USE_CALIBRATION = True
CAL_METHOD = "sigmoid"   # "sigmoid" (safer) or "isotonic" (can overfit)
CAL_FOLDS = 5            # grouped by year within training window

RANDOM_SEED = 42

def safe_auc(y_true, y_prob):
    if len(np.unique(y_true)) < 2:
        return np.nan
    return roc_auc_score(y_true, y_prob)

def build_base_model():
    return HistGradientBoostingClassifier(
        loss="log_loss",
        learning_rate=0.05,
        max_depth=6,
        max_iter=400,
        min_samples_leaf=40,
        l2_regularization=0.0,
        random_state=RANDOM_SEED,
    )

# Build event_name lookup from OAD schedule (2025)
sched = pd.read_excel(SCHED_2025)  # or whatever your 2025 schedule path variable is
sched["event_id"] = pd.to_numeric(sched["event_id"], errors="coerce").astype("Int64")

event_name_map = (
    sched.dropna(subset=["event_id"])
         .drop_duplicates(subset=["event_id"])
         .set_index("event_id")["event_name"]
         .to_dict()
)

def fit_model_with_year_sigmoid_calibration(train_df, feat_cols, label_col="y_win"):
    """
    Time-safe calibration:
      1) make OOF base-model probabilities using year-based folds
      2) fit sigmoid calibrator (logistic regression) on OOF probs
      3) refit base model on full train
    Returns: (base_model, calibrator_or_None)
    """
    tr = train_df.dropna(subset=feat_cols + [label_col, "year"]).copy()
    Xtr = tr[feat_cols]
    ytr = tr[label_col].astype(int).values
    years = tr["year"].astype(int).values
    uniq_years = np.unique(years)

    base = build_base_model()

    # If not enough distinct years, skip calibration
    if (not USE_CALIBRATION) or (len(uniq_years) < 3):
        base.fit(Xtr, ytr)
        return base, None

    # Build year folds: each fold holds out one year (or a few years if many)
    # Simple LOYO:
    oof = np.zeros(len(tr), dtype=float)
    oof[:] = np.nan

    for y in uniq_years:
        idx_te = np.where(years == y)[0]
        idx_tr = np.where(years != y)[0]

        # Need both classes in training fold
        if len(np.unique(ytr[idx_tr])) < 2:
            continue

        m = build_base_model()
        m.fit(Xtr.iloc[idx_tr], ytr[idx_tr])
        oof[idx_te] = m.predict_proba(Xtr.iloc[idx_te])[:, 1]

    ok = np.isfinite(oof)
    if ok.mean() < 0.8 or len(np.unique(ytr[ok])) < 2:
        # too many NaNs or degenerate folds -> skip calibration
        base.fit(Xtr, ytr)
        return base, None

    # Sigmoid calibration: P = sigmoid(a * logit(p) + b)
    # To stabilize, calibrate on logit(p) with clipping
    eps = 1e-6
    p = np.clip(oof[ok], eps, 1 - eps)
    logit_p = np.log(p / (1 - p)).reshape(-1, 1)

    cal = LogisticRegression(solver="lbfgs")
    cal.fit(logit_p, ytr[ok])

    # Refit base on full training
    base.fit(Xtr, ytr)
    return base, cal

def predict_proba_calibrated(base_model, calibrator, X):
    p = base_model.predict_proba(X)[:, 1]
    if calibrator is None:
        return p
    eps = 1e-6
    p2 = np.clip(p, eps, 1 - eps)
    logit_p = np.log(p2 / (1 - p2)).reshape(-1, 1)
    return calibrator.predict_proba(logit_p)[:, 1]


# ============================================================
# 0) Prepare X and event order for 2025
# ============================================================
BACKTEST_YEAR = 2025

df_all = X.copy()

# Create optional derived features if requested
if "sg_total_L12_minus_L40" in WIN_FEATURES and "sg_total_L12_minus_L40" not in df_all.columns:
    df_all["sg_total_L12_minus_L40"] = df_all["sg_total_L12"] - df_all["sg_total_L40"]

# Ensure event_start_date exists and is datetime
df_all["event_start_date"] = pd.to_datetime(df_all["event_start_date"], errors="coerce")

# Build event order for 2025
bt_events = (
    df_all[df_all["year"] == BACKTEST_YEAR][["event_id","event_start_date"]]
    .dropna()
    .drop_duplicates()
    .sort_values("event_start_date")
    .reset_index(drop=True)
)

# If you have rank/order in schedule and want it, merge it here (optional)
# bt_events = bt_events.merge(sched_25[["event_id","rank"]], on="event_id", how="left").sort_values(["event_start_date","rank","event_id"])

print("2025 events found:", len(bt_events))

# ============================================================
# 1) Walk-forward: for each 2025 event, train on ALL prior data, predict that event
# ============================================================
event_boards = []   # per-player per-event predictions
event_summ   = []   # per-event summary
event_top10 = []

# ============================
# Add: event_skill + odds blend (stats-first)
# ============================

# 1) Load once, ABOVE the loop (do this near where you set BACKTEST_YEAR)
EVENT_SKILL_PATH = "/Data/in Use/event_skill.xlsx"
event_skill_df = pd.read_excel(EVENT_SKILL_PATH)
event_skill_df["year"] = pd.to_numeric(event_skill_df["year"], errors="coerce").astype("Int64")
event_skill_df["event_id"] = pd.to_numeric(event_skill_df["event_id"], errors="coerce").astype("Int64")

# Optional: keep just what we need
event_skill_df = event_skill_df[["year","event_id","event_name","avg_skill","x_score"]].copy()

def _logit(p, eps=1e-6):
    p = np.clip(p, eps, 1 - eps)
    return np.log(p / (1 - p))

def _sigmoid(z):
    return 1 / (1 + np.exp(-z))

def blend_stats_odds_with_field_strength(board, year, ev_id, event_skill_df):
    """
    board must contain:
      - p_win_raw  (stats model prob, NOT normalized)
      - close_odds (decimal odds)
    returns board with:
      - p_win_blend_raw
      - p_win_blend_norm
      - blend_weight
      - x_score (if found)
    """
    b = board.copy()

    # Pull event x_score (pre-event, safe)
    row = event_skill_df[(event_skill_df["year"] == year) & (event_skill_df["event_id"] == ev_id)]
    if row.empty:
        x = np.nan
        # conservative default if missing
        w_event = 0.20
        ev_name = None
    else:
        x = float(row["x_score"].iloc[0])
        ev_name = row["event_name"].iloc[0] if "event_name" in row.columns else None

        # Map x_score -> weight. Clamp to keep odds "a little bit".
        # You can tune these later, but start simple:
        # typical x_score seems around ~0.7–1.0 from your image
        w_event = 0.10 + 0.30 * ((x - 0.70) / (1.00 - 0.70))  # 0.10..0.40 roughly
        w_event = float(np.clip(w_event, 0.10, 0.35))

    # Odds implied prob within event
    p_odds_raw = 1.0 / pd.to_numeric(b["close_odds"], errors="coerce")
    p_odds_raw = p_odds_raw.fillna(p_odds_raw.median())
    p_odds = p_odds_raw / (p_odds_raw.sum() + 1e-12)

    # Stats prob: use p_win_raw (not normalized) and normalize to an event prior first
    p_stats_raw = pd.to_numeric(b["p_win_raw"], errors="coerce").fillna(0.0)
    p_stats = p_stats_raw / (p_stats_raw.sum() + 1e-12)

    # Blend in logit space, then renormalize
    z = _logit(p_stats.values) + w_event * _logit(p_odds.values)
    p_blend = _sigmoid(z)

    b["p_win_blend_raw"] = p_blend
    b["p_win_blend_norm"] = b["p_win_blend_raw"] / (b["p_win_blend_raw"].sum() + 1e-12)
    b["blend_weight"] = w_event
    b["x_score"] = x
    if ev_name is not None:
        b["event_name"] = ev_name
    return b


for _, ev in bt_events.iterrows():
    ev_id = int(ev["event_id"])
    ev_date = pd.to_datetime(ev["event_start_date"])
    ev_name = sched.loc[sched["event_id"] == ev_id, "event_name"].iloc[0] if (sched is not None and (sched["event_id"] == ev_id).any()) else ""
    ev_name = event_name_map.get(ev_id, "UNKNOWN_EVENT")
    print(f"\n=== Event {ev_id} | {ev_date.date()} | {ev_name} ===")

    # Training data = all years < 2025 plus 2025 events strictly before this event date
    train_df = df_all[
        (df_all["year"] < BACKTEST_YEAR) |
        ((df_all["year"] == BACKTEST_YEAR) & (df_all["event_start_date"] < ev_date))
    ].copy()

    test_df = df_all[(df_all["year"] == BACKTEST_YEAR) & (df_all["event_id"] == ev_id)].copy()
    if test_df.empty or train_df.empty:
        continue

    # require features present
    feat_cols = [c for c in WIN_FEATURES if c in train_df.columns]
    missing = set(WIN_FEATURES) - set(feat_cols)
    if missing:
        print("Missing features for event", ev_id, ":", sorted(missing))
        continue

    base_model, calibrator = fit_model_with_year_sigmoid_calibration(train_df, feat_cols, label_col="y_win")
    p = predict_proba_calibrated(base_model, calibrator, test_df[feat_cols])
    was_cal = int(calibrator is not None)

    test_df = test_df.copy()
    test_df["p_win"] = p
    test_df["was_calibrated"] = int(was_cal)

    # Mark actual winner (finish_num == 1)
    test_df["is_winner"] = (pd.to_numeric(test_df["finish_num"], errors="coerce") == 1).astype(int)

    # Board
    board_cols = ["year","event_id","event_start_date","dg_id","player_name","finish_num","is_winner","p_win","was_calibrated"] + feat_cols
    board = test_df[board_cols].copy()
    board = board.sort_values("p_win", ascending=False).reset_index(drop=True)
    board["pred_rank"] = np.arange(1, len(board)+1)
    event_boards.append(board)

        # Normalize win probs to sum to ~1 per event (win-share)
    eps = 1e-12
    board["p_win_raw"] = board["p_win"]
    board["p_win_norm"] = board["p_win_raw"] / (board["p_win_raw"].sum() + eps)

        # Ensure close_odds is on board (bring it from test_df if needed)
    if "close_odds" not in board.columns and "close_odds" in test_df.columns:
        board = board.merge(
            test_df[["dg_id","close_odds"]],
            on="dg_id",
            how="left"
        )

    board = blend_stats_odds_with_field_strength(
        board=board,
        year=BACKTEST_YEAR,
        ev_id=ev_id,
        event_skill_df=event_skill_df
    )

    # If you want to rank/display by blended instead of stats-only:
    board = board.sort_values("p_win_blend_norm", ascending=False).reset_index(drop=True)
    board["pred_rank"] = np.arange(1, len(board)+1)


    top10_board = board.head(10)[[
        "year","event_id","event_start_date","pred_rank",
        "player_name","dg_id",
        "p_win_norm","p_win_raw",
        "sg_total_L40","sg_total_L24","sg_total_L12",
    ]].copy()

    # nice formatting for display
    top10_board["p_win_norm_pct"] = (100 * top10_board["p_win_norm"]).round(2)
    top10_board["p_win_raw_pct"]  = (100 * top10_board["p_win_raw"]).round(2)

    display(
        top10_board[[
            "pred_rank","player_name","dg_id",
            "p_win_norm_pct","p_win_raw_pct",
            "sg_total_L40","sg_total_L24","sg_total_L12"
        ]]
    )


    # Event summary: top pick + winner rank
    top_pick = board.iloc[0]
    winner_rows = board[board["is_winner"] == 1]
    winner_rank = int(winner_rows["pred_rank"].iloc[0]) if not winner_rows.empty else np.nan
    winner_name = winner_rows["player_name"].iloc[0] if not winner_rows.empty else None
    winner_prob = float(winner_rows["p_win_norm"].iloc[0]) if not winner_rows.empty else np.nan

    eval_board = board.dropna(subset=["finish_num"]).copy()
    y_true = eval_board["is_winner"].values
    y_prob = eval_board["p_win_norm"].values
    brier = brier_score_loss(y_true, y_prob)
    auc = safe_auc(y_true, y_prob)


    event_summ.append({
        "event_id": ev_id,
        "event_date": ev_date,
        "calibrated": int(was_cal),
        "top_pick": top_pick["player_name"],
        "top_pick_pwin": float(top_pick["p_win_norm"]),
        "top_pick_won": int(top_pick["is_winner"]),
        "winner_name": winner_name,
        "winner_rank": winner_rank,
        "winner_pwin": winner_prob,
        "brier": brier,
        "auc": auc,
        "n_field": len(board),
    })

boards_2025 = pd.concat(event_boards, ignore_index=True) if event_boards else pd.DataFrame()
summ_2025   = pd.DataFrame(event_summ).sort_values("event_date") if event_summ else pd.DataFrame()
top10_all_2025 = pd.concat(event_top10, ignore_index=True) if event_top10 else pd.DataFrame()


print("Events scored:", summ_2025["event_id"].nunique() if not summ_2025.empty else 0)
display(summ_2025.head(40))

# ============================================================
# 2) "What % of the time these players won" — in a meaningful way
#    A) Per-event: show the board with P(win) and actual winner
#    B) Calibration: do predicted probabilities match observed win rates (aggregate)?
#    C) Per-player in 2025: avg P(win) vs actual wins
# ============================================================

# A) Example: show top 15 for a chosen event_id (edit)
EXAMPLE_EVENT_ID = int(summ_2025["event_id"].iloc[0]) if not summ_2025.empty else None
if EXAMPLE_EVENT_ID is not None:
    display(
        boards_2025[boards_2025["event_id"] == EXAMPLE_EVENT_ID]
        .sort_values("p_win", ascending=False)
        .head(15)
    )

# B) Calibration table (aggregate across all 2025 player-event rows)
# B) Calibration table (aggregate across all 2025 player-event rows) — use p_win_norm
if not boards_2025.empty:
    tmp = boards_2025.copy()

    # If you want calibration only on players with known outcomes:
    # tmp = tmp.dropna(subset=["finish_num"]).copy()

    bins = [0, 0.002, 0.005, 0.01, 0.02, 0.04, 0.07, 0.10, 0.20, 1.0]
    tmp["p_bin"] = pd.cut(tmp["p_win_norm"], bins=bins, include_lowest=True)

    calib = (
        tmp.groupby("p_bin", as_index=False)
        .agg(
            n=("p_win_norm","size"),
            avg_pred_pwin=("p_win_norm","mean"),
            observed_win_rate=("is_winner","mean"),
        )
    )
    display(calib)

# C) Per-player summary (2025): "model says you win X% on average when you tee it up"
if not boards_2025.empty:
    player_2025 = (
        boards_2025.groupby(["dg_id","player_name"], as_index=False)
        .agg(
            starts=("event_id","nunique"),
            wins=("is_winner","sum"),
            avg_pwin=("p_win","mean"),
            max_pwin=("p_win","max"),
        )
        .sort_values(["wins","avg_pwin","starts"], ascending=[False, False, False])
    )
    display(player_2025.head(50))

2025 events found: 31

=== Event 6 | 2025-01-12 | Sony Open in Hawaii ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Henley, Russell",14578,3.84,5.45,1.302175,1.322500,1.076083
1,2,"Matsuyama, Hideki",13562,2.39,3.39,1.580925,1.627917,1.633583
2,3,"McNealy, Maverick",18634,2.96,4.20,1.117150,0.975458,1.002417
3,4,"Clanton, Luke",32330,2.63,3.73,1.660250,1.660250,1.809500
4,5,"Stevens, Sam",25569,3.22,4.58,0.463625,0.631708,-0.054167
5,6,"Horschel, Billy",11276,2.44,3.46,1.160025,1.018750,0.587833
6,7,"Phillips, Chandler",27164,2.75,3.90,0.062000,0.265250,-0.800000
7,8,"Hoey, Rico",23504,2.56,3.64,0.573400,0.778958,0.355167
8,9,"Novak, Andrew",23475,1.95,2.76,0.737125,0.735833,0.055083
9,10,"McCarthy, Denny",19870,1.77,2.52,0.555325,0.663792,1.260583

=== Event 2 | 2025-01-19 | The American Express ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Meissner, Mac",28159,8.49,10.98,0.897600,0.632375,0.765000
1,2,"Greyserman, Max",23465,3.16,4.09,0.921875,1.453292,0.469167
2,3,"Hall, Harry",27194,2.56,3.31,0.793675,1.302875,1.564917
3,4,"Spaun, J.J.",17536,2.28,2.95,1.009425,2.055917,2.287333
4,5,"Smalley, Alex",18474,2.22,2.87,-0.479150,0.251500,1.336917
5,6,"Johnson, Zach",6986,2.49,3.22,0.253475,0.310750,0.370667
6,7,"Cantlay, Patrick",15466,1.22,1.58,1.320875,1.771667,1.368000
7,8,"Thomas, Justin",14139,1.08,1.39,0.790000,0.620542,0.034667
8,9,"Taylor, Nick",13126,1.90,2.45,-0.004425,0.263458,0.378333
9,10,"Burns, Sam",19483,1.15,1.48,1.267275,1.202792,1.510917

=== Event 4 | 2025-01-25 | Farmers Insurance Open ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Griffin, Ben",24968,3.65,4.61,0.381550,0.325792,0.334750
1,2,"Clanton, Luke",32330,3.19,4.03,1.602609,1.602609,1.303000
2,3,"Matsuyama, Hideki",13562,2.07,2.61,1.565275,1.482625,2.503000
3,4,"Kitayama, Kurt",21891,2.62,3.31,0.371575,0.788167,0.148750
4,5,"Day, Jason",9771,2.31,2.91,0.914375,1.274750,1.106417
5,6,"Finau, Tony",11676,1.77,2.23,1.258525,0.874917,0.255917
6,7,"Spaun, J.J.",17536,1.95,2.46,1.176675,1.927958,1.849833
7,8,"Pendrith, Taylor",17780,1.61,2.04,0.870875,0.625625,0.791667
8,9,"McNealy, Maverick",18634,1.50,1.89,0.924100,0.652917,0.542083
9,10,"Rai, Aaron",18554,1.75,2.21,1.399700,0.661750,0.179167

=== Event 5 | 2025-02-02 | AT&T Pebble Beach Pro-Am ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Pendrith, Taylor",17780,7.57,6.32,0.894625,1.173833,0.986417
1,2,"McIlroy, Rory",10091,3.68,3.07,1.641800,0.946083,-0.004250
2,3,"Scheffler, Scottie",18417,2.57,2.15,2.308175,1.648708,1.061833
3,4,"Henley, Russell",14578,5.30,4.42,1.404425,1.332167,1.512583
4,5,"Aberg, Ludvig",23950,2.50,2.09,1.192075,0.349667,0.296583
5,6,"Straka, Sepp",17511,3.37,2.81,1.033225,1.455375,2.589500
6,7,"Cantlay, Patrick",15466,2.22,1.85,1.277650,1.393333,1.301583
7,8,"Stevens, Sam",25569,3.74,3.12,0.852900,0.808000,1.670167
8,9,"Morikawa, Collin",22085,1.89,1.58,1.811050,1.170792,0.561833
9,10,"Day, Jason",9771,2.30,1.92,0.835900,1.284333,1.832333

=== Event 3 | 2025-02-09 | WM Phoenix Open ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Thomas, Justin",14139,3.43,3.96,0.743775,0.687083,1.847417
1,2,"Straka, Sepp",17511,4.25,4.91,0.806025,1.301917,2.527750
2,3,"Scheffler, Scottie",18417,1.73,2.00,2.185375,1.866625,1.164833
3,4,"Matsuyama, Hideki",13562,2.48,2.86,1.312175,1.333667,1.033750
4,5,"Burns, Sam",19483,2.05,2.37,1.019325,0.848375,0.732917
5,6,"Thorbjornsen, Michael",26649,3.27,3.77,0.136450,0.317333,-0.761250
6,7,"Power, Seamus",10104,3.14,3.63,0.602275,0.453583,0.168250
7,8,"Clanton, Luke",32330,2.55,2.94,1.452500,1.524917,1.095833
8,9,"Taylor, Nick",13126,2.28,2.64,0.340000,0.689417,1.435250
9,10,"Detry, Thomas",14181,2.50,2.89,0.511275,0.661333,1.752583

=== Event 7 | 2025-02-16 | Genesis Invitational ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,4.04,3.40,2.051825,1.566125,1.467667
1,2,"Pendrith, Taylor",17780,6.50,5.48,0.901500,0.752333,0.702333
2,3,"Matsuyama, Hideki",13562,5.03,4.24,1.386525,1.567208,0.631417
3,4,"Burns, Sam",19483,5.27,4.44,1.104350,1.047500,0.584083
4,5,"Cantlay, Patrick",15466,3.57,3.01,1.323050,1.295917,1.343917
5,6,"Morikawa, Collin",22085,2.86,2.41,1.506175,0.823375,0.359167
6,7,"McIlroy, Rory",10091,2.13,1.80,1.812200,0.914583,1.442500
7,8,"Kim, Michael",17543,5.35,4.50,0.320025,0.205750,1.056250
8,9,"Thomas, Justin",14139,2.86,2.41,0.747300,0.866625,1.698583
9,10,"Henley, Russell",14578,3.72,3.14,1.395950,1.526417,1.304917

=== Event 540 | 2025-02-23 | Mexico Open ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Bhatia, Akshay",26096,3.36,2.81,0.861475,0.639625,1.504583
1,2,"Rai, Aaron",18554,4.07,3.41,1.016850,0.606708,0.491583
2,3,"Manassero, Matteo",11460,4.01,3.36,0.603667,0.603667,0.704250
3,4,"Stevens, Sam",25569,2.51,2.10,0.509950,0.768500,0.097500
4,5,"Kim, Michael",17543,2.25,1.88,0.482350,0.584417,1.717333
5,6,"Bridgeman, Jacob",29433,2.66,2.23,0.897975,0.801708,0.378333
6,7,"Moore, Taylor",21944,1.65,1.38,0.363325,0.494042,0.702750
7,8,"Lower, Justin",17723,1.91,1.60,0.359500,0.598625,0.236833
8,9,"Griffin, Ben",24968,1.55,1.30,0.229000,0.298167,0.254583
9,10,"Smalley, Alex",18474,1.60,1.34,0.305875,1.406208,1.596417

=== Event 10 | 2025-03-02 | Cognizant Classic ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Lowry, Shane",13900,2.67,3.07,0.907800,0.704167,1.012917
1,2,"Manassero, Matteo",11460,4.41,5.07,0.268458,0.268458,0.097000
2,3,"Ghim, Doug",24550,3.04,3.50,0.256150,0.198375,0.322667
3,4,"Dahmen, Joel",14509,2.89,3.32,0.590575,0.431917,1.534667
4,5,"Clanton, Luke",32330,2.22,2.55,1.440207,1.530875,0.634417
5,6,"Smalley, Alex",18474,2.15,2.47,0.579175,1.268292,1.441167
6,7,"Greyserman, Max",23465,2.21,2.53,0.712150,0.446958,-0.206417
7,8,"Svensson, Jesper",26850,2.74,3.15,0.398167,0.338792,0.357833
8,9,"Bridgeman, Jacob",29433,2.46,2.82,0.889050,0.775583,0.625333
9,10,"Power, Seamus",10104,2.07,2.38,0.575325,0.335625,0.525417

=== Event 9 | 2025-03-09 | Arnold Palmer Invitational ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Aberg, Ludvig",23950,4.88,4.30,0.975375,0.375625,0.398917
1,2,"Fleetwood, Tommy",12294,4.73,4.17,1.063800,0.783042,1.364750
2,3,"Scheffler, Scottie",18417,2.20,1.94,1.878825,1.403125,1.744417
3,4,"Henley, Russell",14578,5.00,4.41,1.501625,1.622750,1.732917
4,5,"Thomas, Justin",14139,3.96,3.49,0.992375,1.246917,1.577750
5,6,"Cantlay, Patrick",15466,3.40,2.99,1.228475,1.007917,0.647833
6,7,"Matsuyama, Hideki",13562,3.39,2.99,1.064475,1.010292,0.577750
7,8,"Griffin, Ben",24968,4.27,3.77,0.588275,0.516417,1.750667
8,9,"Straka, Sepp",17511,3.80,3.35,1.044925,1.605208,0.972750
9,10,"McIlroy, Rory",10091,1.96,1.73,1.367625,0.574708,1.948083

=== Event 11 | 2025-03-16 | The Players Championship ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Henley, Russell",14578,4.96,6.91,1.399125,1.533000,1.761083
1,2,"Cantlay, Patrick",15466,2.72,3.80,1.537300,1.379000,1.456417
2,3,"Scheffler, Scottie",18417,1.32,1.84,1.717500,1.399208,1.633583
3,4,"Thomas, Justin",14139,1.71,2.39,0.839375,1.532167,1.216917
4,5,"Rai, Aaron",18554,2.34,3.27,0.849100,0.616958,1.640833
5,6,"Lowry, Shane",13900,1.80,2.51,1.210775,1.257708,1.261083
6,7,"Bhatia, Akshay",26096,2.30,3.20,0.632200,0.730833,1.704667
7,8,"Schauffele, Xander",19895,1.40,1.96,2.082150,1.461750,0.552583
8,9,"Morikawa, Collin",22085,1.13,1.57,1.546850,1.134125,1.706417
9,10,"Berger, Daniel",17606,1.66,2.31,1.043575,1.492000,1.511083

=== Event 475 | 2025-03-23 | Valspar Championship ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Conners, Corey",17576,6.30,7.31,0.602900,0.806458,2.682167
1,2,"Straka, Sepp",17511,2.65,3.08,1.290725,1.187750,1.547583
2,3,"Fleetwood, Tommy",12294,1.95,2.26,1.216250,1.395667,1.682167
3,4,"Thomas, Justin",14139,1.77,2.06,0.966550,1.357042,1.015500
4,5,"Lowry, Shane",13900,2.03,2.35,1.295050,1.571917,2.130917
5,6,"Poston, J.T.",21554,2.39,2.77,0.293875,0.383125,0.265500
6,7,"Glover, Lucas",7399,1.89,2.19,0.547375,1.051250,1.377917
7,8,"Griffin, Ben",24968,2.05,2.38,0.340850,0.693000,0.382833
8,9,"Shipley, Neal",32055,2.64,3.07,0.210333,0.210333,0.008583
9,10,"Bridgeman, Jacob",29433,1.44,1.67,1.186875,1.253125,1.880917

=== Event 20 | 2025-03-30 | Texas Children's Houston Open ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,1.47,4.27,1.816075,1.769583,2.071500
1,2,"McIlroy, Rory",10091,1.27,3.69,1.360600,1.673667,1.904833
2,3,"Lee, Min Woo",16841,1.39,4.04,0.743775,1.261750,2.040167
3,4,"Spaun, J.J.",17536,1.27,3.69,1.466675,1.252750,1.837750
4,5,"Day, Jason",9771,0.92,2.67,0.919025,1.045500,0.258667
5,6,"Pendrith, Taylor",17780,0.89,2.60,0.746425,0.510542,0.318750
6,7,"Riley, Davis",19872,1.13,3.29,-0.403325,-0.332500,1.345167
7,8,"Griffin, Ben",24968,0.93,2.70,0.395150,0.632375,-0.167750
8,9,"Kim, Michael",17543,0.78,2.26,1.031150,1.420583,1.487250
9,10,"Thompson, Davis",27364,0.77,2.24,0.358000,0.675333,0.818750

=== Event 41 | 2025-04-06 | Valero Texas Open ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Cantlay, Patrick",15466,1.45,3.59,1.397150,1.363042,1.382167
1,2,"Conners, Corey",17576,1.19,2.95,0.589250,1.238292,2.148833
2,3,"McCarthy, Denny",19870,1.29,3.19,1.156825,1.275667,1.580917
3,4,"Fleetwood, Tommy",12294,0.96,2.36,1.154800,1.506792,1.648833
4,5,"Aberg, Ludvig",23950,0.85,2.11,0.792575,0.607167,0.917750
5,6,"Berger, Daniel",17606,1.08,2.68,0.948750,1.465375,0.997583
6,7,"Bradley, Keegan",13872,0.95,2.35,0.897950,0.807833,1.548833
7,8,"Matsuyama, Hideki",13562,0.86,2.13,0.965125,0.583292,0.334417
8,9,"Cauley, Bud",14502,1.10,2.73,0.580225,1.346000,1.905833
9,10,"Bhatia, Akshay",26096,0.84,2.09,0.572800,1.128708,1.292750

=== Event 14 | 2025-04-13 | Masters Tournament ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,2.84,5.89,1.885825,2.098333,2.452250
1,2,"McIlroy, Rory",10091,3.10,6.43,1.594900,2.575167,3.202250
2,3,"Morikawa, Collin",22085,2.04,4.22,1.451575,1.433917,2.508667
3,4,"DeChambeau, Bryson",19841,2.03,4.20,1.804450,2.265542,3.452667
4,5,"Lowry, Shane",13900,1.83,3.78,1.275200,1.545792,2.025333
5,6,"Thomas, Justin",14139,1.53,3.18,0.913050,1.259875,0.942000
6,7,"Rahm, Jon",19195,1.24,2.57,1.070425,0.962417,1.017583
7,8,"Schauffele, Xander",19895,1.33,2.76,1.567100,1.084542,0.525333
8,9,"Henley, Russell",14578,1.88,3.89,1.518000,1.517583,1.750750
9,10,"MacIntyre, Robert",23323,1.59,3.30,0.986250,0.776375,0.638917

=== Event 12 | 2025-04-20 | RBC Heritage ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,2.93,4.67,1.797475,2.067875,2.502167
1,2,"Hovland, Viktor",18841,3.91,6.23,0.759600,0.483333,2.039667
2,3,"Thomas, Justin",14139,2.51,4.00,1.300675,1.521083,1.825250
3,4,"Henley, Russell",14578,2.41,3.84,1.476575,1.431500,1.724500
4,5,"Cantlay, Patrick",15466,2.01,3.21,1.089925,1.070250,0.684083
5,6,"Schauffele, Xander",19895,1.63,2.61,1.379575,0.563917,0.575250
6,7,"Morikawa, Collin",22085,1.48,2.36,1.141550,1.160792,0.873500
7,8,"Hoge, Tom",15575,2.59,4.13,0.032325,0.430917,1.850750
8,9,"McCarthy, Denny",19870,2.02,3.22,0.941375,0.764250,0.767417
9,10,"Aberg, Ludvig",23950,1.23,1.97,0.637175,0.443208,0.487500

=== Event 19 | 2025-05-04 | CJ Cup Byron Nelson ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,2.79,7.13,2.025800,2.669500,3.267500
1,2,"Hughes, Mackenzie",15556,1.47,3.75,0.044700,0.342750,1.566917
2,3,"Cole, Eric",21756,1.61,4.09,-0.005000,0.761125,1.535000
3,4,"Griffin, Ben",24968,1.28,3.26,0.341425,0.706417,0.572917
4,5,"Im, Sungjae",17488,1.06,2.71,0.693100,0.725708,1.517500
5,6,"Spieth, Jordan",14636,0.91,2.32,0.427900,1.063958,1.305417
6,7,"Gerard, Ryan",29767,1.18,3.00,1.006250,0.973875,1.035083
7,8,"Kuchar, Matt",6169,1.31,3.34,0.869925,0.338708,0.761500
8,9,"Hahn, James",11374,1.53,3.90,-0.470000,-0.564250,-0.298833
9,10,"Springer, Hayden",21995,1.22,3.11,0.599000,0.328833,0.337417

=== Event 480 | 2025-05-11 | Truist Championship ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"McIlroy, Rory",10091,2.91,4.08,1.405725,2.279792,2.769833
1,2,"Thomas, Justin",14139,3.82,5.35,1.708975,1.508500,2.001500
2,3,"Straka, Sepp",17511,3.77,5.28,1.633650,1.563042,1.144583
3,4,"Schauffele, Xander",19895,2.67,3.73,1.166725,0.327750,1.418167
4,5,"Morikawa, Collin",22085,1.77,2.47,1.021600,1.185208,0.664000
5,6,"Cantlay, Patrick",15466,1.93,2.71,1.099725,0.937917,0.493667
6,7,"Matsuyama, Hideki",13562,1.98,2.78,1.227350,0.791458,1.005167
7,8,"Henley, Russell",14578,1.93,2.71,1.097200,0.981333,0.497000
8,9,"Lowry, Shane",13900,2.00,2.80,1.419300,1.607875,1.084833
9,10,"Fleetwood, Tommy",12294,1.77,2.47,1.160975,1.196250,0.743667

=== Event 33 | 2025-05-18 | PGA Championship ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,2.32,6.73,2.569950,3.198625,3.945000
1,2,"DeChambeau, Bryson",19841,1.54,4.47,2.060700,2.509292,2.339500
2,3,"McIlroy, Rory",10091,1.13,3.29,1.461725,2.069167,2.233500
3,4,"Rahm, Jon",19195,0.98,2.85,1.286225,1.158917,2.236417
4,5,"Thomas, Justin",14139,1.05,3.05,1.548875,1.324250,1.595750
5,6,"Schauffele, Xander",19895,0.98,2.84,1.249800,0.732917,0.940500
6,7,"Niemann, Joaquin",18079,0.91,2.65,0.951350,0.690500,0.920083
7,8,"Cantlay, Patrick",15466,0.98,2.84,0.990900,0.837000,0.762417
8,9,"Fleetwood, Tommy",12294,0.95,2.75,1.272300,1.054875,1.607167
9,10,"Berger, Daniel",17606,1.22,3.54,1.397450,1.287333,1.440500

=== Event 21 | 2025-05-25 | Charles Schwab Challenge ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,3.08,7.33,2.650450,3.203625,3.905083
1,2,"Berger, Daniel",17606,1.32,3.13,1.320575,1.292958,1.240917
2,3,"Fleetwood, Tommy",12294,1.23,2.92,1.327800,1.127750,1.483917
3,4,"Spieth, Jordan",14636,1.13,2.69,0.980850,1.067083,1.316083
4,5,"McNealy, Maverick",18634,1.03,2.44,0.585525,0.691292,0.074250
5,6,"Gotterup, Chris",27774,1.69,4.01,0.360200,0.191417,0.997000
6,7,"Spaun, J.J.",17536,1.12,2.65,0.820100,0.701917,1.400583
7,8,"Matsuyama, Hideki",13562,0.94,2.22,0.771100,0.701833,1.043333
8,9,"Rai, Aaron",18554,0.95,2.25,0.846675,0.714667,0.657583
9,10,"Smalley, Alex",18474,1.25,2.97,0.986500,0.766542,0.695083

=== Event 23 | 2025-06-01 | Memorial Tournament ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,4.72,7.10,2.784375,3.480458,3.693417
1,2,"Straka, Sepp",17511,3.44,5.17,1.327675,1.515333,2.095750
2,3,"Griffin, Ben",24968,3.46,5.20,1.356675,1.662667,2.834000
3,4,"Conners, Corey",17576,2.55,3.83,1.370325,1.235042,1.531833
4,5,"Fleetwood, Tommy",12294,2.44,3.67,1.303425,1.163833,1.584000
5,6,"Lowry, Shane",13900,2.66,3.99,1.384300,1.419583,1.595750
6,7,"Morikawa, Collin",22085,1.83,2.75,0.939825,0.744333,0.615167
7,8,"Schauffele, Xander",19895,1.80,2.71,1.155200,1.095208,1.615167
8,9,"Cantlay, Patrick",15466,1.87,2.81,1.164800,1.015667,1.095750
9,10,"Bradley, Keegan",13872,2.36,3.55,0.902900,1.066125,1.365167

=== Event 32 | 2025-06-08 | RBC Canadian Open ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"McIlroy, Rory",10091,1.34,2.94,1.300425,1.432500,0.302000
1,2,"Conners, Corey",17576,1.64,3.60,1.591050,1.018208,1.292750
2,3,"Pendrith, Taylor",17780,1.82,3.99,0.345100,0.504958,1.709417
3,4,"Roy, Kevin",18424,2.66,5.85,0.688325,0.202000,1.274583
4,5,"Clanton, Luke",32330,1.34,2.94,1.255111,0.791625,0.547250
5,6,"Taylor, Nick",13126,1.36,3.00,0.528450,0.445750,1.332667
6,7,"Burns, Sam",19483,1.13,2.48,0.552300,1.254083,1.292750
7,8,"Aberg, Ludvig",23950,0.87,1.90,0.416775,0.234750,0.332667
8,9,"Lowry, Shane",13900,0.96,2.10,1.186825,1.168208,1.416000
9,10,"Gotterup, Chris",27774,1.20,2.63,0.344400,0.338083,0.828417

=== Event 26 | 2025-06-15 | U.S. Open ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,2.83,7.85,2.980350,3.390333,2.835667
1,2,"DeChambeau, Bryson",19841,1.48,4.10,2.136900,2.596917,1.563500
2,3,"McIlroy, Rory",10091,1.57,4.35,1.547200,1.375500,-0.044333
3,4,"Rahm, Jon",19195,1.26,3.48,1.270925,1.098917,2.149250
4,5,"Hovland, Viktor",18841,1.72,4.77,0.745175,1.230875,1.710250
5,6,"Koepka, Brooks",16243,1.63,4.51,1.094175,0.335417,0.224250
6,7,"Morikawa, Collin",22085,1.18,3.27,1.026650,0.770458,0.876917
7,8,"Burns, Sam",19483,1.75,4.85,1.160850,2.262542,3.225667
8,9,"Griffin, Ben",24968,1.64,4.55,1.299800,1.720042,3.002333
9,10,"Fleetwood, Tommy",12294,1.24,3.43,1.339425,1.375792,1.072500

=== Event 34 | 2025-06-22 | Travelers Championship ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,4.60,6.47,2.963450,3.346417,2.787750
1,2,"McIlroy, Rory",10091,2.60,3.65,1.682875,1.423583,0.516417
2,3,"Bradley, Keegan",13872,2.98,4.19,1.305675,1.514417,1.955083
3,4,"Young, Cameron",26651,3.15,4.43,0.501025,1.164167,1.879833
4,5,"Cantlay, Patrick",15466,2.38,3.34,1.027225,0.776792,1.059917
5,6,"Morikawa, Collin",22085,1.97,2.77,1.067775,0.531125,0.955083
6,7,"Henley, Russell",14578,2.44,3.43,1.302800,1.171625,2.144250
7,8,"Thomas, Justin",14139,2.12,2.98,1.247725,1.155708,0.309917
8,9,"Griffin, Ben",24968,2.51,3.53,1.180475,1.891417,1.954417
9,10,"Rai, Aaron",18554,2.51,3.53,0.902000,0.596833,0.503167

=== Event 524 | 2025-06-29 | Rocket Classic ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Hall, Harry",27194,1.24,3.41,1.148000,1.663833,1.834833
1,2,"Smalley, Alex",18474,1.45,3.98,0.740575,0.202375,0.475750
2,3,"Cantlay, Patrick",15466,1.01,2.76,0.989625,1.064833,1.153333
3,4,"Griffin, Ben",24968,1.10,3.01,1.454025,2.288833,1.743667
4,5,"Morikawa, Collin",22085,0.86,2.36,1.205175,0.929417,1.243667
5,6,"Greyserman, Max",23465,1.19,3.26,0.388250,1.288833,1.660333
6,7,"Bradley, Keegan",13872,0.89,2.44,1.198125,1.387750,1.410333
7,8,"Knapp, Jake",19396,1.28,3.51,0.906775,0.366625,1.306083
8,9,"Fitzpatrick, Matt",17646,1.03,2.83,0.289375,0.929417,1.577000
9,10,"Kim, Si Woo",14609,0.93,2.54,0.737175,0.697792,-0.037583

=== Event 30 | 2025-07-06 | John Deere Classic ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Griffin, Ben",24968,1.95,4.90,1.576250,2.148708,1.141583
1,2,"Lawrence, Thriston",18105,2.46,6.20,-0.394100,-0.149333,1.955167
2,3,"Cauley, Bud",14502,1.33,3.35,0.988700,0.383625,-0.005417
3,4,"Clanton, Luke",32330,1.27,3.21,0.949200,0.333750,-0.075083
4,5,"Champ, Cameron",23542,1.51,3.81,0.778175,1.649042,2.013500
5,6,"Kim, Si Woo",14609,1.11,2.81,0.692325,0.646542,0.074000
6,7,"Ventura, Kris",15651,1.77,4.46,0.306775,0.188125,1.082833
7,8,"Gotterup, Chris",27774,1.11,2.79,0.779125,1.347167,1.714333
8,9,"Knapp, Jake",19396,1.09,2.75,0.927625,0.744125,1.378833
9,10,"Smalley, Alex",18474,1.09,2.75,0.824125,0.254500,-0.111667

=== Event 541 | 2025-07-13 | Genesis Scottish Open ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,3.47,8.39,3.027750,3.069125,2.444833
1,2,"McIlroy, Rory",10091,2.09,5.06,1.764925,1.620792,1.677500
2,3,"Hojgaard, Nicolai",23602,2.60,6.28,0.435775,0.204042,1.285667
3,4,"Fitzpatrick, Matt",17646,1.83,4.41,0.657375,1.573375,1.936500
4,5,"Conners, Corey",17576,1.70,4.11,1.309750,0.942958,0.749500
5,6,"Hall, Harry",27194,1.90,4.60,1.424350,1.774708,1.828167
6,7,"Fleetwood, Tommy",12294,1.30,3.14,1.314350,1.691833,1.354500
7,8,"Clark, Wyndham",23604,1.84,4.46,0.226225,0.202792,1.196167
8,9,"Morikawa, Collin",22085,1.01,2.44,0.876275,0.636625,0.444000
9,10,"Hovland, Viktor",18841,1.14,2.76,0.968375,1.182667,1.978917

=== Event 100 | 2025-07-20 | The Open Championship ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,3.25,8.62,3.282825,2.957708,3.079750
1,2,"McIlroy, Rory",10091,2.74,7.25,1.909575,1.559375,3.163083
2,3,"Rahm, Jon",19195,1.22,3.24,1.401025,1.660125,2.302667
3,4,"Hatton, Tyrrell",14796,1.28,3.39,1.094800,1.294333,1.886000
4,5,"Fitzpatrick, Matt",17646,1.37,3.62,1.264225,1.683333,2.828250
5,6,"DeChambeau, Bryson",19841,0.97,2.58,2.063650,2.330792,1.649917
6,7,"Gotterup, Chris",27774,1.52,4.03,1.442575,1.893083,2.580000
7,8,"Griffin, Ben",24968,1.35,3.58,1.554775,2.014750,1.105250
8,9,"Spieth, Jordan",14636,1.13,2.99,1.275425,1.255583,1.195083
9,10,"Straka, Sepp",17511,1.08,2.85,1.373250,1.400708,0.877167

=== Event 525 | 2025-07-27 | 3M Open ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Gotterup, Chris",27774,3.82,8.58,1.773250,2.362917,3.011500
1,2,"Kitayama, Kurt",21891,2.57,5.77,0.754575,1.180417,1.811917
2,3,"Burns, Sam",19483,1.62,3.65,1.506400,1.448750,0.684333
3,4,"Knapp, Jake",19396,1.97,4.42,0.993350,1.638583,1.971083
4,5,"Clark, Wyndham",23604,1.38,3.10,0.419750,1.108792,1.866750
5,6,"Hodges, Lee",25157,1.56,3.52,0.495475,0.455875,0.489750
6,7,"Roy, Kevin",18424,1.37,3.08,0.746800,1.434208,1.593833
7,8,"McNealy, Maverick",18634,0.87,1.96,0.741575,0.816167,0.926667
8,9,"Grillo, Emiliano",12808,1.09,2.46,0.924600,1.487417,1.202167
9,10,"Stevens, Sam",25569,1.17,2.64,0.816200,0.739042,1.107000

=== Event 13 | 2025-08-03 | Wyndham Championship ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Hall, Harry",27194,3.02,5.13,1.594375,1.599625,1.364417
1,2,"Fitzpatrick, Matt",17646,1.90,3.22,1.486900,2.220708,2.864417
2,3,"Griffin, Ben",24968,1.83,3.10,1.541500,1.670375,1.386333
3,4,"Hojgaard, Nicolai",23602,2.09,3.56,0.886025,1.242375,1.781083
4,5,"Kitayama, Kurt",21891,1.89,3.21,0.964575,1.383792,2.007500
5,6,"Matsuyama, Hideki",13562,1.52,2.59,0.889800,0.950833,2.113917
6,7,"MacIntyre, Robert",23323,1.43,2.43,1.081350,1.273417,1.083667
7,8,"Glover, Lucas",7399,1.45,2.46,0.359825,0.825583,1.416000
8,9,"Bezuidenhout, Christiaan",18103,1.66,2.81,0.745450,0.847208,1.270083
9,10,"Wallace, Matt",20706,1.73,2.93,1.024300,1.047167,1.186750

=== Event 27 | 2025-08-10 | FedEx St. Jude Championship ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,6.42,8.28,3.234625,3.071958,3.356167
1,2,"Henley, Russell",14578,3.01,3.88,1.325825,1.152375,1.887917
2,3,"Griffin, Ben",24968,2.95,3.81,1.812100,1.610750,1.477833
3,4,"Hall, Harry",27194,3.47,4.48,1.568975,1.609417,1.390667
4,5,"Fleetwood, Tommy",12294,2.42,3.13,1.762450,1.861208,1.689500
5,6,"Fitzpatrick, Matt",17646,2.42,3.12,1.478325,1.996917,2.057333
6,7,"Aberg, Ludvig",23950,2.46,3.17,0.733675,1.322833,1.606167
7,8,"Gotterup, Chris",27774,2.59,3.33,1.513475,1.673417,1.459250
8,9,"English, Harris",14577,2.48,3.19,1.183275,1.321958,1.939500
9,10,"Rose, Justin",6093,2.95,3.81,0.499425,0.115875,2.218500

=== Event 28 | 2025-08-17 | BMW Championship ===

,pred_rank,player_name,dg_id,p_win_norm_pct,p_win_raw_pct,sg_total_L40,sg_total_L24,sg_total_L12
0,1,"Scheffler, Scottie",18417,8.10,8.44,3.397150,3.089167,3.733500
1,2,"McIlroy, Rory",10091,5.74,5.98,1.895850,1.594833,2.673250
2,3,"Fleetwood, Tommy",12294,5.20,5.42,1.809450,1.877333,2.400167
3,4,"Fitzpatrick, Matt",17646,4.81,5.01,1.568675,1.895042,0.961833
4,5,"Young, Cameron",26651,3.94,4.11,1.516500,1.519083,2.672167
5,6,"Gotterup, Chris",27774,4.17,4.35,1.388525,1.305208,0.030417
6,7,"Thomas, Justin",14139,3.00,3.13,0.982725,0.794000,0.733500
7,8,"Aberg, Ludvig",23950,2.64,2.75,0.894050,1.614750,2.066833
8,9,"Hall, Harry",27194,3.37,3.51,1.714475,1.853375,1.545167
9,10,"MacIntyre, Robert",23323,3.17,3.30,1.362925,1.437458,1.711833

Events scored: 31

,event_id,event_date,calibrated,top_pick,top_pick_pwin,top_pick_won,winner_name,winner_rank,winner_pwin,brier,auc,n_field
0,6,2025-01-12,1,"Henley, Russell",0.038401,0,"Taylor, Nick",111,0.001445,0.013240,0.106667,143
1,2,2025-01-19,1,"Meissner, Mac",0.084884,0,"Straka, Sepp",18,0.012706,0.013929,0.814286,156
2,4,2025-01-25,1,"Griffin, Ben",0.036481,0,"English, Harris",13,0.015676,0.013918,0.927536,154
3,5,2025-02-02,1,"Pendrith, Taylor",0.075702,0,"McIlroy, Rory",2,0.036821,0.012171,0.961039,80
4,3,2025-02-09,1,"Thomas, Justin",0.034254,0,"Detry, Thomas",10,0.025017,0.012493,0.947368,132
5,7,2025-02-16,1,"Scheffler, Scottie",0.040417,0,"Aberg, Ludvig",19,0.014512,0.018471,0.584906,72
6,540,2025-02-23,1,"Bhatia, Akshay",0.033574,0,"Campbell, Brian",33,0.011532,0.012829,0.750000,132
7,10,2025-03-02,1,"Lowry, Shane",0.026670,0,"Highsmith, Joe",62,0.005410,0.014706,0.432836,144
8,9,2025-03-09,1,"Aberg, Ludvig",0.048776,0,"Henley, Russell",4,0.050026,0.018120,1.000000,72
9,11,2025-03-16,1,"Henley, Russell",0.049617,0,"McIlroy, Rory",11,0.009578,0.013774,0.605634,144
10,475,2025-03-23,1,"Conners, Corey",0.062956,0,"Hovland, Viktor",70,0.003318,0.012883,0.402597,152
11,20,2025-03-30,1,"Scheffler, Scottie",0.014689,0,"Lee, Min Woo",3,0.013914,0.014142,0.985294,153
12,41,2025-04-06,1,"Cantlay, Patrick",0.014493,0,"Harman, Brian",26,0.009062,0.014937,0.800000,144
13,14,2025-04-13,1,"Scheffler, Scottie",0.028415,0,"McIlroy, Rory",2,0.031037,0.017863,1.000000,95
14,12,2025-04-20,1,"Scheffler, Scottie",0.029292,0,"Thomas, Justin",3,0.025068,0.013411,0.957746,72
15,19,2025-05-04,1,"Scheffler, Scottie",0.027934,1,"Scheffler, Scottie",1,0.027934,0.013549,1.000000,156
16,480,2025-05-11,1,"McIlroy, Rory",0.029111,0,"Straka, Sepp",3,0.037675,0.013642,0.985294,72
17,33,2025-05-18,1,"Scheffler, Scottie",0.023210,1,"Scheffler, Scottie",1,0.023210,0.012947,1.000000,156
18,21,2025-05-25,1,"Scheffler, Scottie",0.030845,0,"Griffin, Ben",15,0.010661,0.012622,0.870130,134
19,23,2025-06-01,1,"Scheffler, Scottie",0.047182,1,"Scheffler, Scottie",1,0.047182,0.016167,1.000000,72
20,32,2025-06-08,1,"McIlroy, Rory",0.013392,0,"Fox, Ryan",18,0.010686,0.014468,0.805970,155
21,26,2025-06-15,1,"Scheffler, Scottie",0.028310,0,"Spaun, J.J.",28,0.009770,0.014941,0.753846,156
22,34,2025-06-22,1,"Scheffler, Scottie",0.046040,0,"Bradley, Keegan",3,0.029827,0.014301,0.969697,71
23,524,2025-06-29,1,"Hall, Harry",0.012439,0,"Potgieter, Aldrich",47,0.006608,0.011524,0.552941,156
24,30,2025-07-06,1,"Griffin, Ben",0.019453,0,"Campbell, Brian",111,0.004716,0.015546,0.277778,156
25,541,2025-07-13,1,"Scheffler, Scottie",0.034692,0,"Gotterup, Chris",28,0.008762,0.012534,0.717949,155
26,100,2025-07-20,1,"Scheffler, Scottie",0.032529,1,"Scheffler, Scottie",1,0.032529,0.013444,1.000000,156
27,525,2025-07-27,1,"Gotterup, Chris",0.038164,0,"Kitayama, Kurt",2,0.025675,0.012567,0.986667,156
28,13,2025-08-03,1,"Hall, Harry",0.030225,0,"Young, Cameron",22,0.011751,0.013120,0.743243,156
29,27,2025-08-10,1,"Scheffler, Scottie",0.064227,0,"Rose, Justin",10,0.029530,0.013946,0.955882,69
30,28,2025-08-17,1,"Scheffler, Scottie",0.080990,1,"Scheffler, Scottie",1,0.080990,0.018111,1.000000,49

,year,event_id,event_start_date,dg_id,player_name,finish_num,is_winner,p_win,was_calibrated,sg_total_L40,sg_total_L24,sg_total_L12,pred_rank,p_win_raw,p_win_norm
0,2025,6,2025-01-12,14578,"Henley, Russell",10.0,0,0.054503,1,1.302175,1.322500,1.076083,1,0.054503,0.038401
1,2025,6,2025-01-12,25569,"Stevens, Sam",59.0,0,0.045750,1,0.463625,0.631708,-0.054167,2,0.045750,0.032234
2,2025,6,2025-01-12,18634,"McNealy, Maverick",45.0,0,0.041980,1,1.117150,0.975458,1.002417,3,0.041980,0.029577
3,2025,6,2025-01-12,27164,"Phillips, Chandler",NaN,0,0.039024,1,0.062000,0.265250,-0.800000,4,0.039024,0.027495
4,2025,6,2025-01-12,32330,"Clanton, Luke",NaN,0,0.037284,1,1.660250,1.660250,1.809500,5,0.037284,0.026268
5,2025,6,2025-01-12,23504,"Hoey, Rico",59.0,0,0.036378,1,0.573400,0.778958,0.355167,6,0.036378,0.025630
6,2025,6,2025-01-12,11276,"Horschel, Billy",NaN,0,0.034597,1,1.160025,1.018750,0.587833,7,0.034597,0.024376
7,2025,6,2025-01-12,13562,"Matsuyama, Hideki",16.0,0,0.033935,1,1.580925,1.627917,1.633583,8,0.033935,0.023910
8,2025,6,2025-01-12,10873,"Skinns, David",NaN,0,0.032796,1,0.267350,0.278083,-0.009583,9,0.032796,0.023106
9,2025,6,2025-01-12,25094,"Fishburn, Patrick",6.0,0,0.029673,1,0.037794,0.636792,1.677750,10,0.029673,0.020906
10,2025,6,2025-01-12,23475,"Novak, Andrew",NaN,0,0.027631,1,0.737125,0.735833,0.055083,11,0.027631,0.019467
11,2025,6,2025-01-12,24550,"Ghim, Doug",72.0,0,0.026779,1,0.275750,0.237917,0.523417,12,0.026779,0.018868
12,2025,6,2025-01-12,6169,"Kuchar, Matt",21.0,0,0.026031,1,0.644925,1.297417,1.934750,13,0.026031,0.018341
13,2025,6,2025-01-12,19870,"McCarthy, Denny",16.0,0,0.025189,1,0.555325,0.663792,1.260583,14,0.025189,0.017747
14,2025,6,2025-01-12,14509,"Dahmen, Joel",NaN,0,0.023907,1,0.105850,0.136542,-0.773833,15,0.023907,0.016844

             p_bin     n  avg_pred_pwin  observed_win_rate
0  (-0.001, 0.002]   343       0.001477           0.002915
1   (0.002, 0.005]  1049       0.003698           0.001907
2    (0.005, 0.01]  1549       0.006885           0.003873
3     (0.01, 0.02]   725       0.013587           0.011034
4     (0.02, 0.04]   178       0.026501           0.061798
5     (0.04, 0.07]    23       0.049582           0.086957
6      (0.07, 0.1]     3       0.080525           0.333333
7       (0.1, 0.2]     0            NaN                NaN
8       (0.2, 1.0]     0            NaN                NaN

     dg_id         player_name  starts  wins  avg_pwin  max_pwin
226  18417  Scheffler, Scottie      18     5  0.056940  0.086220
63   10091       McIlroy, Rory      14     3  0.039042  0.072526
204  17511        Straka, Sepp      19     2  0.028281  0.052785
235  18628     Campbell, Brian      22     2  0.010768  0.025895
139  14578     Henley, Russell      16     1  0.035477  0.069113
127  14139      Thomas, Justin      18     1  0.028365  0.053478
361  24968        Griffin, Ben      26     1  0.026958  0.052003
205  17536         Spaun, J.J.      22     1  0.022524  0.036852
417  27774     Gotterup, Chris      21     1  0.022349  0.085797
119  13872     Bradley, Keegan      19     1  0.022344  0.041906
241  18841     Hovland, Viktor      16     1  0.021092  0.062340
340  23950       Aberg, Ludvig      18     1  0.019636  0.043013
292  21891      Kitayama, Kurt      20     1  0.018747  0.057721
104  13126        Taylor, Nick      20     1  0.018682  0.036606
83   11889           Fox, Ryan      18     1  0.017840  0.035091
22    6093        Rose, Justin      17     1  0.016536  0.038068
138  14577     English, Harris      20     1  0.016393  0.031930
191  16841        Lee, Min Woo      17     1  0.015317  0.040442
396  26651      Young, Cameron      22     1  0.013966  0.044319
56    8825       Harman, Brian      21     1  0.012660  0.029832
129  14181       Detry, Thomas      22     1  0.010966  0.028900
422  27900  Potgieter, Aldrich      16     1  0.010764  0.020042
437  28469      Highsmith, Joe      24     1  0.010524  0.023251
256  19841  DeChambeau, Bryson       4     0  0.038385  0.044659
243  19195           Rahm, Jon       4     0  0.030365  0.034843
188  16652   Langasque, Romain       2     0  0.029797  0.039613
327  23542      Champ, Cameron       5     0  0.029290  0.039905
305  22322       McKibbin, Tom       2     0  0.028691  0.036051
87   12294    Fleetwood, Tommy      18     0  0.028108  0.054206
148  14796     Hatton, Tyrrell       4     0  0.027964  0.033889
418  27780        Crowe, Trace       2     0  0.027860  0.029602
164  15466    Cantlay, Patrick      17     0  0.026831  0.037954
26    6516      Bland, Richard       2     0  0.026289  0.042725
408  27194         Hall, Harry      21     0  0.025149  0.051346
485  32330       Clanton, Luke      12     0  0.025127  0.040319
221  18079    Niemann, Joaquin       4     0  0.024146  0.030152
115  13562   Matsuyama, Hideki      20     0  0.023806  0.042396
479  32055       Shipley, Neal       2     0  0.023336  0.030667
132  14424     Burmester, Dean       2     0  0.023128  0.025902
300  22085    Morikawa, Collin      16     0  0.023126  0.042160
208  17550    Van Rooyen, Erik       2     0  0.022884  0.024215
176  16243      Koepka, Brooks       4     0  0.022861  0.045098
210  17576      Conners, Corey      19     0  0.022320  0.073099
149  14838       Reed, Patrick       4     0  0.022163  0.024456
216  17780    Pendrith, Taylor      22     0  0.021947  0.063213
250  19483          Burns, Sam      22     0  0.021894  0.048511
227  18424          Roy, Kevin      16     0  0.021290  0.058481
66   10419         Noren, Alex       9     0  0.021212  0.030079
281  21407  Reitan, Kristoffer       2     0  0.021192  0.029312
262  19895  Schauffele, Xander      14     0  0.021174  0.037340

In [22]:
# ============================================================
# WIN-ONLY MODEL (P(win)) — 2025 walk-forward, NO FUTURE INFO
# ============================================================
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import brier_score_loss, roc_auc_score

# -----------------------------
# Feature set (SG-only)
# -----------------------------
WIN_FEATURES = ["sg_total_L40", "sg_total_L24", "sg_total_L12"]
USE_CALIBRATION = True
RANDOM_SEED = 42

def safe_auc(y_true, y_prob):
    if len(np.unique(y_true)) < 2:
        return np.nan
    return roc_auc_score(y_true, y_prob)

def build_base_model():
    return HistGradientBoostingClassifier(
        loss="log_loss",
        learning_rate=0.05,
        max_depth=6,
        max_iter=400,
        min_samples_leaf=40,
        l2_regularization=0.0,
        random_state=RANDOM_SEED,
    )

def fit_model_with_year_sigmoid_calibration(train_df, feat_cols, label_col="y_win"):
    tr = train_df.dropna(subset=feat_cols + [label_col, "year"]).copy()
    Xtr = tr[feat_cols]
    ytr = tr[label_col].astype(int).values
    years = tr["year"].astype(int).values
    uniq_years = np.unique(years)

    base = build_base_model()

    # If not enough distinct years, skip calibration
    if (not USE_CALIBRATION) or (len(uniq_years) < 3):
        base.fit(Xtr, ytr)
        return base, None

    # LOYO OOF probs
    oof = np.full(len(tr), np.nan, dtype=float)
    for y in uniq_years:
        idx_te = np.where(years == y)[0]
        idx_tr = np.where(years != y)[0]
        if len(np.unique(ytr[idx_tr])) < 2:
            continue
        m = build_base_model()
        m.fit(Xtr.iloc[idx_tr], ytr[idx_tr])
        oof[idx_te] = m.predict_proba(Xtr.iloc[idx_te])[:, 1]

    ok = np.isfinite(oof)
    if ok.mean() < 0.8 or len(np.unique(ytr[ok])) < 2:
        base.fit(Xtr, ytr)
        return base, None

    # sigmoid calibrator on logit(oof)
    eps = 1e-6
    p = np.clip(oof[ok], eps, 1 - eps)
    logit_p = np.log(p / (1 - p)).reshape(-1, 1)

    cal = LogisticRegression(solver="lbfgs")
    cal.fit(logit_p, ytr[ok])

    base.fit(Xtr, ytr)
    return base, cal

def predict_proba_calibrated(base_model, calibrator, X):
    p = base_model.predict_proba(X)[:, 1]
    if calibrator is None:
        return p
    eps = 1e-6
    p2 = np.clip(p, eps, 1 - eps)
    logit_p = np.log(p2 / (1 - p2)).reshape(-1, 1)
    return calibrator.predict_proba(logit_p)[:, 1]

# ============================================================
# Names: schedule (optional) + event_skill fallback
# ============================================================
SCHED_2025 = None  # <-- set this if you want, e.g. "/Users/joshmacbook/python_projects/OAD/Data/in Use/OAD_2025.xlsx"

event_name_map = {}
if SCHED_2025 is not None:
    sched = pd.read_excel(SCHED_2025)
    sched["event_id"] = pd.to_numeric(sched.get("event_id"), errors="coerce").astype("Int64")
    if "event_name" in sched.columns:
        event_name_map = (
            sched.dropna(subset=["event_id"])
                 .drop_duplicates(subset=["event_id"])
                 .set_index("event_id")["event_name"]
                 .to_dict()
        )

# ============================================================
# event_skill + odds blend (stats-first)
# ============================================================
EVENT_SKILL_PATH = "/Data/in Use/event_skill.xlsx"
event_skill_df = pd.read_excel(EVENT_SKILL_PATH)
event_skill_df["year"] = pd.to_numeric(event_skill_df["year"], errors="coerce").astype("Int64")
event_skill_df["event_id"] = pd.to_numeric(event_skill_df["event_id"], errors="coerce").astype("Int64")
need_cols = [c for c in ["year","event_id","event_name","avg_skill","x_score"] if c in event_skill_df.columns]
event_skill_df = event_skill_df[need_cols].copy()

# if schedule wasn't provided, use event_skill names
if not event_name_map and "event_name" in event_skill_df.columns:
    event_name_map = (
        event_skill_df.dropna(subset=["event_id"])
                      .drop_duplicates(subset=["event_id"])
                      .set_index("event_id")["event_name"]
                      .to_dict()
    )

def _logit(p, eps=1e-6):
    p = np.clip(p, eps, 1 - eps)
    return np.log(p / (1 - p))

def _sigmoid(z):
    return 1 / (1 + np.exp(-z))

def blend_stats_odds_with_field_strength(board, year, ev_id, event_skill_df):
    """
    Requires:
      - p_win_raw  (stats model prob, not normalized)
      - close_odds (decimal odds)
    Adds:
      - p_win_blend_raw
      - p_win_blend_norm
      - blend_weight
      - x_score
    """
    b = board.copy()

    row = event_skill_df[(event_skill_df["year"] == year) & (event_skill_df["event_id"] == ev_id)]
    if row.empty or ("x_score" not in row.columns):
        x = np.nan
        w_event = 0.20
    else:
        x = float(row["x_score"].iloc[0])
        # map ~0.70..1.00 -> ~0.10..0.35, clamp
        w_event = 0.10 + 0.30 * ((x - 0.70) / (1.00 - 0.70))
        w_event = float(np.clip(w_event, 0.10, 0.35))

    # odds implied within-event
    p_odds_raw = 1.0 / pd.to_numeric(b["close_odds"], errors="coerce")
    p_odds_raw = p_odds_raw.fillna(p_odds_raw.median())
    p_odds = (p_odds_raw / (p_odds_raw.sum() + 1e-12)).values

    # stats within-event
    p_stats_raw = pd.to_numeric(b["p_win_raw"], errors="coerce").fillna(0.0)
    p_stats = (p_stats_raw / (p_stats_raw.sum() + 1e-12)).values

    z = _logit(p_stats) + w_event * _logit(p_odds)
    p_blend = _sigmoid(z)

    b["p_win_blend_raw"] = p_blend
    b["p_win_blend_norm"] = b["p_win_blend_raw"] / (b["p_win_blend_raw"].sum() + 1e-12)
    b["blend_weight"] = w_event
    b["x_score"] = x
    return b

# ============================================================
# 0) Prepare X and event order for 2025
# ============================================================
BACKTEST_YEAR = 2025
df_all = X.copy()

df_all["event_start_date"] = pd.to_datetime(df_all["event_start_date"], errors="coerce")

bt_events = (
    df_all[df_all["year"] == BACKTEST_YEAR][["event_id","event_start_date"]]
    .dropna()
    .drop_duplicates()
    .sort_values("event_start_date")
    .reset_index(drop=True)
)
print("2025 events found:", len(bt_events))

# ============================================================
# 1) Walk-forward
# ============================================================
event_boards = []
event_summ   = []
event_top10  = []

for _, ev in bt_events.iterrows():
    ev_id = int(ev["event_id"])
    ev_date = pd.to_datetime(ev["event_start_date"])
    ev_name = event_name_map.get(ev_id, "UNKNOWN_EVENT")
    print(f"\n=== Event {ev_id} | {ev_date.date()} | {ev_name} ===")

    train_df = df_all[
        (df_all["year"] < BACKTEST_YEAR) |
        ((df_all["year"] == BACKTEST_YEAR) & (df_all["event_start_date"] < ev_date))
    ].copy()

    test_df = df_all[(df_all["year"] == BACKTEST_YEAR) & (df_all["event_id"] == ev_id)].copy()
    if test_df.empty or train_df.empty:
        continue

    feat_cols = [c for c in WIN_FEATURES if c in train_df.columns]
    missing = set(WIN_FEATURES) - set(feat_cols)
    if missing:
        print("Missing features:", sorted(missing))
        continue

    base_model, calibrator = fit_model_with_year_sigmoid_calibration(train_df, feat_cols, label_col="y_win")
    p = predict_proba_calibrated(base_model, calibrator, test_df[feat_cols])
    was_cal = int(calibrator is not None)

    test_df = test_df.copy()
    test_df["p_win"] = p
    test_df["was_calibrated"] = was_cal
    test_df["is_winner"] = (pd.to_numeric(test_df["finish_num"], errors="coerce") == 1).astype(int)

    # Build board with features included
    base_cols = ["year","event_id","event_start_date","dg_id","player_name","finish_num","is_winner","p_win","was_calibrated"]
    board_cols = base_cols + feat_cols + (["close_odds"] if "close_odds" in test_df.columns else [])
    board = test_df[board_cols].copy()

    # Normalize stats-only win share
    board["p_win_raw"] = board["p_win"]
    board["p_win_norm"] = board["p_win_raw"] / (board["p_win_raw"].sum() + 1e-12)

    # Blend with odds if available
    if "close_odds" in board.columns:
        board = blend_stats_odds_with_field_strength(board, BACKTEST_YEAR, ev_id, event_skill_df)
        # rank by blended (you can switch to p_win_norm if you want stats-only ranking)
        board = board.sort_values("p_win_blend_norm", ascending=False).reset_index(drop=True)
    else:
        board = board.sort_values("p_win_norm", ascending=False).reset_index(drop=True)

    board["pred_rank"] = np.arange(1, len(board) + 1)
    board["event_name"] = ev_name

    # Append AFTER we’ve added p_win_* columns (this was one of your big issues)
    event_boards.append(board)

    # --- Top 10 display (robust selection) ---
    top10 = board.head(10).copy()

    show_cols = ["pred_rank","player_name","dg_id"]
    # show both stats-only and blended if present
    if "p_win_norm" in top10.columns:        show_cols += ["p_win_norm"]
    if "p_win_blend_norm" in top10.columns:  show_cols += ["p_win_blend_norm"]
    for c in ["sg_total_L40","sg_total_L24","sg_total_L12"]:
        if c in top10.columns:
            show_cols.append(c)

    if "p_win_norm" in top10.columns:
        top10["p_win_norm_pct"] = (100 * top10["p_win_norm"]).round(2)
    if "p_win_blend_norm" in top10.columns:
        top10["p_win_blend_norm_pct"] = (100 * top10["p_win_blend_norm"]).round(2)

    print(f"Top-10 ({ev_name})")
    display(top10[show_cols + [c for c in ["p_win_norm_pct","p_win_blend_norm_pct"] if c in top10.columns]])

    # store top10 rows for later concat
    top10_out = top10.copy()
    top10_out["event_date"] = ev_date
    event_top10.append(top10_out)

    # --- Event summary (use stats-only or blended consistently) ---
    winner_rows = board[board["is_winner"] == 1]
    winner_rank = int(winner_rows["pred_rank"].iloc[0]) if not winner_rows.empty else np.nan
    winner_name = winner_rows["player_name"].iloc[0] if not winner_rows.empty else None

    # score using stats-only normalized (stable baseline)
    eval_board = board.dropna(subset=["finish_num"]).copy()
    y_true = eval_board["is_winner"].values
    y_prob = eval_board["p_win_norm"].values
    brier = brier_score_loss(y_true, y_prob)
    auc = safe_auc(y_true, y_prob)

    top_pick = board.iloc[0]
    event_summ.append({
        "event_id": ev_id,
        "event_date": ev_date,
        "event_name": ev_name,
        "calibrated": was_cal,
        "top_pick": top_pick["player_name"],
        "top_pick_pwin": float(top_pick["p_win_norm"]),
        "top_pick_won": int(top_pick["is_winner"]),
        "winner_name": winner_name,
        "winner_rank": winner_rank,
        "brier": brier,
        "auc": auc,
        "n_field": len(board),
    })

boards_2025 = pd.concat(event_boards, ignore_index=True) if event_boards else pd.DataFrame()
summ_2025   = pd.DataFrame(event_summ).sort_values("event_date") if event_summ else pd.DataFrame()
top10_all_2025 = pd.concat(event_top10, ignore_index=True) if event_top10 else pd.DataFrame()

print("Events scored:", summ_2025["event_id"].nunique() if not summ_2025.empty else 0)
display(summ_2025.head(40))

2025 events found: 31

=== Event 6 | 2025-01-12 | Sony Open in Hawaii ===
Top-10 (Sony Open in Hawaii)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Henley, Russell",14578,0.038401,0.064807,1.302175,1.322500,1.076083,3.84,6.48
1,2,"Matsuyama, Hideki",13562,0.023910,0.051539,1.580925,1.627917,1.633583,2.39,5.15
2,3,"McNealy, Maverick",18634,0.029577,0.046174,1.117150,0.975458,1.002417,2.96,4.62
3,4,"Clanton, Luke",32330,0.026268,0.038570,1.660250,1.660250,1.809500,2.63,3.86
4,5,"Stevens, Sam",25569,0.032234,0.031150,0.463625,0.631708,-0.054167,3.22,3.11
5,6,"Horschel, Billy",11276,0.024376,0.026524,1.160025,1.018750,0.587833,2.44,2.65
6,7,"Phillips, Chandler",27164,0.027495,0.026465,0.062000,0.265250,-0.800000,2.75,2.65
7,8,"Hoey, Rico",23504,0.025630,0.023941,0.573400,0.778958,0.355167,2.56,2.39
8,9,"Novak, Andrew",23475,0.019467,0.022696,0.737125,0.735833,0.055083,1.95,2.27
9,10,"McCarthy, Denny",19870,0.017747,0.021930,0.555325,0.663792,1.260583,1.77,2.19

=== Event 2 | 2025-01-19 | Desert Classic ===
Top-10 (Desert Classic)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Meissner, Mac",28159,0.084884,0.102215,0.897600,0.632375,0.765000,8.49,10.22
1,2,"Greyserman, Max",23465,0.031604,0.046225,0.921875,1.453292,0.469167,3.16,4.62
2,3,"Hall, Harry",27194,0.025595,0.034135,0.793675,1.302875,1.564917,2.56,3.41
3,4,"Spaun, J.J.",17536,0.022765,0.027474,1.009425,2.055917,2.287333,2.28,2.75
4,5,"Smalley, Alex",18474,0.022152,0.022957,-0.479150,0.251500,1.336917,2.22,2.30
5,6,"Johnson, Zach",6986,0.024924,0.021269,0.253475,0.310750,0.370667,2.49,2.13
6,7,"Cantlay, Patrick",15466,0.012222,0.020613,1.320875,1.771667,1.368000,1.22,2.06
7,8,"Thomas, Justin",14139,0.010755,0.020494,0.790000,0.620542,0.034667,1.08,2.05
8,9,"Taylor, Nick",13126,0.018966,0.020332,-0.004425,0.263458,0.378333,1.90,2.03
9,10,"Burns, Sam",19483,0.011475,0.020050,1.267275,1.202792,1.510917,1.15,2.01

=== Event 4 | 2025-01-25 | Farmers Insurance Open ===
Top-10 (Farmers Insurance Open)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Griffin, Ben",24968,0.036481,0.047210,0.381550,0.325792,0.334750,3.65,4.72
1,2,"Clanton, Luke",32330,0.031917,0.041161,1.602609,1.602609,1.303000,3.19,4.12
2,3,"Matsuyama, Hideki",13562,0.020678,0.040870,1.565275,1.482625,2.503000,2.07,4.09
3,4,"Kitayama, Kurt",21891,0.026168,0.038117,0.371575,0.788167,0.148750,2.62,3.81
4,5,"Day, Jason",9771,0.023068,0.036910,0.914375,1.274750,1.106417,2.31,3.69
5,6,"Finau, Tony",11676,0.017684,0.028191,1.258525,0.874917,0.255917,1.77,2.82
6,7,"Spaun, J.J.",17536,0.019471,0.024071,1.176675,1.927958,1.849833,1.95,2.41
7,8,"Pendrith, Taylor",17780,0.016128,0.023326,0.870875,0.625625,0.791667,1.61,2.33
8,9,"McNealy, Maverick",18634,0.014957,0.021615,0.924100,0.652917,0.542083,1.50,2.16
9,10,"Rai, Aaron",18554,0.017464,0.021559,1.399700,0.661750,0.179167,1.75,2.16

=== Event 5 | 2025-02-02 | AT&T Pebble Beach Pro-Am ===
Top-10 (AT&T Pebble Beach Pro-Am)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Pendrith, Taylor",17780,0.075702,0.078026,0.894625,1.173833,0.986417,7.57,7.80
1,2,"McIlroy, Rory",10091,0.036821,0.059384,1.641800,0.946083,-0.004250,3.68,5.94
2,3,"Scheffler, Scottie",18417,0.025718,0.058825,2.308175,1.648708,1.061833,2.57,5.88
3,4,"Henley, Russell",14578,0.052982,0.051909,1.404425,1.332167,1.512583,5.30,5.19
4,5,"Aberg, Ludvig",23950,0.025040,0.035003,1.192075,0.349667,0.296583,2.50,3.50
5,6,"Straka, Sepp",17511,0.033708,0.031567,1.033225,1.455375,2.589500,3.37,3.16
6,7,"Cantlay, Patrick",15466,0.022165,0.030923,1.277650,1.393333,1.301583,2.22,3.09
7,8,"Stevens, Sam",25569,0.037401,0.029525,0.852900,0.808000,1.670167,3.74,2.95
8,9,"Morikawa, Collin",22085,0.018895,0.028615,1.811050,1.170792,0.561833,1.89,2.86
9,10,"Day, Jason",9771,0.022991,0.027015,0.835900,1.284333,1.832333,2.30,2.70

=== Event 3 | 2025-02-09 | Waste Management Phoenix Open ===
Top-10 (Waste Management Phoenix Open)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Thomas, Justin",14139,0.034254,0.061388,0.743775,0.687083,1.847417,3.43,6.14
1,2,"Straka, Sepp",17511,0.042546,0.054618,0.806025,1.301917,2.527750,4.25,5.46
2,3,"Scheffler, Scottie",18417,0.017341,0.051051,2.185375,1.866625,1.164833,1.73,5.11
3,4,"Matsuyama, Hideki",13562,0.024800,0.042314,1.312175,1.333667,1.033750,2.48,4.23
4,5,"Burns, Sam",19483,0.020538,0.030232,1.019325,0.848375,0.732917,2.05,3.02
5,6,"Thorbjornsen, Michael",26649,0.032665,0.029871,0.136450,0.317333,-0.761250,3.27,2.99
6,7,"Power, Seamus",10104,0.031382,0.028668,0.602275,0.453583,0.168250,3.14,2.87
7,8,"Clanton, Luke",32330,0.025481,0.028271,1.452500,1.524917,1.095833,2.55,2.83
8,9,"Taylor, Nick",13126,0.022835,0.025283,0.340000,0.689417,1.435250,2.28,2.53
9,10,"Detry, Thomas",14181,0.025017,0.025244,0.511275,0.661333,1.752583,2.50,2.52

=== Event 7 | 2025-02-16 | Genesis Open ===
Top-10 (Genesis Open)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.040417,0.089789,2.051825,1.566125,1.467667,4.04,8.98
1,2,"Pendrith, Taylor",17780,0.065031,0.069124,0.901500,0.752333,0.702333,6.50,6.91
2,3,"Matsuyama, Hideki",13562,0.050324,0.064598,1.386525,1.567208,0.631417,5.03,6.46
3,4,"Burns, Sam",19483,0.052719,0.053343,1.104350,1.047500,0.584083,5.27,5.33
4,5,"Cantlay, Patrick",15466,0.035680,0.040841,1.323050,1.295917,1.343917,3.57,4.08
5,6,"Morikawa, Collin",22085,0.028637,0.040265,1.506175,0.823375,0.359167,2.86,4.03
6,7,"McIlroy, Rory",10091,0.021313,0.040157,1.812200,0.914583,1.442500,2.13,4.02
7,8,"Kim, Michael",17543,0.053454,0.040016,0.320025,0.205750,1.056250,5.35,4.00
8,9,"Thomas, Justin",14139,0.028565,0.038612,0.747300,0.866625,1.698583,2.86,3.86
9,10,"Henley, Russell",14578,0.037229,0.035911,1.395950,1.526417,1.304917,3.72,3.59

=== Event 540 | 2025-02-23 | Mexico Open at Vidanta ===
Top-10 (Mexico Open at Vidanta)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Bhatia, Akshay",26096,0.033574,0.057916,0.861475,0.639625,1.504583,3.36,5.79
1,2,"Rai, Aaron",18554,0.040709,0.057468,1.016850,0.606708,0.491583,4.07,5.75
2,3,"Manassero, Matteo",11460,0.040053,0.039664,0.603667,0.603667,0.704250,4.01,3.97
3,4,"Stevens, Sam",25569,0.025084,0.038119,0.509950,0.768500,0.097500,2.51,3.81
4,5,"Kim, Michael",17543,0.022451,0.032900,0.482350,0.584417,1.717333,2.25,3.29
5,6,"Bridgeman, Jacob",29433,0.026600,0.029511,0.897975,0.801708,0.378333,2.66,2.95
6,7,"Moore, Taylor",21944,0.016506,0.024096,0.363325,0.494042,0.702750,1.65,2.41
7,8,"Lower, Justin",17723,0.019071,0.021951,0.359500,0.598625,0.236833,1.91,2.20
8,9,"Griffin, Ben",24968,0.015509,0.021529,0.229000,0.298167,0.254583,1.55,2.15
9,10,"Smalley, Alex",18474,0.016030,0.021342,0.305875,1.406208,1.596417,1.60,2.13

=== Event 10 | 2025-03-02 | The Honda Classic ===
Top-10 (The Honda Classic)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Lowry, Shane",13900,0.026670,0.041821,0.907800,0.704167,1.012917,2.67,4.18
1,2,"Manassero, Matteo",11460,0.044084,0.036610,0.268458,0.268458,0.097000,4.41,3.66
2,3,"Ghim, Doug",24550,0.030433,0.030339,0.256150,0.198375,0.322667,3.04,3.03
3,4,"Dahmen, Joel",14509,0.028901,0.027067,0.590575,0.431917,1.534667,2.89,2.71
4,5,"Clanton, Luke",32330,0.022173,0.026270,1.440207,1.530875,0.634417,2.22,2.63
5,6,"Smalley, Alex",18474,0.021461,0.026240,0.579175,1.268292,1.441167,2.15,2.62
6,7,"Greyserman, Max",23465,0.022051,0.026123,0.712150,0.446958,-0.206417,2.21,2.61
7,8,"Svensson, Jesper",26850,0.027445,0.024999,0.398167,0.338792,0.357833,2.74,2.50
8,9,"Bridgeman, Jacob",29433,0.024553,0.023591,0.889050,0.775583,0.625333,2.46,2.36
9,10,"Power, Seamus",10104,0.020678,0.023149,0.575325,0.335625,0.525417,2.07,2.31

=== Event 9 | 2025-03-09 | Arnold Palmer Invitational presented by Mastercard ===
Top-10 (Arnold Palmer Invitational presented by Mastercard)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Aberg, Ludvig",23950,0.048776,0.069122,0.975375,0.375625,0.398917,4.88,6.91
1,2,"Fleetwood, Tommy",12294,0.047293,0.055508,1.063800,0.783042,1.364750,4.73,5.55
2,3,"Scheffler, Scottie",18417,0.022027,0.052834,1.878825,1.403125,1.744417,2.20,5.28
3,4,"Henley, Russell",14578,0.050026,0.052168,1.501625,1.622750,1.732917,5.00,5.22
4,5,"Thomas, Justin",14139,0.039621,0.048038,0.992375,1.246917,1.577750,3.96,4.80
5,6,"Cantlay, Patrick",15466,0.033955,0.040999,1.228475,1.007917,0.647833,3.40,4.10
6,7,"Matsuyama, Hideki",13562,0.033917,0.040952,1.064475,1.010292,0.577750,3.39,4.10
7,8,"Griffin, Ben",24968,0.042733,0.038610,0.588275,0.516417,1.750667,4.27,3.86
8,9,"Straka, Sepp",17511,0.038000,0.036391,1.044925,1.605208,0.972750,3.80,3.64
9,10,"McIlroy, Rory",10091,0.019625,0.035082,1.367625,0.574708,1.948083,1.96,3.51

=== Event 11 | 2025-03-16 | THE PLAYERS Championship ===
Top-10 (THE PLAYERS Championship)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Henley, Russell",14578,0.049617,0.071428,1.399125,1.533000,1.761083,4.96,7.14
1,2,"Cantlay, Patrick",15466,0.027247,0.038553,1.537300,1.379000,1.456417,2.72,3.86
2,3,"Scheffler, Scottie",18417,0.013227,0.038462,1.717500,1.399208,1.633583,1.32,3.85
3,4,"Thomas, Justin",14139,0.017123,0.028207,0.839375,1.532167,1.216917,1.71,2.82
4,5,"Rai, Aaron",18554,0.023444,0.026026,0.849100,0.616958,1.640833,2.34,2.60
5,6,"Lowry, Shane",13900,0.018015,0.024169,1.210775,1.257708,1.261083,1.80,2.42
6,7,"Bhatia, Akshay",26096,0.023002,0.023395,0.632200,0.730833,1.704667,2.30,2.34
7,8,"Schauffele, Xander",19895,0.014046,0.023087,2.082150,1.461750,0.552583,1.40,2.31
8,9,"Morikawa, Collin",22085,0.011303,0.021645,1.546850,1.134125,1.706417,1.13,2.16
9,10,"Berger, Daniel",17606,0.016574,0.019893,1.043575,1.492000,1.511083,1.66,1.99

=== Event 475 | 2025-03-23 | Valspar Championship ===
Top-10 (Valspar Championship)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Conners, Corey",17576,0.062956,0.090132,0.602900,0.806458,2.682167,6.30,9.01
1,2,"Straka, Sepp",17511,0.026496,0.047497,1.290725,1.187750,1.547583,2.65,4.75
2,3,"Fleetwood, Tommy",12294,0.019463,0.039145,1.216250,1.395667,1.682167,1.95,3.91
3,4,"Thomas, Justin",14139,0.017744,0.029436,0.966550,1.357042,1.015500,1.77,2.94
4,5,"Lowry, Shane",13900,0.020250,0.028081,1.295050,1.571917,2.130917,2.03,2.81
5,6,"Poston, J.T.",21554,0.023854,0.026475,0.293875,0.383125,0.265500,2.39,2.65
6,7,"Glover, Lucas",7399,0.018851,0.021914,0.547375,1.051250,1.377917,1.89,2.19
7,8,"Griffin, Ben",24968,0.020540,0.021768,0.340850,0.693000,0.382833,2.05,2.18
8,9,"Shipley, Neal",32055,0.026412,0.019380,0.210333,0.210333,0.008583,2.64,1.94
9,10,"Bridgeman, Jacob",29433,0.014373,0.017670,1.186875,1.253125,1.880917,1.44,1.77

=== Event 20 | 2025-03-30 | Houston Open ===
Top-10 (Houston Open)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.014689,0.046008,1.816075,1.769583,2.071500,1.47,4.60
1,2,"McIlroy, Rory",10091,0.012711,0.033075,1.360600,1.673667,1.904833,1.27,3.31
2,3,"Lee, Min Woo",16841,0.013914,0.021397,0.743775,1.261750,2.040167,1.39,2.14
3,4,"Spaun, J.J.",17536,0.012679,0.020459,1.466675,1.252750,1.837750,1.27,2.05
4,5,"Day, Jason",9771,0.009170,0.014053,0.919025,1.045500,0.258667,0.92,1.41
5,6,"Pendrith, Taylor",17780,0.008942,0.013130,0.746425,0.510542,0.318750,0.89,1.31
6,7,"Riley, Davis",19872,0.011321,0.012849,-0.403325,-0.332500,1.345167,1.13,1.28
7,8,"Griffin, Ben",24968,0.009292,0.012327,0.395150,0.632375,-0.167750,0.93,1.23
8,9,"Kim, Michael",17543,0.007767,0.011891,1.031150,1.420583,1.487250,0.78,1.19
9,10,"Thompson, Davis",27364,0.007703,0.011793,0.358000,0.675333,0.818750,0.77,1.18

=== Event 41 | 2025-04-06 | Valero Texas Open ===
Top-10 (Valero Texas Open)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Cantlay, Patrick",15466,0.014493,0.026147,1.397150,1.363042,1.382167,1.45,2.61
1,2,"Conners, Corey",17576,0.011914,0.022246,0.589250,1.238292,2.148833,1.19,2.22
2,3,"McCarthy, Denny",19870,0.012896,0.020285,1.156825,1.275667,1.580917,1.29,2.03
3,4,"Fleetwood, Tommy",12294,0.009554,0.017813,1.154800,1.506792,1.648833,0.96,1.78
4,5,"Aberg, Ludvig",23950,0.008525,0.017342,0.792575,0.607167,0.917750,0.85,1.73
5,6,"Berger, Daniel",17606,0.010812,0.016624,0.948750,1.465375,0.997583,1.08,1.66
6,7,"Bradley, Keegan",13872,0.009507,0.016073,0.897950,0.807833,1.548833,0.95,1.61
7,8,"Matsuyama, Hideki",13562,0.008623,0.015003,0.965125,0.583292,0.334417,0.86,1.50
8,9,"Cauley, Bud",14502,0.011032,0.014962,0.580225,1.346000,1.905833,1.10,1.50
9,10,"Bhatia, Akshay",26096,0.008436,0.014251,0.572800,1.128708,1.292750,0.84,1.43

=== Event 14 | 2025-04-13 | The Masters ===
Top-10 (The Masters)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.028415,0.076977,1.885825,2.098333,2.452250,2.84,7.70
1,2,"McIlroy, Rory",10091,0.031037,0.071880,1.594900,2.575167,3.202250,3.10,7.19
2,3,"Morikawa, Collin",22085,0.020352,0.034585,1.451575,1.433917,2.508667,2.04,3.46
3,4,"DeChambeau, Bryson",19841,0.020283,0.033760,1.804450,2.265542,3.452667,2.03,3.38
4,5,"Lowry, Shane",13900,0.018263,0.023682,1.275200,1.545792,2.025333,1.83,2.37
5,6,"Thomas, Justin",14139,0.015347,0.022301,0.913050,1.259875,0.942000,1.53,2.23
6,7,"Rahm, Jon",19195,0.012418,0.021971,1.070425,0.962417,1.017583,1.24,2.20
7,8,"Schauffele, Xander",19895,0.013334,0.021661,1.567100,1.084542,0.525333,1.33,2.17
8,9,"Henley, Russell",14578,0.018784,0.021538,1.518000,1.517583,1.750750,1.88,2.15
9,10,"MacIntyre, Robert",23323,0.015907,0.018198,0.986250,0.776375,0.638917,1.59,1.82

=== Event 12 | 2025-04-20 | RBC Heritage ===
Top-10 (RBC Heritage)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.029292,0.072747,1.797475,2.067875,2.502167,2.93,7.27
1,2,"Hovland, Viktor",18841,0.039076,0.048309,0.759600,0.483333,2.039667,3.91,4.83
2,3,"Thomas, Justin",14139,0.025068,0.035222,1.300675,1.521083,1.825250,2.51,3.52
3,4,"Henley, Russell",14578,0.024074,0.031323,1.476575,1.431500,1.724500,2.41,3.13
4,5,"Cantlay, Patrick",15466,0.020130,0.029216,1.089925,1.070250,0.684083,2.01,2.92
5,6,"Schauffele, Xander",19895,0.016340,0.025763,1.379575,0.563917,0.575250,1.63,2.58
6,7,"Morikawa, Collin",22085,0.014818,0.025322,1.141550,1.160792,0.873500,1.48,2.53
7,8,"Hoge, Tom",15575,0.025881,0.021699,0.032325,0.430917,1.850750,2.59,2.17
8,9,"McCarthy, Denny",19870,0.020173,0.020624,0.941375,0.764250,0.767417,2.02,2.06
9,10,"Aberg, Ludvig",23950,0.012338,0.020442,0.637175,0.443208,0.487500,1.23,2.04

=== Event 19 | 2025-05-04 | AT&T Byron Nelson ===
Top-10 (AT&T Byron Nelson)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.027934,0.087241,2.025800,2.669500,3.267500,2.79,8.72
1,2,"Hughes, Mackenzie",15556,0.014687,0.020023,0.044700,0.342750,1.566917,1.47,2.00
2,3,"Cole, Eric",21756,0.016052,0.019127,-0.005000,0.761125,1.535000,1.61,1.91
3,4,"Griffin, Ben",24968,0.012790,0.018806,0.341425,0.706417,0.572917,1.28,1.88
4,5,"Im, Sungjae",17488,0.010607,0.017259,0.693100,0.725708,1.517500,1.06,1.73
5,6,"Spieth, Jordan",14636,0.009087,0.016324,0.427900,1.063958,1.305417,0.91,1.63
6,7,"Gerard, Ryan",29767,0.011768,0.014655,1.006250,0.973875,1.035083,1.18,1.47
7,8,"Kuchar, Matt",6169,0.013092,0.013945,0.869925,0.338708,0.761500,1.31,1.39
8,9,"Hahn, James",11374,0.015302,0.013863,-0.470000,-0.564250,-0.298833,1.53,1.39
9,10,"Springer, Hayden",21995,0.012211,0.012287,0.599000,0.328833,0.337417,1.22,1.23

=== Event 480 | 2025-05-11 | Wells Fargo Championship ===
Top-10 (Wells Fargo Championship)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"McIlroy, Rory",10091,0.029111,0.064985,1.405725,2.279792,2.769833,2.91,6.50
1,2,"Thomas, Justin",14139,0.038170,0.055194,1.708975,1.508500,2.001500,3.82,5.52
2,3,"Straka, Sepp",17511,0.037675,0.040345,1.633650,1.563042,1.144583,3.77,4.03
3,4,"Schauffele, Xander",19895,0.026652,0.038242,1.166725,0.327750,1.418167,2.67,3.82
4,5,"Morikawa, Collin",22085,0.017653,0.026301,1.021600,1.185208,0.664000,1.77,2.63
5,6,"Cantlay, Patrick",15466,0.019346,0.025677,1.099725,0.937917,0.493667,1.93,2.57
6,7,"Matsuyama, Hideki",13562,0.019818,0.023025,1.227350,0.791458,1.005167,1.98,2.30
7,8,"Henley, Russell",14578,0.019346,0.022468,1.097200,0.981333,0.497000,1.93,2.25
8,9,"Lowry, Shane",13900,0.020010,0.022096,1.419300,1.607875,1.084833,2.00,2.21
9,10,"Fleetwood, Tommy",12294,0.017653,0.021747,1.160975,1.196250,0.743667,1.77,2.17

=== Event 33 | 2025-05-18 | PGA Championship ===
Top-10 (PGA Championship)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.023210,0.079570,2.569950,3.198625,3.945000,2.32,7.96
1,2,"DeChambeau, Bryson",19841,0.015404,0.041016,2.060700,2.509292,2.339500,1.54,4.10
2,3,"McIlroy, Rory",10091,0.011337,0.036642,1.461725,2.069167,2.233500,1.13,3.66
3,4,"Rahm, Jon",19195,0.009823,0.020583,1.286225,1.158917,2.236417,0.98,2.06
4,5,"Thomas, Justin",14139,0.010508,0.020559,1.548875,1.324250,1.595750,1.05,2.06
5,6,"Schauffele, Xander",19895,0.009804,0.019172,1.249800,0.732917,0.940500,0.98,1.92
6,7,"Niemann, Joaquin",18079,0.009134,0.016040,0.951350,0.690500,0.920083,0.91,1.60
7,8,"Cantlay, Patrick",15466,0.009806,0.014972,0.990900,0.837000,0.762417,0.98,1.50
8,9,"Fleetwood, Tommy",12294,0.009476,0.014465,1.272300,1.054875,1.607167,0.95,1.45
9,10,"Berger, Daniel",17606,0.012203,0.014142,1.397450,1.287333,1.440500,1.22,1.41

=== Event 21 | 2025-05-25 | Charles Schwab Challenge ===
Top-10 (Charles Schwab Challenge)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.030845,0.101530,2.650450,3.203625,3.905083,3.08,10.15
1,2,"Berger, Daniel",17606,0.013188,0.021545,1.320575,1.292958,1.240917,1.32,2.15
2,3,"Fleetwood, Tommy",12294,0.012281,0.019231,1.327800,1.127750,1.483917,1.23,1.92
3,4,"Spieth, Jordan",14636,0.011301,0.018438,0.980850,1.067083,1.316083,1.13,1.84
4,5,"McNealy, Maverick",18634,0.010255,0.015107,0.585525,0.691292,0.074250,1.03,1.51
5,6,"Gotterup, Chris",27774,0.016868,0.014699,0.360200,0.191417,0.997000,1.69,1.47
6,7,"Spaun, J.J.",17536,0.011161,0.014402,0.820100,0.701917,1.400583,1.12,1.44
7,8,"Matsuyama, Hideki",13562,0.009358,0.014092,0.771100,0.701833,1.043333,0.94,1.41
8,9,"Rai, Aaron",18554,0.009457,0.013924,0.846675,0.714667,0.657583,0.95,1.39
9,10,"Smalley, Alex",18474,0.012491,0.013349,0.986500,0.766542,0.695083,1.25,1.33

=== Event 23 | 2025-06-01 | the Memorial Tournament presented by Nationwide ===
Top-10 (the Memorial Tournament presented by Nationwide)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.047182,0.121043,2.784375,3.480458,3.693417,4.72,12.10
1,2,"Straka, Sepp",17511,0.034379,0.036952,1.327675,1.515333,2.095750,3.44,3.70
2,3,"Griffin, Ben",24968,0.034576,0.033390,1.356675,1.662667,2.834000,3.46,3.34
3,4,"Conners, Corey",17576,0.025486,0.030677,1.370325,1.235042,1.531833,2.55,3.07
4,5,"Fleetwood, Tommy",12294,0.024423,0.030513,1.303425,1.163833,1.584000,2.44,3.05
5,6,"Lowry, Shane",13900,0.026559,0.029682,1.384300,1.419583,1.595750,2.66,2.97
6,7,"Morikawa, Collin",22085,0.018262,0.026376,0.939825,0.744333,0.615167,1.83,2.64
7,8,"Schauffele, Xander",19895,0.018027,0.026033,1.155200,1.095208,1.615167,1.80,2.60
8,9,"Cantlay, Patrick",15466,0.018707,0.024297,1.164800,1.015667,1.095750,1.87,2.43
9,10,"Bradley, Keegan",13872,0.023591,0.024169,0.902900,1.066125,1.365167,2.36,2.42

=== Event 32 | 2025-06-08 | RBC Canadian Open ===
Top-10 (RBC Canadian Open)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"McIlroy, Rory",10091,0.013392,0.037663,1.300425,1.432500,0.302000,1.34,3.77
1,2,"Conners, Corey",17576,0.016393,0.029228,1.591050,1.018208,1.292750,1.64,2.92
2,3,"Pendrith, Taylor",17780,0.018163,0.029173,0.345100,0.504958,1.709417,1.82,2.92
3,4,"Roy, Kevin",18424,0.026644,0.027186,0.688325,0.202000,1.274583,2.66,2.72
4,5,"Clanton, Luke",32330,0.013404,0.019173,1.255111,0.791625,0.547250,1.34,1.92
5,6,"Taylor, Nick",13126,0.013646,0.018809,0.528450,0.445750,1.332667,1.36,1.88
6,7,"Burns, Sam",19483,0.011278,0.018026,0.552300,1.254083,1.292750,1.13,1.80
7,8,"Aberg, Ludvig",23950,0.008653,0.017161,0.416775,0.234750,0.332667,0.87,1.72
8,9,"Lowry, Shane",13900,0.009590,0.016519,1.186825,1.168208,1.416000,0.96,1.65
9,10,"Gotterup, Chris",27774,0.011975,0.015048,0.344400,0.338083,0.828417,1.20,1.50

=== Event 26 | 2025-06-15 | U.S. Open ===
Top-10 (U.S. Open)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.028310,0.105516,2.980350,3.390333,2.835667,2.83,10.55
1,2,"DeChambeau, Bryson",19841,0.014800,0.039495,2.136900,2.596917,1.563500,1.48,3.95
2,3,"McIlroy, Rory",10091,0.015705,0.035765,1.547200,1.375500,-0.044333,1.57,3.58
3,4,"Rahm, Jon",19195,0.012568,0.028565,1.270925,1.098917,2.149250,1.26,2.86
4,5,"Hovland, Viktor",18841,0.017190,0.022506,0.745175,1.230875,1.710250,1.72,2.25
5,6,"Koepka, Brooks",16243,0.016268,0.021282,1.094175,0.335417,0.224250,1.63,2.13
6,7,"Morikawa, Collin",22085,0.011804,0.020842,1.026650,0.770458,0.876917,1.18,2.08
7,8,"Burns, Sam",19483,0.017499,0.020735,1.160850,2.262542,3.225667,1.75,2.07
8,9,"Griffin, Ben",24968,0.016405,0.019862,1.299800,1.720042,3.002333,1.64,1.99
9,10,"Fleetwood, Tommy",12294,0.012377,0.018582,1.339425,1.375792,1.072500,1.24,1.86

=== Event 34 | 2025-06-22 | Travelers Championship ===
Top-10 (Travelers Championship)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.046040,0.116040,2.963450,3.346417,2.787750,4.60,11.60
1,2,"McIlroy, Rory",10091,0.025996,0.041176,1.682875,1.423583,0.516417,2.60,4.12
2,3,"Bradley, Keegan",13872,0.029827,0.032849,1.305675,1.514417,1.955083,2.98,3.28
3,4,"Young, Cameron",26651,0.031544,0.030758,0.501025,1.164167,1.879833,3.15,3.08
4,5,"Cantlay, Patrick",15466,0.023765,0.030566,1.027225,0.776792,1.059917,2.38,3.06
5,6,"Morikawa, Collin",22085,0.019682,0.027040,1.067775,0.531125,0.955083,1.97,2.70
6,7,"Henley, Russell",14578,0.024439,0.025598,1.302800,1.171625,2.144250,2.44,2.56
7,8,"Thomas, Justin",14139,0.021210,0.024475,1.247725,1.155708,0.309917,2.12,2.45
8,9,"Griffin, Ben",24968,0.025144,0.024394,1.180475,1.891417,1.954417,2.51,2.44
9,10,"Rai, Aaron",18554,0.025143,0.024394,0.902000,0.596833,0.503167,2.51,2.44

=== Event 524 | 2025-06-29 | Rocket Mortgage Classic ===
Top-10 (Rocket Mortgage Classic)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Hall, Harry",27194,0.012439,0.019934,1.148000,1.663833,1.834833,1.24,1.99
1,2,"Smalley, Alex",18474,0.014520,0.019918,0.740575,0.202375,0.475750,1.45,1.99
2,3,"Cantlay, Patrick",15466,0.010073,0.019530,0.989625,1.064833,1.153333,1.01,1.95
3,4,"Griffin, Ben",24968,0.010987,0.019342,1.454025,2.288833,1.743667,1.10,1.93
4,5,"Morikawa, Collin",22085,0.008601,0.018180,1.205175,0.929417,1.243667,0.86,1.82
5,6,"Greyserman, Max",23465,0.011869,0.018135,0.388250,1.288833,1.660333,1.19,1.81
6,7,"Bradley, Keegan",13872,0.008881,0.016600,1.198125,1.387750,1.410333,0.89,1.66
7,8,"Knapp, Jake",19396,0.012802,0.015478,0.906775,0.366625,1.306083,1.28,1.55
8,9,"Fitzpatrick, Matt",17646,0.010300,0.015087,0.289375,0.929417,1.577000,1.03,1.51
9,10,"Kim, Si Woo",14609,0.009268,0.014820,0.737175,0.697792,-0.037583,0.93,1.48

=== Event 30 | 2025-07-06 | John Deere Classic ===
Top-10 (John Deere Classic)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Griffin, Ben",24968,0.019453,0.034885,1.576250,2.148708,1.141583,1.95,3.49
1,2,"Lawrence, Thriston",18105,0.024570,0.027513,-0.394100,-0.149333,1.955167,2.46,2.75
2,3,"Cauley, Bud",14502,0.013277,0.018107,0.988700,0.383625,-0.005417,1.33,1.81
3,4,"Clanton, Luke",32330,0.012714,0.018033,0.949200,0.333750,-0.075083,1.27,1.80
4,5,"Champ, Cameron",23542,0.015103,0.016788,0.778175,1.649042,2.013500,1.51,1.68
5,6,"Kim, Si Woo",14609,0.011126,0.016498,0.692325,0.646542,0.074000,1.11,1.65
6,7,"Ventura, Kris",15651,0.017681,0.016330,0.306775,0.188125,1.082833,1.77,1.63
7,8,"Gotterup, Chris",27774,0.011075,0.015690,0.779125,1.347167,1.714333,1.11,1.57
8,9,"Knapp, Jake",19396,0.010889,0.015424,0.927625,0.744125,1.378833,1.09,1.54
9,10,"Smalley, Alex",18474,0.010920,0.014358,0.824125,0.254500,-0.111667,1.09,1.44

=== Event 541 | 2025-07-13 | Genesis Scottish Open ===
Top-10 (Genesis Scottish Open)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.034692,0.106025,3.027750,3.069125,2.444833,3.47,10.60
1,2,"McIlroy, Rory",10091,0.020929,0.048054,1.764925,1.620792,1.677500,2.09,4.81
2,3,"Hojgaard, Nicolai",23602,0.025999,0.026779,0.435775,0.204042,1.285667,2.60,2.68
3,4,"Fitzpatrick, Matt",17646,0.018250,0.023729,0.657375,1.573375,1.936500,1.83,2.37
4,5,"Conners, Corey",17576,0.017004,0.023003,1.309750,0.942958,0.749500,1.70,2.30
5,6,"Hall, Harry",27194,0.019049,0.021830,1.424350,1.774708,1.828167,1.90,2.18
6,7,"Fleetwood, Tommy",12294,0.013002,0.021532,1.314350,1.691833,1.354500,1.30,2.15
7,8,"Clark, Wyndham",23604,0.018436,0.020584,0.226225,0.202792,1.196167,1.84,2.06
8,9,"Morikawa, Collin",22085,0.010080,0.015945,0.876275,0.636625,0.444000,1.01,1.59
9,10,"Hovland, Viktor",18841,0.011417,0.015378,0.968375,1.182667,1.978917,1.14,1.54

=== Event 100 | 2025-07-20 | The Open Championship ===
Top-10 (The Open Championship)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.032529,0.101970,3.282825,2.957708,3.079750,3.25,10.20
1,2,"McIlroy, Rory",10091,0.027363,0.072265,1.909575,1.559375,3.163083,2.74,7.23
2,3,"Rahm, Jon",19195,0.012228,0.027303,1.401025,1.660125,2.302667,1.22,2.73
3,4,"Hatton, Tyrrell",14796,0.012786,0.020842,1.094800,1.294333,1.886000,1.28,2.08
4,5,"Fitzpatrick, Matt",17646,0.013672,0.018683,1.264225,1.683333,2.828250,1.37,1.87
5,6,"DeChambeau, Bryson",19841,0.009746,0.017645,2.063650,2.330792,1.649917,0.97,1.76
6,7,"Gotterup, Chris",27774,0.015203,0.016346,1.442575,1.893083,2.580000,1.52,1.63
7,8,"Griffin, Ben",24968,0.013523,0.015062,1.554775,2.014750,1.105250,1.35,1.51
8,9,"Spieth, Jordan",14636,0.011277,0.014881,1.275425,1.255583,1.195083,1.13,1.49
9,10,"Straka, Sepp",17511,0.010756,0.014666,1.373250,1.400708,0.877167,1.08,1.47

=== Event 525 | 2025-07-27 | 3M Open ===
Top-10 (3M Open)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Gotterup, Chris",27774,0.038164,0.066098,1.773250,2.362917,3.011500,3.82,6.61
1,2,"Kitayama, Kurt",21891,0.025675,0.034714,0.754575,1.180417,1.811917,2.57,3.47
2,3,"Burns, Sam",19483,0.016233,0.027719,1.506400,1.448750,0.684333,1.62,2.77
3,4,"Knapp, Jake",19396,0.019660,0.027554,0.993350,1.638583,1.971083,1.97,2.76
4,5,"Clark, Wyndham",23604,0.013788,0.021300,0.419750,1.108792,1.866750,1.38,2.13
5,6,"Hodges, Lee",25157,0.015649,0.017728,0.495475,0.455875,0.489750,1.56,1.77
6,7,"Roy, Kevin",18424,0.013719,0.014902,0.746800,1.434208,1.593833,1.37,1.49
7,8,"McNealy, Maverick",18634,0.008725,0.014365,0.741575,0.816167,0.926667,0.87,1.44
8,9,"Grillo, Emiliano",12808,0.010941,0.013678,0.924600,1.487417,1.202167,1.09,1.37
9,10,"Stevens, Sam",25569,0.011746,0.013569,0.816200,0.739042,1.107000,1.17,1.36

=== Event 13 | 2025-08-03 | Wyndham Championship ===
Top-10 (Wyndham Championship)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Hall, Harry",27194,0.030225,0.039599,1.594375,1.599625,1.364417,3.02,3.96
1,2,"Fitzpatrick, Matt",17646,0.018964,0.030731,1.486900,2.220708,2.864417,1.90,3.07
2,3,"Griffin, Ben",24968,0.018256,0.027545,1.541500,1.670375,1.386333,1.83,2.75
3,4,"Hojgaard, Nicolai",23602,0.020928,0.024589,0.886025,1.242375,1.781083,2.09,2.46
4,5,"Kitayama, Kurt",21891,0.018895,0.022854,0.964575,1.383792,2.007500,1.89,2.29
5,6,"Matsuyama, Hideki",13562,0.015222,0.021623,0.889800,0.950833,2.113917,1.52,2.16
6,7,"MacIntyre, Robert",23323,0.014300,0.020300,1.081350,1.273417,1.083667,1.43,2.03
7,8,"Glover, Lucas",7399,0.014475,0.019562,0.359825,0.825583,1.416000,1.45,1.96
8,9,"Bezuidenhout, Christiaan",18103,0.016569,0.018866,0.745450,0.847208,1.270083,1.66,1.89
9,10,"Wallace, Matt",20706,0.017266,0.018720,1.024300,1.047167,1.186750,1.73,1.87

=== Event 27 | 2025-08-10 | THE NORTHERN TRUST ===
Top-10 (THE NORTHERN TRUST)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.064227,0.158301,3.234625,3.071958,3.356167,6.42,15.83
1,2,"Henley, Russell",14578,0.030113,0.033577,1.325825,1.152375,1.887917,3.01,3.36
2,3,"Griffin, Ben",24968,0.029521,0.031224,1.812100,1.610750,1.477833,2.95,3.12
3,4,"Hall, Harry",27194,0.034742,0.030706,1.568975,1.609417,1.390667,3.47,3.07
4,5,"Fleetwood, Tommy",12294,0.024250,0.029909,1.762450,1.861208,1.689500,2.42,2.99
5,6,"Fitzpatrick, Matt",17646,0.024165,0.027462,1.478325,1.996917,2.057333,2.42,2.75
6,7,"Aberg, Ludvig",23950,0.024556,0.027268,0.733675,1.322833,1.606167,2.46,2.73
7,8,"Gotterup, Chris",27774,0.025861,0.025038,1.513475,1.673417,1.459250,2.59,2.50
8,9,"English, Harris",14577,0.024768,0.023960,1.183275,1.321958,1.939500,2.48,2.40
9,10,"Rose, Justin",6093,0.029530,0.022625,0.499425,0.115875,2.218500,2.95,2.26

=== Event 28 | 2025-08-17 | BMW Championship ===
Top-10 (BMW Championship)

,pred_rank,player_name,dg_id,p_win_norm,p_win_blend_norm,sg_total_L40,sg_total_L24,sg_total_L12,p_win_norm_pct,p_win_blend_norm_pct
0,1,"Scheffler, Scottie",18417,0.080990,0.182346,3.397150,3.089167,3.733500,8.10,18.23
1,2,"McIlroy, Rory",10091,0.057376,0.088868,1.895850,1.594833,2.673250,5.74,8.89
2,3,"Fleetwood, Tommy",12294,0.052032,0.058314,1.809450,1.877333,2.400167,5.20,5.83
3,4,"Fitzpatrick, Matt",17646,0.048087,0.044613,1.568675,1.895042,0.961833,4.81,4.46
4,5,"Young, Cameron",26651,0.039416,0.040653,1.516500,1.519083,2.672167,3.94,4.07
5,6,"Gotterup, Chris",27774,0.041733,0.038532,1.388525,1.305208,0.030417,4.17,3.85
6,7,"Thomas, Justin",14139,0.030050,0.030785,0.982725,0.794000,0.733500,3.00,3.08
7,8,"Aberg, Ludvig",23950,0.026388,0.028141,0.894050,1.614750,2.066833,2.64,2.81
8,9,"Hall, Harry",27194,0.033653,0.026530,1.714475,1.853375,1.545167,3.37,2.65
9,10,"MacIntyre, Robert",23323,0.031720,0.025783,1.362925,1.437458,1.711833,3.17,2.58

Events scored: 31

,event_id,event_date,event_name,calibrated,top_pick,top_pick_pwin,top_pick_won,winner_name,winner_rank,brier,auc,n_field
0,6,2025-01-12,Sony Open in Hawaii,1,"Henley, Russell",0.038401,0,"Taylor, Nick",111,0.013240,0.106667,143
1,2,2025-01-19,Desert Classic,1,"Meissner, Mac",0.084884,0,"Straka, Sepp",18,0.013929,0.814286,156
2,4,2025-01-25,Farmers Insurance Open,1,"Griffin, Ben",0.036481,0,"English, Harris",13,0.013918,0.927536,154
3,5,2025-02-02,AT&T Pebble Beach Pro-Am,1,"Pendrith, Taylor",0.075702,0,"McIlroy, Rory",2,0.012171,0.961039,80
4,3,2025-02-09,Waste Management Phoenix Open,1,"Thomas, Justin",0.034254,0,"Detry, Thomas",10,0.012493,0.947368,132
5,7,2025-02-16,Genesis Open,1,"Scheffler, Scottie",0.040417,0,"Aberg, Ludvig",19,0.018471,0.584906,72
6,540,2025-02-23,Mexico Open at Vidanta,1,"Bhatia, Akshay",0.033574,0,"Campbell, Brian",33,0.012829,0.750000,132
7,10,2025-03-02,The Honda Classic,1,"Lowry, Shane",0.026670,0,"Highsmith, Joe",62,0.014706,0.432836,144
8,9,2025-03-09,Arnold Palmer Invitational presented by Master...,1,"Aberg, Ludvig",0.048776,0,"Henley, Russell",4,0.018120,1.000000,72
9,11,2025-03-16,THE PLAYERS Championship,1,"Henley, Russell",0.049617,0,"McIlroy, Rory",11,0.013774,0.605634,144
10,475,2025-03-23,Valspar Championship,1,"Conners, Corey",0.062956,0,"Hovland, Viktor",70,0.012883,0.402597,152
11,20,2025-03-30,Houston Open,1,"Scheffler, Scottie",0.014689,0,"Lee, Min Woo",3,0.014142,0.985294,153
12,41,2025-04-06,Valero Texas Open,1,"Cantlay, Patrick",0.014493,0,"Harman, Brian",26,0.014937,0.800000,144
13,14,2025-04-13,The Masters,1,"Scheffler, Scottie",0.028415,0,"McIlroy, Rory",2,0.017863,1.000000,95
14,12,2025-04-20,RBC Heritage,1,"Scheffler, Scottie",0.029292,0,"Thomas, Justin",3,0.013411,0.957746,72
15,19,2025-05-04,AT&T Byron Nelson,1,"Scheffler, Scottie",0.027934,1,"Scheffler, Scottie",1,0.013549,1.000000,156
16,480,2025-05-11,Wells Fargo Championship,1,"McIlroy, Rory",0.029111,0,"Straka, Sepp",3,0.013642,0.985294,72
17,33,2025-05-18,PGA Championship,1,"Scheffler, Scottie",0.023210,1,"Scheffler, Scottie",1,0.012947,1.000000,156
18,21,2025-05-25,Charles Schwab Challenge,1,"Scheffler, Scottie",0.030845,0,"Griffin, Ben",15,0.012622,0.870130,134
19,23,2025-06-01,the Memorial Tournament presented by Nationwide,1,"Scheffler, Scottie",0.047182,1,"Scheffler, Scottie",1,0.016167,1.000000,72
20,32,2025-06-08,RBC Canadian Open,1,"McIlroy, Rory",0.013392,0,"Fox, Ryan",18,0.014468,0.805970,155
21,26,2025-06-15,U.S. Open,1,"Scheffler, Scottie",0.028310,0,"Spaun, J.J.",28,0.014941,0.753846,156
22,34,2025-06-22,Travelers Championship,1,"Scheffler, Scottie",0.046040,0,"Bradley, Keegan",3,0.014301,0.969697,71
23,524,2025-06-29,Rocket Mortgage Classic,1,"Hall, Harry",0.012439,0,"Potgieter, Aldrich",47,0.011524,0.552941,156
24,30,2025-07-06,John Deere Classic,1,"Griffin, Ben",0.019453,0,"Campbell, Brian",111,0.015546,0.277778,156
25,541,2025-07-13,Genesis Scottish Open,1,"Scheffler, Scottie",0.034692,0,"Gotterup, Chris",28,0.012534,0.717949,155
26,100,2025-07-20,The Open Championship,1,"Scheffler, Scottie",0.032529,1,"Scheffler, Scottie",1,0.013444,1.000000,156
27,525,2025-07-27,3M Open,1,"Gotterup, Chris",0.038164,0,"Kitayama, Kurt",2,0.012567,0.986667,156
28,13,2025-08-03,Wyndham Championship,1,"Hall, Harry",0.030225,0,"Young, Cameron",22,0.013120,0.743243,156
29,27,2025-08-10,THE NORTHERN TRUST,1,"Scheffler, Scottie",0.064227,0,"Rose, Justin",10,0.013946,0.955882,69
30,28,2025-08-17,BMW Championship,1,"Scheffler, Scottie",0.080990,1,"Scheffler, Scottie",1,0.018111,1.000000,49