In [19]:
# ============================================================
# WIN MODEL (P(win)) — 2025 walk-forward + evaluation:
#   "higher win% guys finished relatively high (Top10)"
#
# Uses:
#   - combined_rounds_all_2017_2026.csv  (all tours)
#   - Odds_and_Results.xlsx              (field + finish_num + close_odds)
#   - OAD_2024/2025/2026.xlsx            (event schedule + event_name + start_date)
#
# Key choices:
#   - No future info: features use rounds <= (event_start_date - 1 day)
#   - Primary driver: rolling sg_total (L40/L24/L12)
#   - Odds: included as a SMALL feature (scaled), not allowed to dominate
#   - Model: regularized LogisticRegression (stable)
#   - Output: per-event Top10 board + summary metrics
# ============================================================

import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, brier_score_loss

# -----------------------------
# PATHS (EDIT IF NEEDED)
# -----------------------------
BASE_DIR = "/Users/joshmacbook/python_projects/OAD/Data/in Use"
ROUNDS_PATH = f"{BASE_DIR}/combined_rounds_all_2017_2026.csv"
ODDS_XLSX   = f"{BASE_DIR}/Odds_and_Results.xlsx"
SCHED_2024  = f"{BASE_DIR}/OAD_2024.xlsx"
SCHED_2025  = f"{BASE_DIR}/OAD_2025.xlsx"
SCHED_2026  = f"{BASE_DIR}/OAD_2026.xlsx"

# -----------------------------
# SETTINGS (EDIT)
# -----------------------------
BACKTEST_YEAR = 2025
WINDOWS = (40, 24, 12)

LR_C = 0.05
LR_MAX_ITER = 2000

ODDS_SCALE = 0.15       # keep small (you found 0.10-ish works well)
REL_HIGH_FINISH = 10    # Top10
TOP_GROUP_N = 10
TOPK_LIST = [1, 3, 5, 10, 20]

# choose one feature set
FEAT_SET_KEY = "baseline_plus_layoff"

# -----------------------------
# HELPERS
# -----------------------------
def safe_auc(y_true, y_prob):
    y_true = np.asarray(y_true)
    y_prob = np.asarray(y_prob)
    if np.unique(y_true).size < 2:
        return np.nan
    return roc_auc_score(y_true, y_prob)

def _spearman_rank_corr(a, b):
    s = pd.DataFrame({"a": a, "b": b}).dropna()
    if len(s) < 3:
        return np.nan
    ra = s["a"].rank(method="average")
    rb = s["b"].rank(method="average")
    return float(ra.corr(rb, method="pearson"))

def _logit(p, eps=1e-8):
    p = np.clip(p, eps, 1 - eps)
    return np.log(p / (1 - p))

def _to_naive_datetime(s: pd.Series) -> pd.Series:
    """Force datetime64[ns] naive for merge_asof stability (kills tz/object weirdness)."""
    s = pd.to_datetime(s, errors="coerce")
    try:
        if hasattr(s.dt, "tz") and s.dt.tz is not None:
            s = s.dt.tz_convert(None)
    except Exception:
        pass
    return s

# ============================================================
# 1) LOAD SCHEDULES -> sched_all with standard cols:
#    year, event_id, event_start_date, event_name
# ============================================================
sched_24 = pd.read_excel(SCHED_2024)
sched_25 = pd.read_excel(SCHED_2025)
sched_26 = pd.read_excel(SCHED_2026)

sched_all_raw = pd.concat([sched_24, sched_25, sched_26], ignore_index=True)

# Find date column
date_col = None
for cand in ["start_date", "event_start_date", "date", "event_date"]:
    if cand in sched_all_raw.columns:
        date_col = cand
        break
if date_col is None:
    raise ValueError("Schedule missing start date column (start_date / event_start_date / date / event_date).")

# Find name column
name_col = None
for cand in ["event_name", "tournament", "name"]:
    if cand in sched_all_raw.columns:
        name_col = cand
        break
if name_col is None:
    raise ValueError("Schedule missing event name column (event_name / tournament / name).")

sched_all = sched_all_raw.copy()
sched_all["year"] = pd.to_numeric(sched_all["year"], errors="coerce")
sched_all["event_id"] = pd.to_numeric(sched_all["event_id"], errors="coerce")
sched_all[date_col] = _to_naive_datetime(sched_all[date_col])
sched_all[name_col] = sched_all[name_col].astype(str)

sched_all = sched_all.dropna(subset=["year", "event_id", date_col]).copy()
sched_all["year"] = sched_all["year"].astype(int)
sched_all["event_id"] = sched_all["event_id"].astype(int)

sched_all = sched_all.rename(columns={date_col: "event_start_date", name_col: "event_name"})
sched_all = sched_all[["year","event_id","event_start_date","event_name"]].copy()

# backtest events (2025)
sched_bt = (
    sched_all[sched_all["year"] == BACKTEST_YEAR]
    .dropna(subset=["event_id","event_start_date"])
    .sort_values("event_start_date")
    .reset_index(drop=True)
)

print("Backtest events:", len(sched_bt))
display(sched_bt[["event_id","event_start_date","event_name"]].head(25))

# ============================================================
# 2) LOAD ODDS/RESULTS
# ============================================================
odds = pd.read_excel(ODDS_XLSX)

need_odds = {"year","event_id","dg_id","close_odds","finish_num"}
missing = need_odds - set(odds.columns)
if missing:
    raise ValueError(f"Odds_and_Results.xlsx missing required columns: {sorted(missing)}")

for c in ["year", "event_id", "dg_id"]:
    odds[c] = pd.to_numeric(odds[c], errors="coerce")

odds["close_odds"] = pd.to_numeric(odds["close_odds"], errors="coerce")
odds["finish_num"] = pd.to_numeric(odds["finish_num"], errors="coerce")

odds = odds.dropna(subset=["year","event_id","dg_id"]).copy()
odds["year"] = odds["year"].astype(int)
odds["event_id"] = odds["event_id"].astype(int)
odds["dg_id"] = odds["dg_id"].astype(int)

# Restrict odds to event_ids that appear in schedule
oad_event_ids = sorted(sched_all["event_id"].unique().tolist())
odds = odds[odds["event_id"].isin(oad_event_ids)].copy()

# ============================================================
# 3) LOAD ROUNDS + BUILD ROLLING SG_TOTAL FEATURES
# ============================================================
rounds = pd.read_csv(ROUNDS_PATH)

need_rounds = {"round_date","dg_id","player_name","sg_total"}
missing = need_rounds - set(rounds.columns)
if missing:
    raise ValueError(f"combined_rounds file missing required columns: {sorted(missing)}")

rounds["round_date"] = _to_naive_datetime(rounds["round_date"])
rounds["dg_id"] = pd.to_numeric(rounds["dg_id"], errors="coerce")
rounds["sg_total"] = pd.to_numeric(rounds["sg_total"], errors="coerce")
rounds["player_name"] = rounds["player_name"].astype(str)

rounds = rounds.dropna(subset=["round_date","dg_id","sg_total"]).copy()
rounds["dg_id"] = rounds["dg_id"].astype(int)

# stable name map from latest seen name per dg_id
name_map = (
    rounds.dropna(subset=["dg_id","player_name"])
          .sort_values(["dg_id","round_date"])
          .groupby("dg_id")["player_name"]
          .last()
          .to_dict()
)

rounds = rounds.sort_values(["dg_id","round_date"]).reset_index(drop=True)

def build_player_rolling_features(rounds_df: pd.DataFrame, windows=(40,24,12)) -> pd.DataFrame:
    df = rounds_df[["dg_id","round_date","sg_total"]].copy()
    df = df.sort_values(["dg_id","round_date"]).reset_index(drop=True)

    g = df.groupby("dg_id", group_keys=False)
    df["n_rounds_to_date"] = g.cumcount() + 1

    for w in windows:
        df[f"sg_total_L{w}"] = (
            g["sg_total"]
            .rolling(window=w, min_periods=min(10, w))
            .mean()
            .reset_index(level=0, drop=True)
        )
    return df

rounds_roll = build_player_rolling_features(rounds, windows=WINDOWS)

# IMPORTANT: merge_asof requires right "on" key sorted globally
rounds_roll = rounds_roll.dropna(subset=["round_date","dg_id"]).copy()
rounds_roll["round_date"] = _to_naive_datetime(rounds_roll["round_date"])
rounds_roll["dg_id"] = pd.to_numeric(rounds_roll["dg_id"], errors="coerce")
rounds_roll = rounds_roll.dropna(subset=["round_date","dg_id"]).copy()
rounds_roll["dg_id"] = rounds_roll["dg_id"].astype(int)
rounds_roll = rounds_roll.sort_values(["round_date","dg_id"]).reset_index(drop=True)

# ============================================================
# 4) BUILD MODELING TABLE X (player-event rows) with cutoff = start-1
# ============================================================
evs = sched_all.copy()
evs["cutoff_date"] = evs["event_start_date"] - pd.Timedelta(days=1)

# player-event table (from odds/results) + event meta
pe = odds.merge(
    evs[["year","event_id","event_start_date","cutoff_date","event_name"]],
    on=["year","event_id"],
    how="inner",
    suffixes=("", "_sched"),
).copy()

# ensure pe has a clean event_name
if "event_name_sched" in pe.columns:
    pe["event_name"] = pe["event_name_sched"].fillna(pe.get("event_name"))
pe["event_name"] = pe["event_name"].fillna("UNKNOWN_EVENT").astype(str)

# ensure player_name exists
pe["player_name"] = pe["dg_id"].map(name_map).fillna(pe["dg_id"].apply(lambda x: f"dg_{x}"))

# label
pe["y_win"] = (pe["finish_num"] == 1).astype(int)

# -----------------------------
# ASOF MERGE (robust)
#   Must be globally sorted by ON key, not by dg_id first.
# -----------------------------
left = pe.copy()
right = rounds_roll.copy()

left["cutoff_date"] = _to_naive_datetime(left["cutoff_date"])
right["round_date"] = _to_naive_datetime(right["round_date"])

left["dg_id"] = pd.to_numeric(left["dg_id"], errors="coerce")
right["dg_id"] = pd.to_numeric(right["dg_id"], errors="coerce")

left = left.dropna(subset=["dg_id","cutoff_date"]).copy()
right = right.dropna(subset=["dg_id","round_date"]).copy()

left["dg_id"] = left["dg_id"].astype(int)
right["dg_id"] = right["dg_id"].astype(int)

# CRITICAL: sort by ON then BY
left  = left.sort_values(["cutoff_date","dg_id"]).reset_index(drop=True)
right = right.sort_values(["round_date","dg_id"]).reset_index(drop=True)

try:
    X = pd.merge_asof(
        left,
        right,
        by="dg_id",
        left_on="cutoff_date",
        right_on="round_date",
        direction="backward",
        allow_exact_matches=True,
    )
except ValueError as e:
    # fallback per-player (slower, but guaranteed)
    print("merge_asof failed; falling back per dg_id. Error:", e)
    parts = []
    right_g = right.sort_values(["dg_id","round_date"])
    left_g  = left.sort_values(["dg_id","cutoff_date"])
    for pid, lsub in left_g.groupby("dg_id", sort=False):
        rsub = right_g[right_g["dg_id"] == pid]
        if rsub.empty:
            lsub2 = lsub.copy()
            for c in right.columns:
                if c not in lsub2.columns:
                    lsub2[c] = np.nan
            parts.append(lsub2)
        else:
            merged = pd.merge_asof(
                lsub.sort_values("cutoff_date"),
                rsub.sort_values("round_date"),
                left_on="cutoff_date",
                right_on="round_date",
                direction="backward",
                allow_exact_matches=True,
            )
            parts.append(merged)
    X = pd.concat(parts, ignore_index=True)

# keep last matched round date so we can compute inactivity
X = X.rename(columns={"round_date": "last_round_date"})

# ensure X has event_name (belt + suspenders)
if "event_name" not in X.columns:
    for cand in ["event_name_sched", "event_name_x", "event_name_y"]:
        if cand in X.columns:
            X["event_name"] = X[cand]
            break
    if "event_name" not in X.columns:
        X["event_name"] = "UNKNOWN_EVENT"

# ensure player_name exists in X (belt + suspenders)
if "player_name" not in X.columns:
    X["player_name"] = X["dg_id"].map(name_map).fillna(X["dg_id"].apply(lambda x: f"dg_{x}"))

# -----------------------------
# Derived features
# -----------------------------
X["days_since_last_round"] = (pd.to_datetime(X["cutoff_date"]) - pd.to_datetime(X["last_round_date"])).dt.days
X["days_since_last_round"] = pd.to_numeric(X["days_since_last_round"], errors="coerce").clip(lower=0)
X["days_since_last_round_log1p"] = np.log1p(X["days_since_last_round"].fillna(0.0))

# recency shape
X["sg_total_L12_minus_L40"] = X["sg_total_L12"] - X["sg_total_L40"]
X["sg_total_L24_minus_L40"] = X["sg_total_L24"] - X["sg_total_L40"]

# odds feature: implied prob share within event (logit, scaled)
X["p_odds_raw"] = 1.0 / pd.to_numeric(X["close_odds"], errors="coerce")
X["p_odds_raw"] = X["p_odds_raw"].replace([np.inf, -np.inf], np.nan)
X["p_odds_raw"] = X["p_odds_raw"].fillna(X["p_odds_raw"].median())

X["p_odds_share"] = X["p_odds_raw"] / (X.groupby(["year","event_id"])["p_odds_raw"].transform("sum") + 1e-12)
X["odds_logit_scaled"] = ODDS_SCALE * _logit(X["p_odds_share"].values)
# cap odds share to avoid extreme logits
X["p_odds_share_capped"] = X["p_odds_share"].clip(0.0005, 0.20)
X["odds_logit_scaled"] = ODDS_SCALE * _logit(X["p_odds_share_capped"].values)

# Feature sets
BASE_FEATS  = [f"sg_total_L{w}" for w in WINDOWS] + ["odds_logit_scaled"]
TREND_FEATS = ["sg_total_L12_minus_L40", "sg_total_L24_minus_L40"]
LAYOFF_FEATS = ["days_since_last_round_log1p"]

FEAT_SETS = {
    "baseline": BASE_FEATS,
    "baseline_plus_trend": BASE_FEATS + TREND_FEATS,
    "baseline_plus_layoff": BASE_FEATS + LAYOFF_FEATS,
    "baseline_plus_both": BASE_FEATS + TREND_FEATS + LAYOFF_FEATS,
}

if FEAT_SET_KEY not in FEAT_SETS:
    raise ValueError(f"Unknown FEAT_SET_KEY={FEAT_SET_KEY}. Choose from {list(FEAT_SETS.keys())}")

FEATS = FEAT_SETS[FEAT_SET_KEY]

# require rolling sg features + the chosen feature set + label
X = X.dropna(subset=[f"sg_total_L{w}" for w in WINDOWS]).copy()
X = X.dropna(subset=FEATS + ["y_win", "finish_num", "event_start_date", "event_id", "year"]).copy()

# make sure types are clean
X["year"] = pd.to_numeric(X["year"], errors="coerce").astype(int)
X["event_id"] = pd.to_numeric(X["event_id"], errors="coerce").astype(int)
X["event_start_date"] = _to_naive_datetime(X["event_start_date"])

print("X rows:", len(X), "| years:", sorted(X["year"].unique().tolist())[:10], "| feat_set:", FEAT_SET_KEY)
display(X[["year","event_id","event_name","dg_id","player_name","finish_num","y_win"] + FEATS].head(10))

# ============================================================
# 5) WALK-FORWARD BACKTEST (2025)
# ============================================================
def fit_lr(train_df: pd.DataFrame, feat_cols, label_col="y_win"):
    tr = train_df.dropna(subset=feat_cols + [label_col]).copy()
    ytr = tr[label_col].astype(int).values
    if np.unique(ytr).size < 2:
        return None
    m = LogisticRegression(C=LR_C, max_iter=LR_MAX_ITER, solver="lbfgs")
    m.fit(tr[feat_cols].values, ytr)
    return m

event_boards = []
event_summ = []

bt_events = sched_bt.copy()
print("2025 events to score:", len(bt_events))

for _, ev in bt_events.iterrows():
    ev_id = int(ev["event_id"])
    ev_date = pd.to_datetime(ev["event_start_date"])
    ev_name = str(ev["event_name"])

    train_df = X[
        (X["year"] < BACKTEST_YEAR) |
        ((X["year"] == BACKTEST_YEAR) & (X["event_start_date"] < ev_date))
    ].copy()

    test_df = X[(X["year"] == BACKTEST_YEAR) & (X["event_id"] == ev_id)].copy()

    if train_df.empty or test_df.empty:
        continue

    model = fit_lr(train_df, FEATS, label_col="y_win")
    if model is None:
        continue

    p = model.predict_proba(test_df[FEATS].values)[:, 1]
    test_df = test_df.copy()
    test_df["p_win_raw"] = p
    test_df["p_win_share"] = test_df["p_win_raw"] / (test_df["p_win_raw"].sum() + 1e-12)

    board = test_df[[
        "year","event_id","event_start_date","event_name",
        "dg_id","player_name","finish_num","y_win",
        "p_win_raw","p_win_share",
        "sg_total_L40","sg_total_L24","sg_total_L12",
        "close_odds","p_odds_share"
    ]].copy()

    board = board.sort_values("p_win_share", ascending=False).reset_index(drop=True)
    board["pred_rank"] = np.arange(1, len(board) + 1)

    eval_board = board.dropna(subset=["finish_num"]).copy()

    winner_rows = eval_board[eval_board["finish_num"] == 1]
    winner_rank = int(winner_rows["pred_rank"].iloc[0]) if not winner_rows.empty else np.nan

    spearman = _spearman_rank_corr(eval_board["pred_rank"], eval_board["finish_num"])

    top_group = eval_board.head(TOP_GROUP_N).copy()
    top_group_mean_finish = float(top_group["finish_num"].mean()) if len(top_group) else np.nan
    top_group_median_finish = float(top_group["finish_num"].median()) if len(top_group) else np.nan
    top_group_top10_rate = float((top_group["finish_num"] <= REL_HIGH_FINISH).mean()) if len(top_group) else np.nan

    win_in_topk = {f"winner_in_top{K}": (winner_rank <= K) if np.isfinite(winner_rank) else np.nan for K in TOPK_LIST}

    y_true = eval_board["y_win"].values
    y_prob = eval_board["p_win_raw"].values
    brier = brier_score_loss(y_true, y_prob)
    auc = safe_auc(y_true, y_prob)


    event_summ.append({
        "year": BACKTEST_YEAR,
        "event_id": ev_id,
        "event_name": ev_name,
        "event_date": ev_date,
        "n_field": int(len(board)),
        "winner_pred_rank": winner_rank,
        "spearman_predrank_vs_finish": spearman,
        "top_group_n": TOP_GROUP_N,
        "top_group_mean_finish": top_group_mean_finish,
        "top_group_median_finish": top_group_median_finish,
        f"top_group_top{REL_HIGH_FINISH}_rate": top_group_top10_rate,
        "brier": float(brier),
        "auc": float(auc) if np.isfinite(auc) else np.nan,
        **win_in_topk,
    })

    event_boards.append(board)

    top10 = board.head(10).copy()
    top10["p_win_pct"] = (100 * top10["p_win_share"]).round(2)
    top10["p_odds_pct"] = (100 * top10["p_odds_share"]).round(2)

    print(f"\n=== {ev_date.date()} | event_id={ev_id} | {ev_name} ===")
    display(top10[[
        "pred_rank","player_name","dg_id",
        "p_win_pct","p_odds_pct","close_odds",
        "sg_total_L40","sg_total_L24","sg_total_L12",
        "finish_num"
    ]])

boards_2025 = pd.concat(event_boards, ignore_index=True) if event_boards else pd.DataFrame()
summ_2025 = pd.DataFrame(event_summ).sort_values("event_date").reset_index(drop=True)

print("\nEvents scored:", summ_2025["event_id"].nunique() if not summ_2025.empty else 0)
display(summ_2025.head(50))

# ============================================================
# 6) AGGREGATE RESULTS
# ============================================================
if not summ_2025.empty:
    agg = {
        "events": int(summ_2025["event_id"].nunique()),
        "avg_spearman_predrank_vs_finish": float(summ_2025["spearman_predrank_vs_finish"].mean()),
        f"avg_top{REL_HIGH_FINISH}_rate_in_top{TOP_GROUP_N}":
            float(summ_2025[f"top_group_top{REL_HIGH_FINISH}_rate"].mean()),
        "avg_top_group_mean_finish": float(summ_2025["top_group_mean_finish"].mean()),
        "avg_winner_pred_rank": float(summ_2025["winner_pred_rank"].mean()),
        "avg_brier": float(summ_2025["brier"].mean()),
        "avg_auc": float(summ_2025["auc"].mean()),
        "feat_set": FEAT_SET_KEY,
        "lr_c": LR_C,
        "odds_scale": ODDS_SCALE,
    }
    for K in TOPK_LIST:
        col = f"winner_in_top{K}"
        agg[col] = float(pd.to_numeric(summ_2025[col], errors="coerce").mean())
    display(pd.DataFrame([agg]))

# ============================================================
# 7) OPTIONAL: PLAYER SUMMARY ACROSS 2025
# ============================================================
if not boards_2025.empty:
    player_2025 = (
        boards_2025.groupby(["dg_id","player_name"], as_index=False)
        .agg(
            starts=("event_id","nunique"),
            wins=("y_win","sum"),
            avg_pwin_share=("p_win_share","mean"),
            max_pwin_share=("p_win_share","max"),
            avg_pred_rank=("pred_rank","mean"),
        )
        .sort_values(["wins","avg_pwin_share","starts"], ascending=[False, False, False])
        .reset_index(drop=True)
    )
    display(player_2025.head(50))

print("\nDone.")
print("To try trend/layoff features, only change FEAT_SET_KEY at the top.")

Backtest events: 31

    event_id event_start_date                     event_name
0          6       2025-01-12            Sony Open in Hawaii
1          2       2025-01-19           The American Express
2          4       2025-01-25         Farmers Insurance Open
3          5       2025-02-02       AT&T Pebble Beach Pro-Am
4          3       2025-02-09                WM Phoenix Open
5          7       2025-02-16           Genesis Invitational
6        540       2025-02-23                    Mexico Open
7         10       2025-03-02              Cognizant Classic
8          9       2025-03-09     Arnold Palmer Invitational
9         11       2025-03-16       The Players Championship
10       475       2025-03-23           Valspar Championship
11        20       2025-03-30  Texas Children's Houston Open
12        41       2025-04-06              Valero Texas Open
13        14       2025-04-13             Masters Tournament
14        12       2025-04-20                   RBC Heritage
15        19       2025-05-04            CJ Cup Byron Nelson
16       480       2025-05-11            Truist Championship
17        33       2025-05-18               PGA Championship
18        21       2025-05-25       Charles Schwab Challenge
19        23       2025-06-01            Memorial Tournament
20        32       2025-06-08              RBC Canadian Open
21        26       2025-06-15                      U.S. Open
22        34       2025-06-22         Travelers Championship
23       524       2025-06-29                 Rocket Classic
24        30       2025-07-06             John Deere Classic

/var/folders/85/gv9dnstn1tn96gql2f7mj15h0000gn/T/ipykernel_48884/1857285996.py:163: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  rounds = pd.read_csv(ROUNDS_PATH)

X rows: 4410 | years: [2024, 2025, 2026] | feat_set: baseline_plus_layoff

,year,event_id,event_name,dg_id,player_name,finish_num,y_win,sg_total_L40,sg_total_L24,sg_total_L12,odds_logit_scaled,days_since_last_round_log1p
0,2024,6,Sony Open in Hawaii,5665,"Cink, Stewart",24.0,0,0.440450,0.670833,1.082750,-0.854154,0.0
1,2024,6,Sony Open in Hawaii,5768,"Hoffman, Charley",42.0,0,0.089275,0.217375,0.499417,-0.914892,0.0
2,2024,6,Sony Open in Hawaii,6093,"Rose, Justin",57.0,0,0.382300,-0.179958,0.406417,-0.570962,0.0
8,2024,6,Sony Open in Hawaii,7960,"List, Luke",66.0,0,1.069700,1.030375,0.981667,-0.717076,0.0
13,2024,6,Sony Open in Hawaii,8825,"Harman, Brian",18.0,0,1.421575,0.800875,1.248500,-0.495409,0.0
16,2024,6,Sony Open in Hawaii,10104,"Power, Seamus",74.0,0,-0.299025,-0.964542,-1.964917,-0.811083,0.0
17,2024,6,Sony Open in Hawaii,10419,"Noren, Alex",42.0,0,1.116475,1.342375,2.162000,-0.646940,0.0
21,2024,6,Sony Open in Hawaii,11049,"Simpson, Webb",66.0,0,-0.223100,-0.223292,0.067083,-0.811083,0.0
22,2024,6,Sony Open in Hawaii,11276,"Horschel, Billy",18.0,0,0.984525,1.559292,1.119583,-0.707435,0.0
24,2024,6,Sony Open in Hawaii,12359,"Stallings, Scott",42.0,0,-0.346675,0.208250,0.531083,-0.887576,0.0

2025 events to score: 31

=== 2025-01-12 | event_id=6 | Sony Open in Hawaii ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"McNealy, Maverick",18634,6.20,2.63,26.0,1.370050,1.823542,2.361667,45.0
1,2,"Matsuyama, Hideki",13562,5.13,6.83,10.0,1.691775,2.075958,1.738833,16.0
2,3,"Hall, Harry",27194,4.73,1.34,51.0,1.482650,1.523208,2.060083,10.0
3,4,"Fishburn, Patrick",25094,4.39,0.75,91.0,1.670375,1.078833,2.155667,6.0
4,5,"Kim, Tom",24766,3.75,3.25,21.0,1.091450,1.224083,1.990500,65.0
5,6,"Echavarria, Nico",22833,3.74,0.75,91.0,1.275175,1.745875,1.611667,2.0
6,7,"Glover, Lucas",7399,3.47,0.84,81.0,1.008600,1.795625,1.555667,21.0
7,8,"Kitayama, Kurt",21891,3.20,1.90,36.0,0.903300,1.755125,1.470167,37.0
8,9,"Pendrith, Taylor",17780,3.00,1.90,36.0,1.137175,1.181708,1.634167,45.0
9,10,"Lower, Justin",17723,2.62,0.56,121.0,0.805650,0.920667,1.722250,37.0

=== 2025-01-19 | event_id=2 | The American Express ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Greyserman, Max",23465,5.64,2.16,31.0,1.766450,1.499542,2.268667,7.0
1,2,"Griffin, Ben",24968,3.99,1.19,56.0,1.168000,1.511542,1.893000,7.0
2,3,"Hall, Harry",27194,3.92,1.63,41.0,1.490075,1.474708,1.758917,21.0
3,4,"Thomas, Justin",14139,3.82,5.14,13.0,1.115800,1.452625,1.844750,2.0
4,5,"Hubbard, Mark",16333,3.75,0.73,91.0,0.744475,1.526375,1.941500,12.0
5,6,"Straka, Sepp",17511,3.11,1.19,56.0,0.362275,1.283000,1.907583,1.0
6,7,"Fowler, Rickie",12965,2.75,0.83,81.0,0.420600,0.785708,1.985583,21.0
7,8,"Berger, Daniel",17606,2.71,0.88,76.0,0.856550,1.323667,1.468667,21.0
8,9,"Highsmith, Joe",28469,2.69,0.60,111.0,1.062025,1.516250,1.268833,66.0
9,10,"Spaun, J.J.",17536,2.61,1.19,56.0,1.177100,1.323958,1.279750,29.0

=== 2025-01-25 | event_id=4 | Farmers Insurance Open ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Matsuyama, Hideki",13562,9.61,5.69,12.0,1.604600,1.917708,2.558167,32.0
1,2,"Greyserman, Max",23465,4.23,2.63,26.0,1.713325,1.779208,1.241000,48.0
2,3,"Aberg, Ludvig",23950,3.88,6.83,10.0,0.910200,1.171625,1.708250,42.0
3,4,"Im, Sungjae",17488,3.58,3.59,19.0,1.175575,1.241875,1.457833,4.0
4,5,"Clanton, Luke",32330,2.65,1.48,46.0,1.432057,1.204083,0.922833,15.0
5,6,"Hodges, Lee",25157,2.60,0.68,101.0,0.230200,1.178542,1.306833,9.0
6,7,"Hubbard, Mark",16333,2.54,0.84,81.0,0.644900,1.171083,1.140167,68.0
7,8,"Bradley, Keegan",13872,2.53,2.63,26.0,0.609200,0.987292,1.236167,15.0
8,9,"Griffin, Lanto",15330,2.52,0.34,201.0,0.525275,0.693542,1.470917,9.0
9,10,"Hossler, Beau",15470,2.50,1.48,46.0,0.941675,1.155792,1.016333,15.0

=== 2025-02-02 | event_id=5 | AT&T Pebble Beach Pro-Am ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"McIlroy, Rory",10091,11.51,5.21,13.0,1.838275,2.686750,3.259417,1.0
1,2,"Scheffler, Scottie",18417,8.17,13.55,5.0,2.401225,2.273792,2.692917,9.0
2,3,"Straka, Sepp",17511,3.95,1.11,61.0,0.841275,1.450542,2.496167,7.0
3,4,"Hojgaard, Rasmus",23838,3.64,1.11,61.0,1.934850,1.575500,1.926083,22.0
4,5,"Lowry, Shane",13900,3.49,1.21,56.0,1.369775,1.649375,1.985667,2.0
5,6,"Im, Sungjae",17488,2.64,2.61,26.0,1.219250,1.408083,1.701583,33.0
6,7,"Thomas, Justin",14139,2.52,4.52,15.0,1.104575,1.974167,1.277250,48.0
7,8,"Morikawa, Collin",22085,2.34,4.52,15.0,1.367500,1.226083,1.557917,17.0
8,9,"Kim, Tom",24766,2.30,1.33,51.0,1.316775,1.209708,1.577750,7.0
9,10,"Davis, Cam",17786,2.22,0.74,91.0,0.848950,0.922542,1.868750,5.0

=== 2025-02-09 | event_id=3 | WM Phoenix Open ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,11.28,18.25,3.75,2.273150,2.340917,2.704250,25.0
1,2,"Straka, Sepp",17511,6.06,1.67,41.00,0.983700,1.656292,2.527750,15.0
2,3,"Thomas, Justin",14139,5.16,4.56,15.00,1.155725,1.938167,2.004083,6.0
3,4,"Hojgaard, Rasmus",23838,4.74,1.34,51.00,1.732675,1.810375,1.799167,12.0
4,5,"Im, Sungjae",17488,3.05,2.63,26.00,1.022200,1.501833,1.483917,57.0
5,6,"Detry, Thomas",14181,2.97,0.84,81.00,0.722050,1.197542,1.752583,1.0
6,7,"Woo Lee, Min",16841,2.74,1.04,66.00,0.905600,1.208625,1.560583,12.0
7,8,"Matsuyama, Hideki",13562,2.42,4.03,17.00,1.515225,1.386292,1.033750,25.0
8,9,"Woodland, Gary",12577,2.19,0.75,91.00,0.844550,1.022458,1.342667,21.0
9,10,"MacIntyre, Robert",23323,2.07,1.22,56.00,1.101625,0.943542,1.225000,6.0

=== 2025-02-16 | event_id=7 | Genesis Invitational ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"McIlroy, Rory",10091,14.68,9.41,7.5,2.160100,2.500500,2.826833,17.0
1,2,"Scheffler, Scottie",18417,7.57,14.11,5.0,2.240350,1.840875,2.110000,3.0
2,3,"Thomas, Justin",14139,4.76,3.71,19.0,1.263450,1.771667,1.698583,9.0
3,4,"Lowry, Shane",13900,3.98,1.53,46.0,1.495500,1.649875,1.445917,39.0
4,5,"Fleetwood, Tommy",12294,3.93,1.96,36.0,1.421950,1.693583,1.410167,5.0
5,6,"Morikawa, Collin",22085,3.06,4.15,17.0,1.159050,1.220792,1.381083,17.0
6,7,"Berger, Daniel",17606,2.88,0.87,81.0,1.159100,0.970417,1.472917,12.0
7,8,"Detry, Thomas",14181,2.81,1.38,51.0,0.860250,1.347333,1.266917,53.0
8,9,"Cantlay, Patrick",15466,2.41,2.28,31.0,0.987375,0.680083,1.417250,5.0
9,10,"Matsuyama, Hideki",13562,2.41,3.07,23.0,1.655350,1.594792,0.631417,13.0

=== 2025-02-23 | event_id=540 | Mexico Open ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Kim, Michael",17543,5.34,2.55,26.0,1.163375,1.330958,1.717333,13.0
1,2,"Smalley, Alex",18474,5.07,1.84,36.0,1.126250,1.415667,1.596417,10.0
2,3,"Roy, Kevin",18424,3.74,1.09,61.0,0.604350,1.284958,1.344833,17.0
3,4,"Bhatia, Akshay",26096,3.42,4.42,15.0,0.414050,0.853375,1.504583,9.0
4,5,"Campbell, Brian",18628,3.35,0.33,201.0,1.179286,1.179286,1.111917,1.0
5,6,"Castillo, Ricky",27819,2.79,0.73,91.0,0.776474,0.776474,1.173750,55.0
6,7,"Potgieter, Aldrich",27900,2.35,1.30,51.0,0.010650,1.115917,0.874250,2.0
7,8,"Rodgers, Patrick",16283,2.33,2.88,23.0,0.630000,0.481042,1.090000,25.0
8,9,"Hojgaard, Nicolai",23602,2.32,1.62,41.0,0.611875,1.036417,0.745417,8.0
9,10,"Griffin, Lanto",15330,2.26,0.82,81.0,0.535900,0.723000,0.939917,25.0

=== 2025-03-02 | event_id=10 | Cognizant Classic ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Berger, Daniel",17606,5.24,2.55,26.0,1.224250,1.480542,1.933167,25.0
1,2,"Kim, Michael",17543,4.90,1.30,51.0,1.430850,1.243208,1.932500,6.0
2,3,"Campbell, Brian",18628,4.25,0.82,81.0,1.176278,1.176278,1.826167,48.0
3,4,"Smalley, Alex",18474,3.45,1.44,46.0,1.079700,1.281292,1.441167,18.0
4,5,"Knapp, Jake",19396,2.95,0.82,81.0,-0.341475,1.158833,1.682500,6.0
5,6,"Lowry, Shane",13900,2.87,3.16,21.0,1.448575,1.312625,1.012917,11.0
6,7,"Gerard, Ryan",29767,2.85,0.87,76.0,0.241775,1.348417,1.337417,25.0
7,8,"Griffin, Ben",24968,2.79,1.62,41.0,1.142400,0.747042,1.432500,4.0
8,9,"Henley, Russell",14578,2.72,2.55,26.0,1.024000,0.816375,1.376750,6.0
9,10,"Dahmen, Joel",14509,2.68,0.60,111.0,0.484425,0.806208,1.534667,32.0

=== 2025-03-09 | event_id=9 | Arnold Palmer Invitational ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"McIlroy, Rory",10091,11.46,8.04,8.5,2.311775,2.396458,2.390500,15.0
1,2,"Scheffler, Scottie",18417,7.27,17.10,4.0,2.195875,2.218667,1.744417,11.0
2,3,"Morikawa, Collin",22085,5.18,3.26,21.0,1.357475,1.765250,1.771417,2.0
3,4,"Kim, Michael",17543,5.17,1.22,56.0,1.533950,1.486792,1.917333,4.0
4,5,"Henley, Russell",14578,4.15,1.67,41.0,0.985825,1.470000,1.732917,1.0
5,6,"Thomas, Justin",14139,4.11,2.63,26.0,1.491625,1.427500,1.577750,36.0
6,7,"Fleetwood, Tommy",12294,3.33,2.36,29.0,1.498625,1.313125,1.307167,11.0
7,8,"Lowry, Shane",13900,3.17,1.49,46.0,1.574925,1.525958,1.066250,7.0
8,9,"Berger, Daniel",17606,3.00,1.34,51.0,1.099175,1.232000,1.326750,15.0
9,10,"Straka, Sepp",17511,2.92,1.34,51.0,1.286375,1.605208,0.972750,5.0

=== 2025-03-16 | event_id=11 | The Players Championship ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"McIlroy, Rory",10091,6.76,5.62,12.0,2.506925,2.524583,1.789750,1.0
1,2,"Scheffler, Scottie",18417,5.02,13.49,5.0,2.092550,2.168917,1.633583,20.0
2,3,"Smalley, Alex",18474,4.57,0.45,151.0,1.116575,1.752875,2.096750,14.0
3,4,"Straka, Sepp",17511,4.00,1.64,41.0,1.464925,1.909708,1.649583,14.0
4,5,"Spaun, J.J.",17536,3.99,0.67,101.0,1.258875,1.354250,2.094417,2.0
5,6,"Morikawa, Collin",22085,3.65,4.50,15.0,1.345500,1.632167,1.706417,10.0
6,7,"Henley, Russell",14578,3.49,1.87,36.0,1.008475,1.611333,1.761083,30.0
7,8,"Fleetwood, Tommy",12294,3.21,2.18,31.0,1.693775,1.316250,1.623083,14.0
8,9,"Berger, Daniel",17606,2.93,1.20,56.0,1.187075,1.492000,1.511083,20.0
9,10,"Knapp, Jake",19396,2.85,0.45,151.0,0.235400,1.195375,1.957167,12.0

=== 2025-03-23 | event_id=475 | Valspar Championship ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Neergaard-Petersen, Rasmus",23841,8.45,0.63,111.0,1.706750,1.776667,2.527583,22.0
1,2,"Lowry, Shane",13900,6.22,1.95,36.0,1.707475,1.571917,2.130917,8.0
2,3,"Conners, Corey",17576,5.30,1.95,36.0,0.917800,0.806458,2.682167,8.0
3,4,"Fleetwood, Tommy",12294,4.80,5.84,12.0,1.747200,1.546167,1.682167,16.0
4,5,"Bridgeman, Jacob",29433,4.08,1.37,51.0,1.067150,1.253125,1.880917,3.0
5,6,"Kim, Michael",17543,3.84,2.26,31.0,1.291025,1.744958,1.339333,28.0
6,7,"Highsmith, Joe",28469,3.59,1.25,56.0,1.156250,1.239500,1.650833,22.0
7,8,"Straka, Sepp",17511,3.53,4.12,17.0,1.423375,1.187750,1.547583,28.0
8,9,"Thomas, Justin",14139,2.92,3.34,21.0,1.717200,1.357042,1.015500,2.0
9,10,"Glover, Lucas",7399,2.70,1.15,61.0,0.979650,1.051250,1.377917,8.0

=== 2025-03-30 | event_id=20 | Texas Children's Houston Open ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"McIlroy, Rory",10091,10.97,8.64,7.5,2.405000,2.365833,1.904833,5.0
1,2,"Scheffler, Scottie",18417,10.22,14.39,4.5,2.100650,2.090750,2.071500,2.0
2,3,"Woo Lee, Min",16841,5.84,1.80,36.0,1.228475,1.261750,2.040167,1.0
3,4,"Kim, Michael",17543,4.50,1.80,36.0,1.214725,1.420583,1.487250,32.0
4,5,"Jaeger, Stephan",16394,2.85,1.41,46.0,0.766325,0.834583,1.298750,11.0
5,6,"Ryder, Sam",16715,2.82,0.58,111.0,0.894975,0.817792,1.261833,61.0
6,7,"Fox, Ryan",11889,2.63,0.58,111.0,0.662025,0.774750,1.258833,15.0
7,8,"Hodges, Lee",25157,2.21,0.71,91.0,0.949775,1.004083,0.701333,11.0
8,9,"Thompson, Davis",27364,1.93,1.80,36.0,0.570725,0.675333,0.818750,27.0
9,10,"Knapp, Jake",19396,1.91,0.85,76.0,0.497350,0.971875,0.626500,27.0

=== 2025-04-06 | event_id=41 | Valero Texas Open ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Conners, Corey",17576,6.74,3.89,17.0,1.194675,1.238292,2.148833,18.0
1,2,"Fleetwood, Tommy",12294,6.01,3.89,17.0,1.621275,1.478000,1.648833,62.0
2,3,"Cauley, Bud",14502,5.38,1.44,46.0,1.053725,1.221667,1.853333,5.0
3,4,"McCarthy, Denny",19870,4.54,2.28,29.0,0.887950,1.275667,1.580917,18.0
4,5,"Cantlay, Patrick",15466,4.32,3.48,19.0,0.956500,1.399708,1.382167,33.0
5,6,"Berger, Daniel",17606,3.60,2.13,31.0,1.109800,1.465375,0.997583,30.0
6,7,"Bradley, Keegan",13872,3.54,2.87,23.0,0.721300,0.807833,1.548833,47.0
7,8,"Valimaki, Sami",23816,3.27,0.60,111.0,-0.140850,0.749083,1.777500,12.0
8,9,"Hisatsune, Ryo",22760,2.79,0.55,121.0,0.549775,0.701208,1.325250,5.0
9,10,"Fisk, Steven",26657,2.48,0.44,151.0,0.234000,0.631333,1.288250,33.0

=== 2025-04-13 | event_id=14 | Masters Tournament ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"McIlroy, Rory",10091,15.43,9.38,7.5,2.546450,2.796375,3.202250,1.0
1,2,"Scheffler, Scottie",18417,7.28,14.06,5.0,2.050675,2.098333,2.452250,4.0
2,3,"Morikawa, Collin",22085,6.30,4.14,17.0,1.484750,1.944875,2.508667,14.0
3,4,"DeChambeau, Bryson",19841,5.67,3.91,18.0,1.901650,1.787917,2.309500,5.0
4,5,"Conners, Corey",17576,4.82,1.26,56.0,1.187575,1.818083,2.252583,8.0
5,6,"Rahm, Jon",19195,4.44,4.69,15.0,2.353275,1.811375,1.726167,14.0
6,7,"Lowry, Shane",13900,4.11,1.95,36.0,1.640275,1.545792,2.025333,42.0
7,8,"Niemann, Joaquin",18079,3.33,2.27,31.0,1.527450,1.740417,1.559500,29.0
8,9,"Woo Lee, Min",16841,2.39,1.38,51.0,1.218175,1.091833,1.579500,49.0
9,10,"McCarthy, Denny",19870,2.39,0.47,151.0,0.879000,1.188792,1.634167,29.0

=== 2025-04-20 | event_id=12 | RBC Heritage ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,10.49,14.72,4.6,2.286800,2.067875,2.502167,8.0
1,2,"Thomas, Justin",14139,4.63,3.22,21.0,1.409025,1.521083,1.825250,1.0
2,3,"Henley, Russell",14578,3.93,2.60,26.0,1.089000,1.431500,1.724500,8.0
3,4,"Lowry, Shane",13900,3.05,2.33,29.0,1.368100,1.293167,1.325250,18.0
4,5,"Conners, Corey",17576,2.69,2.94,23.0,0.746125,1.810208,0.938250,49.0
5,6,"Hovland, Viktor",18841,2.58,2.18,31.0,0.548875,0.293792,2.039667,13.0
6,7,"McNealy, Maverick",18634,2.52,1.11,61.0,0.729025,0.730917,1.642500,3.0
7,8,"Berger, Daniel",17606,2.41,1.47,46.0,1.224375,1.264250,1.017417,3.0
8,9,"Morikawa, Collin",22085,2.38,5.64,12.0,1.380000,1.322458,0.873500,54.0
9,10,"Gerard, Ryan",29767,2.29,0.56,121.0,0.967325,0.940500,1.273833,27.0

=== 2025-05-04 | event_id=19 | CJ Cup Byron Nelson ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,24.14,17.89,3.8,2.487625,2.669500,3.267500,1.0
1,2,"Rosenmueller, Thomas",22736,2.91,0.34,201.0,0.149175,0.684208,1.928667,52.0
2,3,"Thorbjornsen, Michael",26649,2.67,1.03,66.0,0.407575,0.656167,1.703083,33.0
3,4,"Im, Sungjae",17488,2.63,2.62,26.0,0.693100,0.725708,1.517500,33.0
4,5,"Spieth, Jordan",14636,2.55,3.58,19.0,0.427900,1.063958,1.305417,4.0
5,6,"Whaley, Vince",25908,2.51,0.61,111.0,0.462675,0.844792,1.459167,15.0
6,7,"Norlander, Henrik",11657,2.48,0.75,91.0,0.571300,1.094458,1.221583,45.0
7,8,"Hoey, Rico",23504,2.40,0.89,76.0,0.352875,0.989875,1.309917,52.0
8,9,"Walker, Danny",25003,2.20,0.40,171.0,0.642875,0.602458,1.375667,25.0
9,10,"Valimaki, Sami",23816,2.20,0.84,81.0,0.541725,0.935458,1.149583,39.0

=== 2025-05-11 | event_id=480 | Truist Championship ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"McIlroy, Rory",10091,12.66,13.61,5.0,2.460975,2.102750,2.300667,7.0
1,2,"Thomas, Justin",14139,6.90,4.00,17.0,1.755975,1.508500,2.001500,2.0
2,3,"Mitchell, Keith",17365,5.25,1.22,56.0,1.124950,1.427875,1.863833,7.0
3,4,"Straka, Sepp",17511,5.00,1.66,41.0,1.290275,1.591583,1.606750,1.0
4,5,"Berger, Daniel",17606,3.50,1.66,41.0,1.367525,1.162292,1.327000,11.0
5,6,"Spieth, Jordan",14636,3.26,2.62,26.0,0.970825,1.109000,1.382083,34.0
6,7,"Im, Sungjae",17488,2.61,1.48,46.0,0.562425,0.833833,1.382083,23.0
7,8,"Conners, Corey",17576,2.48,2.19,31.0,0.882450,1.446250,0.743667,11.0
8,9,"Novak, Andrew",23475,2.47,1.22,56.0,0.745850,0.775583,1.283000,17.0
9,10,"Fleetwood, Tommy",12294,2.40,2.62,26.0,1.251275,1.196250,0.743667,4.0

=== 2025-05-18 | event_id=33 | PGA Championship ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,22.11,13.59,5.25,2.762650,3.198625,3.945000,1.0
1,2,"DeChambeau, Bryson",19841,13.82,7.13,10.00,2.025575,2.614042,3.632750,2.0
2,3,"Rahm, Jon",19195,8.52,3.75,19.00,2.270750,2.322375,2.882750,8.0
3,4,"Niemann, Joaquin",18079,3.94,2.30,31.00,1.800000,2.030708,1.966083,8.0
4,5,"Penge, Marco",22465,3.72,0.10,701.00,1.699700,1.918750,2.053417,28.0
5,6,"Puig, David",28984,2.57,0.39,181.00,2.006750,1.734708,1.466333,60.0
6,7,"McIlroy, Rory",10091,2.55,11.89,6.00,2.204825,2.118833,1.035417,47.0
7,8,"Hatton, Tyrrell",14796,1.92,1.55,46.00,1.597800,1.030708,1.632750,60.0
8,9,"Berger, Daniel",17606,1.82,0.71,101.00,1.397450,1.287333,1.440500,33.0
9,10,"Fleetwood, Tommy",12294,1.77,1.55,46.00,1.255025,1.054875,1.607167,41.0

=== 2025-05-25 | event_id=21 | Charles Schwab Challenge ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,31.17,19.67,3.4,2.650450,3.203625,3.905083,4.0
1,2,"Schmid, Matti",20722,3.27,0.39,171.0,0.723925,1.144292,2.180500,2.0
2,3,"Griffin, Ben",24968,3.05,1.10,61.0,1.119200,1.266875,1.828417,1.0
3,4,"Hall, Harry",27194,2.90,0.94,71.0,0.839525,1.348333,1.787417,6.0
4,5,"Gotterup, Chris",27774,2.48,0.44,151.0,0.737900,1.304208,1.627250,28.0
5,6,"Fleetwood, Tommy",12294,2.42,2.57,26.0,1.327800,1.127750,1.483917,4.0
6,7,"Kim, Si Woo",14609,2.41,1.63,41.0,1.020500,1.086792,1.623833,28.0
7,8,"Poston, J.T.",21554,2.26,1.63,41.0,0.667950,0.938042,1.749250,36.0
8,9,"Olesen, Thorbjorn",13412,2.19,0.94,71.0,0.793675,1.353333,1.370750,46.0
9,10,"Hubbard, Mark",16333,2.10,0.44,151.0,-0.120450,1.321792,1.650000,28.0

=== 2025-06-01 | event_id=23 | Memorial Tournament ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,34.46,18.51,3.8,2.784375,3.480458,3.693417,1.0
1,2,"Griffin, Ben",24968,7.12,1.26,56.0,1.163825,1.493417,2.834000,2.0
2,3,"Straka, Sepp",17511,4.10,1.72,41.0,1.281050,1.182125,2.139083,3.0
3,4,"Thomas, Justin",14139,2.92,3.70,19.0,1.282100,1.877917,1.095750,31.0
4,5,"Conners, Corey",17576,2.91,2.43,29.0,1.370325,1.235042,1.531833,25.0
5,6,"Fleetwood, Tommy",12294,2.87,2.71,26.0,1.303425,1.163833,1.584000,16.0
6,7,"Spieth, Jordan",14636,2.42,1.95,36.0,1.140475,1.290875,1.290583,7.0
7,8,"Schauffele, Xander",19895,2.40,4.14,17.0,0.529025,1.095208,1.615167,25.0
8,9,"Lowry, Shane",13900,2.34,1.95,36.0,1.146425,1.100875,1.377333,23.0
9,10,"Bradley, Keegan",13872,2.16,1.53,46.0,0.902900,1.066125,1.365167,7.0

=== 2025-06-08 | event_id=32 | RBC Canadian Open ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Fox, Ryan",11889,5.99,1.13,61.0,0.908100,1.252458,1.986000,1.0
1,2,"Hall, Harry",27194,5.20,1.67,41.0,0.927425,1.296208,1.721750,24.0
2,3,"Smalley, Alex",18474,4.31,1.13,61.0,0.996200,0.846542,1.755833,13.0
3,4,"Conners, Corey",17576,4.01,3.27,21.0,1.591050,1.018208,1.292750,27.0
4,5,"Olesen, Thorbjorn",13412,3.66,1.35,51.0,0.883900,1.395625,1.138417,36.0
5,6,"Burns, Sam",19483,3.53,2.37,29.0,0.552300,1.254083,1.292750,2.0
6,7,"Lowry, Shane",13900,3.53,2.98,23.0,1.200350,0.774208,1.416000,13.0
7,8,"McCarty, Matt",28635,3.51,0.75,91.0,0.674000,1.117667,1.364583,4.0
8,9,"Hubbard, Mark",16333,3.47,0.85,81.0,-0.005850,1.357583,1.402500,47.0
9,10,"Yu, Kevin",17881,3.46,0.97,71.0,0.883950,1.021542,1.339167,3.0

=== 2025-06-15 | event_id=26 | U.S. Open ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,17.22,19.76,3.75,2.980350,3.390333,2.835667,7.0
1,2,"Burns, Sam",19483,9.35,0.91,81.00,1.160850,2.262542,3.225667,7.0
2,3,"Griffin, Ben",24968,6.74,0.98,76.00,1.146550,1.837875,3.002333,10.0
3,4,"Rahm, Jon",19195,6.01,5.70,13.00,2.079925,2.200375,2.213083,7.0
4,5,"Neergaard-Petersen, Rasmus",23841,3.97,0.37,201.00,2.008175,2.139875,1.691833,12.0
5,6,"Ortiz, Carlos",14735,3.53,0.37,201.00,0.989575,1.742917,2.135583,4.0
6,7,"Taylor, Nick",13126,2.34,0.43,171.00,0.698775,1.089375,2.081500,23.0
7,8,"Spaun, J.J.",17536,2.25,0.61,121.00,1.216550,0.949417,1.948500,1.0
8,9,"Fox, Ryan",11889,2.17,0.67,111.00,1.001950,1.510125,1.559000,19.0
9,10,"Grillo, Emiliano",12808,2.14,0.18,401.00,0.815475,1.244917,1.818583,19.0

=== 2025-06-22 | event_id=34 | Travelers Championship ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,22.59,18.10,4.0,2.963450,3.346417,2.787750,6.0
1,2,"Burns, Sam",19483,5.72,2.01,36.0,1.194075,1.817458,2.213167,17.0
2,3,"Fleetwood, Tommy",12294,5.44,2.01,36.0,1.491300,1.825250,2.032917,2.0
3,4,"Griffin, Ben",24968,5.05,1.42,51.0,1.279775,1.891417,1.954417,14.0
4,5,"Bradley, Keegan",13872,4.30,2.01,36.0,1.305675,1.514417,1.955083,1.0
5,6,"Henley, Russell",14578,4.17,1.77,41.0,1.302800,1.171625,2.144250,2.0
6,7,"Fox, Ryan",11889,3.34,0.72,101.0,1.031300,1.607583,1.629833,17.0
7,8,"Young, Cameron",26651,2.89,1.42,51.0,0.501025,1.164167,1.879833,52.0
8,9,"Hall, Harry",27194,2.55,0.80,91.0,1.136375,1.288125,1.415000,9.0
9,10,"MacIntyre, Robert",23323,2.53,1.77,41.0,0.688600,1.398583,1.463167,17.0

=== 2025-06-29 | event_id=524 | Rocket Classic ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Griffin, Ben",24968,7.46,3.02,23.0,1.580350,2.288833,1.743667,13.0
1,2,"Hall, Harry",27194,6.06,2.24,31.0,1.341725,1.811125,1.834833,13.0
2,3,"Greyserman, Max",23465,3.67,1.93,36.0,0.700300,1.288833,1.660333,2.0
3,4,"Bradley, Keegan",13872,3.64,3.65,19.0,1.198125,1.387750,1.410333,41.0
4,5,"Putnam, Andrew",14704,3.62,0.46,151.0,0.844375,1.133833,1.721500,8.0
5,6,"Gotterup, Chris",27774,3.32,1.36,51.0,1.060550,1.590417,1.206167,26.0
6,7,"Fitzpatrick, Matthew",17646,3.22,1.69,41.0,0.585250,1.189917,1.577000,8.0
7,8,"Hubbard, Mark",16333,3.11,0.76,91.0,0.634525,1.697625,1.191333,13.0
8,9,"Grillo, Emiliano",12808,2.98,1.14,61.0,0.841725,1.230000,1.362833,73.0
9,10,"Cantlay, Patrick",15466,2.51,4.08,17.0,0.989625,1.064833,1.153333,32.0

=== 2025-07-06 | event_id=30 | John Deere Classic ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Gotterup, Chris",27774,7.47,1.84,36.0,1.353225,1.627042,1.714333,21.0
1,2,"Grillo, Emiliano",12808,6.11,0.93,71.0,1.141025,1.510000,1.579583,2.0
2,3,"Roy, Kevin",18424,5.29,1.09,61.0,0.528150,1.093917,1.822833,3.0
3,4,"Champ, Cameron",23542,4.94,0.82,81.0,0.384925,1.091167,1.778250,27.0
4,5,"Hubbard, Mark",16333,4.39,1.44,46.0,1.124650,1.494625,1.116167,33.0
5,6,"Lawrence, Thriston",18105,4.37,0.82,81.0,0.008075,0.889292,1.849750,44.0
6,7,"Knapp, Jake",19396,4.23,1.84,36.0,1.023575,1.032917,1.378833,21.0
7,8,"Yu, Kevin",17881,3.72,1.84,36.0,0.893125,1.182417,1.148750,21.0
8,9,"Whaley, Vince",25908,3.50,1.00,66.0,0.937025,1.030417,1.156167,33.0
9,10,"Thorbjornsen, Michael",26649,3.33,2.28,29.0,0.695200,0.767500,1.308083,21.0

=== 2025-07-13 | event_id=541 | Genesis Scottish Open ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,11.62,14.67,4.6,3.027750,3.069125,2.444833,8.0
1,2,"Reitan, Kristoffer",21407,4.32,0.39,171.0,1.876200,2.231625,1.843250,13.0
2,3,"Penge, Marco",22465,4.24,0.61,111.0,1.939400,2.052375,1.899167,2.0
3,4,"Laporta, Francesco",14987,3.52,0.34,201.0,1.566900,1.769208,1.926583,50.0
4,5,"Gotterup, Chris",27774,3.33,0.83,81.0,1.559125,1.680458,1.887583,1.0
5,6,"Hall, Harry",27194,3.30,1.02,66.0,1.512925,1.774958,1.828167,17.0
6,7,"Fitzpatrick, Matthew",17646,2.87,1.47,46.0,0.903375,1.573375,1.936500,4.0
7,8,"Knapp, Jake",19396,2.81,0.67,101.0,0.999400,1.481958,1.945917,22.0
8,9,"Smith, Jordan",18586,2.80,0.61,111.0,1.413550,1.337750,1.899167,22.0
9,10,"McIlroy, Rory",10091,2.65,7.10,9.5,1.738750,1.325125,1.677500,2.0

=== 2025-07-20 | event_id=100 | The Open Championship ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,14.27,13.56,5.5,3.282825,2.957708,3.079750,1.0
1,2,"McIlroy, Rory",10091,6.91,8.78,8.5,1.889500,1.559375,3.163083,7.0
2,3,"Gotterup, Chris",27774,5.13,0.74,101.0,1.766250,1.893083,2.580000,3.0
3,4,"Fitzpatrick, Matthew",17646,5.09,1.46,51.0,1.308175,1.683333,2.828250,4.0
4,5,"Reitan, Kristoffer",21407,4.97,0.21,351.0,1.854200,2.380958,2.226250,30.0
5,6,"Rahm, Jon",19195,4.72,5.74,13.0,2.181650,2.279917,2.049583,34.0
6,7,"Hatton, Tyrrell",14796,3.84,2.41,31.0,1.331650,1.696583,2.382917,16.0
7,8,"Hall, Harry",27194,3.52,0.67,111.0,1.512275,1.788292,2.161583,28.0
8,9,"Henley, Russell",14578,3.43,1.13,66.0,1.427600,1.148708,2.535000,10.0
9,10,"English, Harris",14577,2.53,0.62,121.0,1.156475,1.457708,1.996417,2.0

=== 2025-07-27 | event_id=525 | 3M Open ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Gotterup, Chris",27774,16.90,3.62,19.0,2.028200,2.362917,3.011500,10.0
1,2,"Knapp, Jake",19396,4.96,1.91,36.0,0.970775,1.638583,1.971083,3.0
2,3,"Kitayama, Kurt",21891,4.47,1.68,41.0,0.847925,1.390208,2.020333,1.0
3,4,"Mouw, William",29770,3.52,0.57,121.0,0.679550,0.846292,2.091083,7.0
4,5,"Clark, Wyndham",23604,3.09,2.64,26.0,0.232450,1.108792,1.866750,12.0
5,6,"Whaley, Vince",25908,2.93,1.04,66.0,1.164375,1.272125,1.388083,57.0
6,7,"Svensson, Jesper",26850,2.70,0.97,71.0,0.521450,1.243250,1.511500,14.0
7,8,"Fowler, Rickie",12965,2.57,1.68,41.0,0.681100,1.122125,1.451333,28.0
8,9,"Grillo, Emiliano",12808,2.49,1.35,51.0,1.110700,1.249792,1.179833,20.0
9,10,"Skinns, David",10873,2.42,0.34,201.0,0.609400,0.882875,1.570583,57.0

=== 2025-08-03 | event_id=13 | Wyndham Championship ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Fitzpatrick, Matthew",17646,12.12,3.29,21.0,1.517475,2.220708,2.864417,8.0
1,2,"Kitayama, Kurt",21891,4.95,1.36,51.0,1.096700,1.550708,2.101917,31.0
2,3,"Mouw, William",29770,4.90,0.57,121.0,0.663025,1.184708,2.474417,38.0
3,4,"Matsuyama, Hideki",13562,3.70,2.23,31.0,0.889800,0.950833,2.113917,19.0
4,5,"Griffin, Ben",24968,3.59,2.66,26.0,1.612200,1.670375,1.386333,11.0
5,6,"Hall, Harry",27194,3.31,1.69,41.0,1.491100,1.599625,1.364417,15.0
6,7,"Hojgaard, Nicolai",23602,3.26,1.24,56.0,0.845350,1.242375,1.781083,55.0
7,8,"Koivun, Jackson",32319,2.82,0.91,76.0,0.341741,0.659583,2.107917,5.0
8,9,"Lipsky, David",15980,2.71,0.46,151.0,0.543850,1.012333,1.782750,44.0
9,10,"Young, Cameron",26651,2.16,1.24,56.0,1.055950,1.702833,0.849667,1.0

=== 2025-08-10 | event_id=27 | FedEx St. Jude Championship ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,23.42,18.95,3.8,3.234625,3.071958,3.356167,3.0
1,2,"Fitzpatrick, Matthew",17646,4.97,2.48,29.0,1.634625,1.996917,2.057333,32.0
2,3,"Kitayama, Kurt",21891,4.09,1.29,56.0,0.996550,1.664542,2.219833,9.0
3,4,"Fleetwood, Tommy",12294,3.78,3.13,23.0,1.762450,1.861208,1.689500,3.0
4,5,"English, Harris",14577,3.04,1.57,46.0,1.183275,1.321958,1.939500,48.0
5,6,"Young, Cameron",26651,2.97,1.76,41.0,1.183350,1.626250,1.702333,5.0
6,7,"Griffin, Ben",24968,2.94,2.00,36.0,1.812100,1.610750,1.477833,9.0
7,8,"Gotterup, Chris",27774,2.88,1.57,46.0,1.681400,1.673417,1.459250,54.0
8,9,"Henley, Russell",14578,2.82,2.32,31.0,1.325825,1.152375,1.887917,17.0
9,10,"Spaun, J.J.",17536,2.68,1.57,46.0,1.019950,1.494125,1.696083,2.0

=== 2025-08-17 | event_id=28 | BMW Championship ===

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,finish_num
0,1,"Scheffler, Scottie",18417,30.10,22.23,3.3,3.397150,3.089167,3.733500,1.0
1,2,"McIlroy, Rory",10091,7.05,8.63,8.5,1.771400,1.594833,2.673250,12.0
2,3,"Fleetwood, Tommy",12294,6.54,3.49,21.0,1.809450,1.877333,2.400167,4.0
3,4,"Young, Cameron",26651,6.39,2.82,26.0,1.516500,1.519083,2.672167,11.0
4,5,"Aberg, Ludvig",23950,3.83,3.19,23.0,0.894050,1.614750,2.066833,7.0
5,6,"Hall, Harry",27194,3.45,1.31,56.0,1.714625,1.853375,1.545167,6.0
6,7,"Henley, Russell",14578,3.30,2.04,36.0,1.263175,1.872542,1.600833,15.0
7,8,"Griffin, Ben",24968,3.04,2.04,36.0,1.874100,1.380458,1.588833,12.0
8,9,"MacIntyre, Robert",23323,3.02,1.44,51.0,1.362925,1.437458,1.711833,2.0
9,10,"Rose, Justin",6093,2.62,1.59,46.0,0.446525,0.822458,2.150167,30.0

Events scored: 31

,year,event_id,event_name,event_date,n_field,winner_pred_rank,spearman_predrank_vs_finish,top_group_n,top_group_mean_finish,top_group_median_finish,top_group_top10_rate,brier,auc,winner_in_top1,winner_in_top3,winner_in_top5,winner_in_top10,winner_in_top20
0,2025,6,Sony Open in Hawaii,2025-01-12,75,57,0.292464,10,28.4,29.0,0.3,0.013520,0.243243,False,False,False,False,False
1,2025,2,The American Express,2025-01-19,69,6,0.259595,10,18.7,16.5,0.4,0.013935,0.926471,False,False,False,True,True
2,2025,4,Farmers Insurance Open,2025-01-25,69,16,0.210711,10,25.7,15.0,0.3,0.014241,0.779412,False,False,False,False,True
3,2025,5,AT&T Pebble Beach Pro-Am,2025-02-02,78,1,0.465593,10,15.1,8.0,0.6,0.009823,1.000000,True,True,True,True,True
4,2025,3,WM Phoenix Open,2025-02-09,77,6,0.424371,10,18.0,13.5,0.3,0.012631,0.934211,False,False,False,True,True
5,2025,7,Genesis Invitational,2025-02-16,54,22,0.301036,10,17.3,12.5,0.4,0.018612,0.603774,False,False,False,False,False
6,2025,540,Mexico Open,2025-02-23,72,5,0.498744,10,16.5,11.5,0.5,0.013436,0.943662,False,False,True,True,True
7,2025,10,Cognizant Classic,2025-03-02,67,31,0.352346,10,18.1,14.5,0.4,0.014818,0.545455,False,False,False,False,False
8,2025,9,Arnold Palmer Invitational,2025-03-09,51,5,0.466516,10,10.7,9.0,0.5,0.018791,0.920000,False,False,True,True,True
9,2025,11,The Players Championship,2025-03-16,71,1,0.652720,10,13.7,14.0,0.3,0.012488,1.000000,True,True,True,True,True
10,2025,475,Valspar Championship,2025-03-23,78,49,0.565490,10,14.5,12.0,0.5,0.012979,0.376623,False,False,False,False,False
11,2025,20,Texas Children's Houston Open,2025-03-30,69,3,0.438121,10,19.2,13.0,0.3,0.013608,0.970588,False,True,True,True,True
12,2025,41,Valero Texas Open,2025-04-06,66,26,0.426044,10,26.3,24.0,0.2,0.015053,0.615385,False,False,False,False,False
13,2025,14,Masters Tournament,2025-04-13,53,1,0.269773,10,19.5,14.0,0.4,0.013373,1.000000,True,True,True,True,True
14,2025,12,RBC Heritage,2025-04-20,72,2,0.475429,10,18.4,10.5,0.5,0.013054,0.985915,False,True,True,True,True
15,2025,19,CJ Cup Byron Nelson,2025-05-04,69,1,0.307582,10,29.9,33.0,0.2,0.009591,1.000000,True,True,True,True,True
16,2025,480,Truist Championship,2025-05-11,69,4,0.578532,10,11.7,9.0,0.5,0.013718,0.955882,False,False,True,True,True
17,2025,33,PGA Championship,2025-05-18,74,1,0.449174,10,28.8,30.5,0.4,0.006781,1.000000,True,True,True,True,True
18,2025,21,Charles Schwab Challenge,2025-05-25,78,3,0.403781,10,18.3,17.0,0.5,0.013757,0.974026,False,True,True,True,True
19,2025,23,Memorial Tournament,2025-06-01,57,1,0.546716,10,14.0,11.5,0.5,0.007462,1.000000,True,True,True,True,True
20,2025,32,RBC Canadian Open,2025-06-08,66,1,0.441070,10,17.0,13.0,0.4,0.014191,1.000000,True,True,True,True,True
21,2025,26,U.S. Open,2025-06-15,65,8,0.672722,10,10.9,8.5,0.6,0.016297,0.890625,False,False,False,True,True
22,2025,34,Travelers Championship,2025-06-22,66,5,0.547880,10,13.7,11.5,0.5,0.014981,0.938462,False,False,True,True,True
23,2025,524,Rocket Classic,2025-06-29,86,27,0.485079,10,22.9,13.0,0.3,0.011587,0.694118,False,False,False,False,False
24,2025,30,John Deere Classic,2025-07-06,63,45,0.303306,10,22.6,21.0,0.2,0.015920,0.290323,False,False,False,False,False
25,2025,541,Genesis Scottish Open,2025-07-13,79,5,0.461609,10,14.1,10.5,0.5,0.012272,0.948718,False,False,True,True,True
26,2025,100,The Open Championship,2025-07-20,69,1,0.631213,10,13.5,8.5,0.6,0.009315,1.000000,True,True,True,True,True
27,2025,525,3M Open,2025-07-27,75,3,0.422644,10,20.9,13.0,0.4,0.012747,0.972973,False,True,True,True,True
28,2025,13,Wyndham Championship,2025-08-03,75,10,0.388394,10,22.7,17.0,0.3,0.013197,0.878378,False,False,False,True,True
29,2025,27,FedEx St. Jude Championship,2025-08-10,69,17,0.599909,10,18.2,9.0,0.6,0.015601,0.764706,False,False,False,False,True
30,2025,28,BMW Championship,2025-08-17,48,1,0.732499,10,10.0,9.0,0.5,0.009039,1.000000,True,True,True,True,True

,events,avg_spearman_predrank_vs_finish,avg_top10_rate_in_top10,avg_top_group_mean_finish,avg_winner_pred_rank,avg_brier,avg_auc,feat_set,lr_c,odds_scale,winner_in_top1,winner_in_top3,winner_in_top5,winner_in_top10,winner_in_top20
0,31,0.453905,0.416129,18.364516,11.741935,0.013123,0.843643,baseline_plus_layoff,0.05,0.15,0.290323,0.419355,0.580645,0.709677,0.774194

,dg_id,player_name,starts,wins,avg_pwin_share,max_pwin_share,avg_pred_rank
0,18417,"Scheffler, Scottie",18,5,0.165783,0.344586,1.333333
1,10091,"McIlroy, Rory",13,3,0.080617,0.154324,6.461538
2,17511,"Straka, Sepp",15,2,0.029059,0.060621,13.200000
3,18628,"Campbell, Brian",9,2,0.010807,0.042519,43.000000
4,27774,"Gotterup, Chris",12,1,0.039925,0.169041,14.166667
5,14139,"Thomas, Justin",16,1,0.029941,0.068981,11.687500
6,24968,"Griffin, Ben",20,1,0.029535,0.074603,16.900000
7,14578,"Henley, Russell",14,1,0.025529,0.041689,15.928571
8,21891,"Kitayama, Kurt",13,1,0.021886,0.049497,22.846154
9,17536,"Spaun, J.J.",18,1,0.018891,0.039881,18.555556
10,13872,"Bradley, Keegan",17,1,0.018731,0.043034,20.529412
11,11889,"Fox, Ryan",13,1,0.017533,0.059938,24.846154
12,23950,"Aberg, Ludvig",13,1,0.015720,0.038816,25.692308
13,16841,"Woo Lee, Min",13,1,0.015584,0.058392,33.384615
14,26651,"Young, Cameron",15,1,0.015123,0.063907,37.933333
15,14577,"English, Harris",18,1,0.014895,0.030355,23.888889
16,13126,"Taylor, Nick",16,1,0.014259,0.026877,26.875000
17,18841,"Hovland, Viktor",12,1,0.012568,0.025764,27.833333
18,28469,"Highsmith, Joe",11,1,0.011329,0.035933,43.909091
19,6093,"Rose, Justin",10,1,0.011060,0.026164,37.500000
20,14181,"Detry, Thomas",17,1,0.008948,0.029683,41.941176
21,27900,"Potgieter, Aldrich",6,1,0.008920,0.023454,43.666667
22,8825,"Harman, Brian",18,1,0.007547,0.020033,42.888889
23,19841,"DeChambeau, Bryson",3,0,0.073230,0.138219,5.666667
24,23841,"Neergaard-Petersen, Rasmus",2,0,0.062098,0.084511,3.000000
25,19195,"Rahm, Jon",4,0,0.059201,0.085236,4.750000
26,21407,"Reitan, Kristoffer",2,0,0.046428,0.049653,3.500000
27,22465,"Penge, Marco",2,0,0.039791,0.042397,4.000000
28,18079,"Niemann, Joaquin",2,0,0.036337,0.039370,6.000000
29,14735,"Ortiz, Carlos",1,0,0.035270,0.035270,6.000000
30,14987,"Laporta, Francesco",1,0,0.035156,0.035156,4.000000
31,12294,"Fleetwood, Tommy",17,0,0.033046,0.065358,8.588235
32,27194,"Hall, Harry",18,0,0.028675,0.060600,12.277778
33,28984,"Puig, David",1,0,0.025710,0.025710,6.000000
34,13900,"Lowry, Shane",15,0,0.025387,0.062173,19.333333
35,18474,"Smalley, Alex",11,0,0.024559,0.050670,17.636364
36,13562,"Matsuyama, Hideki",17,0,0.023407,0.096062,19.882353
37,17646,"Fitzpatrick, Matthew",16,0,0.023214,0.121242,28.250000
38,14796,"Hatton, Tyrrell",4,0,0.023184,0.038429,12.000000
39,17576,"Conners, Corey",17,0,0.022892,0.067423,20.294118
40,22085,"Morikawa, Collin",14,0,0.022773,0.062991,17.714286
41,23542,"Champ, Cameron",4,0,0.022469,0.049413,19.500000
42,20766,"Brown, Dan",1,0,0.022103,0.022103,14.000000
43,17606,"Berger, Daniel",16,0,0.021382,0.052421,20.875000
44,27811,"Couvra, Martin",1,0,0.020865,0.020865,15.000000
45,18586,"Smith, Jordan",3,0,0.020784,0.027995,14.666667
46,7398,"Schwartzel, Charl",1,0,0.020571,0.020571,11.000000
47,16333,"Hubbard, Mark",12,0,0.020536,0.043850,24.333333
48,19483,"Burns, Sam",19,0,0.019595,0.093496,26.105263
49,15466,"Cantlay, Patrick",14,0,0.019306,0.043206,17.071429

Done.
To try trend/layoff features, only change FEAT_SET_KEY at the top.

### ------------

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

# ============================================================
# CONFIG (lock-in)
# ============================================================
BASE_DIR = "/Users/joshmacbook/python_projects/OAD/Data/in Use"
ROUNDS_PATH = f"{BASE_DIR}/combined_rounds_all_2017_2026.csv"
ODDS_XLSX   = f"{BASE_DIR}/Odds_and_Results.xlsx"
SCHED_2024  = f"{BASE_DIR}/OAD_2024.xlsx"
SCHED_2025  = f"{BASE_DIR}/OAD_2025.xlsx"
SCHED_2026  = f"{BASE_DIR}/OAD_2026.xlsx"

WINDOWS = (40, 24, 12)
LR_C = 0.05
LR_MAX_ITER = 2000
ODDS_SCALE = 0.15

TOP_GROUP_N = 10  # for analysis summaries

# ============================================================
# Helpers
# ============================================================
def _logit(p, eps=1e-8):
    p = np.clip(np.asarray(p, dtype=float), eps, 1 - eps)
    return np.log(p / (1 - p))

def fit_lr(train_df: pd.DataFrame, feat_cols, label_col="y_win"):
    tr = train_df.dropna(subset=feat_cols + [label_col]).copy()
    ytr = tr[label_col].astype(int).values
    if np.unique(ytr).size < 2:
        return None
    m = LogisticRegression(C=LR_C, max_iter=LR_MAX_ITER, solver="lbfgs")
    m.fit(tr[feat_cols].values, ytr)
    return m

def merge_asof_by_group(left: pd.DataFrame, right: pd.DataFrame,
                        by: str, left_on: str, right_on: str,
                        direction="backward", allow_exact_matches=True) -> pd.DataFrame:
    """
    Avoids pandas 'left keys must be sorted' global constraint by running merge_asof per group.
    CRITICAL: we explicitly restore `by` as a column, so dg_id can't disappear.
    """
    out = []
    right_groups = {k: g.sort_values(right_on) for k, g in right.groupby(by, sort=False)}

    for k, lgrp in left.groupby(by, sort=False):
        rgrp = right_groups.get(k)
        if rgrp is None or rgrp.empty:
            continue

        lgrp2 = lgrp.sort_values(left_on).copy()

        merged = pd.merge_asof(
            lgrp2,
            rgrp.sort_values(right_on),
            left_on=left_on,
            right_on=right_on,
            direction=direction,
            allow_exact_matches=allow_exact_matches,
        )
        merged[by] = k
        out.append(merged)

    return pd.concat(out, ignore_index=True) if out else pd.DataFrame()

def build_player_rolling_features(rounds_df: pd.DataFrame, windows=(40,24,12)) -> pd.DataFrame:
    df = rounds_df[["dg_id","round_date","sg_total"]].copy()
    df = df.sort_values(["dg_id","round_date"]).reset_index(drop=True)
    g = df.groupby("dg_id", group_keys=False)

    df["n_rounds_to_date"] = g.cumcount() + 1

    for w in windows:
        df[f"sg_total_L{w}"] = (
            g["sg_total"]
            .rolling(window=w, min_periods=min(10, w))
            .mean()
            .reset_index(level=0, drop=True)
        )
    return df

def analyze_event_board(board: pd.DataFrame, top_group_n=10) -> pd.Series:
    b = board.copy()

    out = {}
    out["n_field"] = int(len(b))
    out["p_sum"] = float(b["p_win_share"].sum())

    # concentration / dominance
    out["top10_p_sum"] = float(b.head(10)["p_win_share"].sum())
    out["top20_p_sum"] = float(b.head(20)["p_win_share"].sum())
    out["top5_p_sum"]  = float(b.head(5)["p_win_share"].sum())

    # odds agreement (rank corr): lower close_odds is "better" so rank ascending
    if "close_odds" in b.columns and b["close_odds"].notna().any():
        tmp = b.dropna(subset=["close_odds","p_win_share"]).copy()
        if len(tmp) >= 5:
            tmp["rank_model"] = tmp["p_win_share"].rank(ascending=False, method="average")
            tmp["rank_odds"]  = tmp["close_odds"].rank(ascending=True, method="average")
            out["corr_rank_model_vs_odds"] = float(tmp["rank_model"].corr(tmp["rank_odds"]))
        else:
            out["corr_rank_model_vs_odds"] = np.nan
    else:
        out["corr_rank_model_vs_odds"] = np.nan

    # top group diagnostics
    tg = b.head(top_group_n).copy()
    out["top_group_n"] = int(len(tg))
    out["top_group_mean_sgL40"] = float(tg["sg_total_L40"].mean()) if "sg_total_L40" in tg else np.nan
    out["top_group_mean_sgL24"] = float(tg["sg_total_L24"].mean()) if "sg_total_L24" in tg else np.nan
    out["top_group_mean_sgL12"] = float(tg["sg_total_L12"].mean()) if "sg_total_L12" in tg else np.nan
    out["top_group_mean_days_since"] = float(tg["days_since_last_round"].mean()) if "days_since_last_round" in tg else np.nan
    out["top_group_mean_close_odds"] = float(tg["close_odds"].mean()) if "close_odds" in tg else np.nan

    return pd.Series(out)

# ============================================================
# 1) LOAD SCHEDULES -> sched_all
# ============================================================
sched_24 = pd.read_excel(SCHED_2024)
sched_25 = pd.read_excel(SCHED_2025)
sched_26 = pd.read_excel(SCHED_2026)
sched_all_raw = pd.concat([sched_24, sched_25, sched_26], ignore_index=True)

# Find date + name columns
date_col = next((c for c in ["start_date","event_start_date","date","event_date"] if c in sched_all_raw.columns), None)
name_col = next((c for c in ["event_name","tournament","name"] if c in sched_all_raw.columns), None)
if date_col is None:
    raise ValueError("Schedule missing start date column (start_date / event_start_date / date / event_date).")
if name_col is None:
    raise ValueError("Schedule missing event name column (event_name / tournament / name).")

sched_all = sched_all_raw.copy()
sched_all["year"] = pd.to_numeric(sched_all["year"], errors="coerce")
sched_all["event_id"] = pd.to_numeric(sched_all["event_id"], errors="coerce")
sched_all[date_col] = pd.to_datetime(sched_all[date_col], errors="coerce")
sched_all[name_col] = sched_all[name_col].astype(str)

sched_all = sched_all.dropna(subset=["year","event_id",date_col]).copy()
sched_all["year"] = sched_all["year"].astype(int)
sched_all["event_id"] = sched_all["event_id"].astype(int)
sched_all = sched_all.rename(columns={date_col:"event_start_date", name_col:"event_name"})
sched_all = sched_all[["year","event_id","event_start_date","event_name"]].copy()

sched_2026_only = sched_all[sched_all["year"] == 2026].sort_values("event_start_date").reset_index(drop=True)
if len(sched_2026_only) < 3:
    raise ValueError("Need at least 2 events in 2026 schedule to run Week 1 and Week 2.")

week1 = sched_2026_only.iloc[0]
week2 = sched_2026_only.iloc[1]
week3 = sched_2026_only.iloc[2]

# ============================================================
# 2) LOAD ODDS/RESULTS
# ============================================================
odds = pd.read_excel(ODDS_XLSX)

need_odds = {"year","event_id","dg_id","close_odds","finish_num"}
missing = need_odds - set(odds.columns)
if missing:
    raise ValueError(f"Odds_and_Results.xlsx missing required columns: {sorted(missing)}")

for c in ["year","event_id","dg_id"]:
    odds[c] = pd.to_numeric(odds[c], errors="coerce")
odds["close_odds"] = pd.to_numeric(odds["close_odds"], errors="coerce")
odds["finish_num"] = pd.to_numeric(odds["finish_num"], errors="coerce")

odds = odds.dropna(subset=["year","event_id","dg_id"]).copy()
odds["year"] = odds["year"].astype(int)
odds["event_id"] = odds["event_id"].astype(int)
odds["dg_id"] = odds["dg_id"].astype(int)

# Restrict odds to schedule event_ids
oad_event_ids = sorted(sched_all["event_id"].unique().tolist())
odds = odds[odds["event_id"].isin(oad_event_ids)].copy()

# ============================================================
# 3) LOAD ROUNDS + BUILD ROLLING FEATURES
# ============================================================
rounds = pd.read_csv(ROUNDS_PATH)

need_rounds = {"round_date","dg_id","player_name","sg_total"}
missing = need_rounds - set(rounds.columns)
if missing:
    raise ValueError(f"combined_rounds file missing required columns: {sorted(missing)}")

rounds["round_date"] = pd.to_datetime(rounds["round_date"], errors="coerce")
rounds["dg_id"] = pd.to_numeric(rounds["dg_id"], errors="coerce")
rounds["sg_total"] = pd.to_numeric(rounds["sg_total"], errors="coerce")
rounds = rounds.dropna(subset=["round_date","dg_id","sg_total"]).copy()
rounds["dg_id"] = rounds["dg_id"].astype(int)
rounds["player_name"] = rounds["player_name"].astype(str)
rounds = rounds.sort_values(["dg_id","round_date"]).reset_index(drop=True)

name_map = (
    rounds.sort_values(["dg_id","round_date"])
          .groupby("dg_id")["player_name"]
          .last()
          .to_dict()
)

rounds_roll = build_player_rolling_features(rounds, windows=WINDOWS)

# ============================================================
# 4) BUILD X (player-event rows + features)
# ============================================================
evs = sched_all.copy()
evs["cutoff_date"] = evs["event_start_date"] - pd.Timedelta(days=1)

pe = odds.merge(
    evs[["year","event_id","event_start_date","cutoff_date","event_name"]],
    on=["year","event_id"],
    how="inner",
).copy()

pe["player_name"] = pe["dg_id"].map(name_map).fillna(pe["dg_id"].apply(lambda x: f"dg_{x}"))

# y_win known only where finish_num is present
pe["y_win"] = np.where(pe["finish_num"].notna(), (pe["finish_num"] == 1).astype(int), np.nan)

left = pe.dropna(subset=["dg_id","cutoff_date"]).copy()
left["cutoff_date"] = pd.to_datetime(left["cutoff_date"], errors="coerce")
left = left.dropna(subset=["cutoff_date"]).copy()
left["dg_id"] = left["dg_id"].astype(int)

right = rounds_roll.dropna(subset=["dg_id","round_date"]).copy()
right["dg_id"] = right["dg_id"].astype(int)
right["round_date"] = pd.to_datetime(right["round_date"], errors="coerce")
right = right.dropna(subset=["round_date"]).copy()

X = merge_asof_by_group(
    left=left,
    right=right,
    by="dg_id",
    left_on="cutoff_date",
    right_on="round_date",
    direction="backward",
    allow_exact_matches=True,
)

if X.empty:
    raise ValueError("As-of merge produced empty X. Check dg_id overlap between odds field and rounds file.")

# ensure dg_id exists (guard against any weirdness)
if "dg_id" not in X.columns:
    raise ValueError("dg_id missing from X after merge_asof_by_group. Something is very wrong with group merge.")

X = X.rename(columns={"round_date":"last_round_date"})

X["days_since_last_round"] = (pd.to_datetime(X["cutoff_date"]) - pd.to_datetime(X["last_round_date"])).dt.days
X["days_since_last_round"] = pd.to_numeric(X["days_since_last_round"], errors="coerce").clip(lower=0)
X["days_since_last_round_log1p"] = np.log1p(X["days_since_last_round"].fillna(0.0))

X["p_odds_raw"] = 1.0 / pd.to_numeric(X["close_odds"], errors="coerce")
X["p_odds_raw"] = X["p_odds_raw"].replace([np.inf, -np.inf], np.nan)
X["p_odds_raw"] = X["p_odds_raw"].fillna(X["p_odds_raw"].median())

X["p_odds_share"] = X["p_odds_raw"] / (X.groupby(["year","event_id"])["p_odds_raw"].transform("sum") + 1e-12)
X["odds_logit_scaled"] = ODDS_SCALE * _logit(X["p_odds_share"].values)

BASE_FEATS = [f"sg_total_L{w}" for w in WINDOWS] + ["odds_logit_scaled"]
LAYOFF_FEATS = ["days_since_last_round_log1p"]
FEATS = BASE_FEATS + LAYOFF_FEATS

X = X.dropna(subset=[f"sg_total_L{w}" for w in WINDOWS] + ["days_since_last_round_log1p","odds_logit_scaled"]).copy()

print("X rows:", len(X), "| years in X:", sorted(X["year"].unique().tolist())[:10], "...")

# ============================================================
# Scoring function for a single 2026 event row
def score_2026_event(ev_row: pd.Series):
    ev_id = int(ev_row["event_id"])
    ev_date = pd.to_datetime(ev_row["event_start_date"])
    ev_name = str(ev_row["event_name"])

    # train on all known outcomes strictly before this event date
    train_df = X[(X["y_win"].notna()) & (pd.to_datetime(X["event_start_date"]) < ev_date)].copy()
    test_df  = X[(X["year"] == 2026) & (X["event_id"] == ev_id)].copy()

    if test_df.empty:
        raise ValueError(f"No rows found for 2026 event_id={ev_id} in Odds_and_Results field.")
    if train_df.empty:
        raise ValueError("Train df empty. Do you have finish_num populated for prior years in Odds_and_Results.xlsx?")

    # --- HARDEN: ensure expected event columns exist ---
    if "event_start_date" not in test_df.columns:
        test_df["event_start_date"] = ev_date
    else:
        test_df["event_start_date"] = pd.to_datetime(test_df["event_start_date"], errors="coerce").fillna(ev_date)

    if "event_name" not in test_df.columns:
        # if merge produced suffixed cols, pull one; otherwise just stamp from schedule row
        for cand in ["event_name_y", "event_name_x", "event_name_sched"]:
            if cand in test_df.columns:
                test_df["event_name"] = test_df[cand].astype(str)
                break
        if "event_name" not in test_df.columns:
            test_df["event_name"] = ev_name
    else:
        test_df["event_name"] = test_df["event_name"].astype(str).fillna(ev_name)

    model = fit_lr(train_df, FEATS, label_col="y_win")
    if model is None:
        raise ValueError("Training window has no class variation (no wins). Check your training filter/data.")

    # predict
    p = model.predict_proba(test_df[FEATS].values)[:, 1]
    test_df = test_df.copy()
    test_df["p_win_raw"] = p
    test_df["p_win_share"] = test_df["p_win_raw"] / (test_df["p_win_raw"].sum() + 1e-12)

    # --- HARDEN: build board using only existing cols, but guarantee the must-haves ---
    must_cols = ["year","event_id","event_start_date","event_name","dg_id","player_name",
                 "p_win_raw","p_win_share","close_odds","p_odds_share",
                 "sg_total_L40","sg_total_L24","sg_total_L12","days_since_last_round", "finish_num"]
    for c in must_cols:
        if c not in test_df.columns:
            # create missing optional columns as NaN (shouldn't happen for dg_id/player_name, but protects you)
            test_df[c] = np.nan

    # attach actual finish if present in odds file (works even if missing -> NaN)
    finish_lookup = odds[["year","event_id","dg_id","finish_num"]].copy()
    finish_lookup["finish_num"] = pd.to_numeric(finish_lookup["finish_num"], errors="coerce")

    test_df = test_df.merge(
        finish_lookup,
        on=["year","event_id","dg_id"],
        how="left",
        suffixes=("", "_actual"),
    )

    # if a merge created finish_num_actual, prefer it
    if "finish_num_actual" in test_df.columns:
        test_df["finish_num"] = test_df["finish_num_actual"].fillna(test_df.get("finish_num"))

    board = test_df[must_cols].copy()
    board = board.sort_values("p_win_share", ascending=False).reset_index(drop=True)
    board["pred_rank"] = np.arange(1, len(board) + 1)

    top10 = board.head(10).copy()
    top10["p_win_pct"] = (100 * top10["p_win_share"]).round(2)
    top10["p_odds_pct"] = (100 * top10["p_odds_share"]).round(2)

    summary = analyze_event_board(board, top_group_n=TOP_GROUP_N)

    return board, top10, summary


# ============================================================
# RUN WEEK 1 + WEEK 2
# ============================================================
print(f"\n2026 Week 1: event_id={int(week1['event_id'])} | {pd.to_datetime(week1['event_start_date']).date()} | {week1['event_name']}")
board_w1, top10_w1, summary_w1 = score_2026_event(week1)
display(summary_w1.to_frame("week1").T)
display(top10_w1[[
    "pred_rank","player_name","dg_id",
    "p_win_pct","p_odds_pct","close_odds",
    "sg_total_L40","sg_total_L24","sg_total_L12",
    "days_since_last_round", "finish_num"
]])

print(f"\n2026 Week 2: event_id={int(week2['event_id'])} | {pd.to_datetime(week2['event_start_date']).date()} | {week2['event_name']}")
board_w2, top10_w2, summary_w2 = score_2026_event(week2)
display(summary_w2.to_frame("week2").T)
display(top10_w2[[
    "pred_rank","player_name","dg_id",
    "p_win_pct","p_odds_pct","close_odds",
    "sg_total_L40","sg_total_L24","sg_total_L12",
    "days_since_last_round", "finish_num"
]])

print(f"\n2026 Week 3: event_id={int(week3['event_id'])} | {pd.to_datetime(week3['event_start_date']).date()} | {week3['event_name']}")
board_w3, top10_w3, summary_w3 = score_2026_event(week3)
display(summary_w3.to_frame("week3").T)
display(top10_w3[[
    "pred_rank","player_name","dg_id",
    "p_win_pct","p_odds_pct","close_odds",
    "sg_total_L40","sg_total_L24","sg_total_L12",
    "days_since_last_round", "finish_num"
]])

# ============================================================
# SAVE OUTPUTS
# ============================================================
OUT_W1 = f"{BASE_DIR}/win_model_2026_week1_board.csv"
OUT_W2 = f"{BASE_DIR}/win_model_2026_week2_board.csv"
OUT_W1_T10 = f"{BASE_DIR}/win_model_2026_week1_top10.csv"
OUT_W2_T10 = f"{BASE_DIR}/win_model_2026_week2_top10.csv"
OUT_W3 = f"{BASE_DIR}/win_model_2026_week3_board.csv"
OUT_W3_T10 = f"{BASE_DIR}/win_model_2026_week3_top10.csv"

board_w1.to_csv(OUT_W1, index=False)
board_w2.to_csv(OUT_W2, index=False)
top10_w1.to_csv(OUT_W1_T10, index=False)
top10_w2.to_csv(OUT_W2_T10, index=False)
board_w3.to_csv(OUT_W3, index=False)
top10_w3.to_csv(OUT_W3_T10, index=False)


print("\nSaved:")
print(" -", OUT_W1)
print(" -", OUT_W2)
print(" -", OUT_W1_T10)
print(" -", OUT_W2_T10)
print(" -", OUT_W3)
print(" -", OUT_W3_T10)

/var/folders/85/gv9dnstn1tn96gql2f7mj15h0000gn/T/ipykernel_1658/834137470.py:182: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  rounds = pd.read_csv(ROUNDS_PATH)

X rows: 7770 | years in X: [2024, 2025, 2026] ...

2026 Week 1: event_id=6 | 2026-01-15 | Sony Open in Hawaii

,n_field,p_sum,top10_p_sum,top20_p_sum,top5_p_sum,corr_rank_model_vs_odds,top_group_n,top_group_mean_sgL40,top_group_mean_sgL24,top_group_mean_sgL12,top_group_mean_days_since,top_group_mean_close_odds
week1,109.0,1.0,0.364305,0.539927,0.246735,0.511719,10.0,1.110192,1.374987,1.7907,60.4,45.9

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,days_since_last_round,finish_num
0,1,"Griffin, Ben",24968,10.52,4.70,14.0,1.771675,2.017500,2.912667,66,19.0
1,2,"Spaun, J.J.",17536,5.90,3.29,20.0,1.471125,1.567458,2.429250,38,40.0
2,3,"McGreevy, Max",23505,2.81,0.59,111.0,0.781725,1.146083,1.892833,52,NaN
3,4,"Hoey, Rico",23504,2.72,1.43,46.0,1.170500,1.543667,1.476167,52,50.0
4,5,"Whaley, Vince",25908,2.72,0.72,91.0,0.825075,1.236542,1.776417,52,40.0
5,6,"Henley, Russell",14578,2.67,5.48,12.0,1.194300,1.663292,1.346417,122,19.0
6,7,"Kim, Si Woo",14609,2.41,3.29,20.0,0.869900,1.363000,1.495083,52,11.0
7,8,"Matsuyama, Hideki",13562,2.28,3.66,18.0,1.061225,0.655917,1.766417,38,13.0
8,9,"McCarty, Matt",28635,2.22,1.00,66.0,0.948875,1.074458,1.545083,80,55.0
9,10,"Meissner, Mac",28159,2.18,1.08,61.0,1.007525,1.481958,1.266667,52,40.0

2026 Week 2: event_id=2 | 2026-01-22 | The American Express

,n_field,p_sum,top10_p_sum,top20_p_sum,top5_p_sum,corr_rank_model_vs_odds,top_group_n,top_group_mean_sgL40,top_group_mean_sgL24,top_group_mean_sgL12,top_group_mean_days_since,top_group_mean_close_odds
week2,154.0,1.0,0.33846,0.484575,0.245446,0.64631,10.0,1.552332,1.727221,1.7712,45.2,68.74

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,days_since_last_round,finish_num
0,1,"Scheffler, Scottie",18417,10.74,18.92,3.4,2.994050,3.110625,2.429083,45,1.0
1,2,"Valimaki, Sami",23816,4.27,0.49,131.0,1.162050,1.420208,2.726167,59,NaN
2,3,"Griffin, Ben",24968,4.08,3.39,19.0,1.794350,1.991583,2.053417,3,24.0
3,4,"Fitzpatrick, Matt",17646,3.30,2.07,31.0,1.931775,2.178542,1.584917,66,63.0
4,5,"Kim, Si Woo",14609,2.16,1.79,36.0,1.063525,1.462083,1.719417,3,6.0
5,6,"Noren, Alex",10419,2.00,1.40,46.0,1.707675,1.378583,1.417583,45,NaN
6,7,"Hojgaard, Rasmus",23838,1.91,1.40,46.0,1.618600,1.547125,1.290833,66,44.0
7,8,"Henley, Russell",14578,1.91,2.80,23.0,1.399050,1.409417,1.443333,3,8.0
8,9,"McGreevy, Max",23505,1.75,0.21,301.0,0.759025,1.270958,1.681833,5,27.0
9,10,"Fowler, Rickie",12965,1.73,1.26,51.0,1.093225,1.503083,1.365417,157,18.0

2026 Week 3: event_id=4 | 2026-01-29 | Farmers Insurance Open

,n_field,p_sum,top10_p_sum,top20_p_sum,top5_p_sum,corr_rank_model_vs_odds,top_group_n,top_group_mean_sgL40,top_group_mean_sgL24,top_group_mean_sgL12,top_group_mean_days_since,top_group_mean_close_odds
week3,145.0,1.0,0.309489,0.469063,0.202565,0.683745,10.0,1.264598,1.528083,1.727058,33.1,43.43

,pred_rank,player_name,dg_id,p_win_pct,p_odds_pct,close_odds,sg_total_L40,sg_total_L24,sg_total_L12,days_since_last_round,finish_num
0,1,"Higgo, Garrick",24342,8.50,1.24,58.0,1.028000,2.078625,3.120750,80,NaN
1,2,"Kim, Si Woo",14609,3.57,2.66,27.0,1.232250,1.755708,2.005833,3,NaN
2,3,"Young, Cameron",26651,3.07,3.68,19.5,1.591925,2.063917,1.345750,52,NaN
3,4,"McCarty, Matt",28635,2.77,1.05,68.0,1.247700,1.635000,1.724583,3,NaN
4,5,"Olesen, Thorbjorn",13412,2.34,1.09,66.0,1.610300,1.665625,1.313583,3,NaN
5,6,"Matsuyama, Hideki",13562,2.24,2.31,31.0,0.989875,0.912708,1.907417,10,NaN
6,7,"Rodgers, Patrick",16283,2.20,1.26,57.0,0.552000,1.479917,1.761500,3,NaN
7,8,"Spaun, J.J.",17536,2.13,2.47,29.0,1.309950,1.124875,1.570000,10,NaN
8,9,"Penge, Marco",22465,2.08,1.14,63.0,1.791975,1.355667,1.156167,59,NaN
9,10,"Schauffele, Xander",19895,2.04,4.54,15.8,1.292000,1.208792,1.365000,108,NaN

Saved:
 - /Users/joshmacbook/python_projects/OAD/Data/in Use/win_model_2026_week1_board.csv
 - /Users/joshmacbook/python_projects/OAD/Data/in Use/win_model_2026_week2_board.csv
 - /Users/joshmacbook/python_projects/OAD/Data/in Use/win_model_2026_week1_top10.csv
 - /Users/joshmacbook/python_projects/OAD/Data/in Use/win_model_2026_week2_top10.csv
 - /Users/joshmacbook/python_projects/OAD/Data/in Use/win_model_2026_week3_board.csv
 - /Users/joshmacbook/python_projects/OAD/Data/in Use/win_model_2026_week3_top10.csv