In [13]:
from pathlib import Path
import pandas as pd
import os
import warnings
warnings.filterwarnings("ignore")
pd.options.display.float_format = "{:,.2f}".format

from Scripts.weekly_view import build_weekly_view
from Scripts.schedule import build_season_schedule
from Scripts.features import compute_rolling_stats
from Scripts.preseason_runner import run_preseason_reports
from Scripts.preseason import build_preseason_package, init_shortlist_template, load_shortlist, render_preseason_player_report, get_shortlist_path

from Scripts.data_io import load_rounds, load_odds_and_results, load_course_fit, load_player_skills

from Scripts.visuals import (
    subset_weekly_for_players,
    plot_ev_current_vs_future_max,
    plot_course_vs_players_radar_from_skills,
    print_event_history_for_player,
)

from Scripts.notebook_support import (
    configure_notebook_display,
    build_default_paths,
    load_course_importance,
    apply_used_filter_to_weekly,
    build_condensed_table,
    filter_top_tables_by_ids,
    log_pick,
    preview_pick_result,
    add_player_names_to_picks_file,
    print_preseason_reports,
)

configure_notebook_display()

SEASON_YEAR = 2024
# TOP_N_PRESEASON = 15
PROJECT_ROOT = Path("/Users/joshmacbook/python_projects/OAD")

paths = build_default_paths(PROJECT_ROOT, SEASON_YEAR)
course_imp_df = load_course_importance(paths.course_imp_path)

path = get_shortlist_path(SEASON_YEAR)
if os.path.exists(path):
    os.remove(path)

init_shortlist_template(SEASON_YEAR, top_n=TOP_N_PRESEASON)
print("Shortlist template recreated:", path)

Shortlist template recreated: /Users/joshmacbook/python_projects/OAD/Data/in Use/preseason_shortlist_2024.csv

In [14]:
rounds_df = load_rounds()
odds_df = load_odds_and_results()
course_fit_df = load_course_fit(SEASON_YEAR)
player_skills_df = load_player_skills(SEASON_YEAR)
schedule_df = build_season_schedule(SEASON_YEAR)

In [15]:
pre_pkg = build_preseason_package(season=SEASON_YEAR, top_n=TOP_N_PRESEASON)
longlist = pre_pkg["longlist"]
big_hist_df = pre_pkg["major_sig_history"]

preseason_as_of = schedule_df["event_date"].min()

baseline_df = compute_rolling_stats(
    rounds_df=rounds_df,
    as_of_date=preseason_as_of,
    dg_ids=longlist["dg_id"].dropna().astype(int).tolist(),
    windows=(40, 24, 12),
)

shortlist_template_path = init_shortlist_template(season=SEASON_YEAR, top_n=TOP_N_PRESEASON)
shortlist_df = load_shortlist(SEASON_YEAR)

In [16]:
ctx = run_preseason_reports(
    season_year=SEASON_YEAR,
    top_n=15,
    windows=(40, 24, 12),
)

longlist = ctx["longlist"]
big_hist_df = ctx["big_hist_df"]
baseline_df = ctx["baseline_df"]

Preseason long list:

    dg_id  hist_rounds  dec_wgh_sg  is_liv  target_season
0   10091          159        2.49   False           2024
1   18417          162        2.41   False           2024
2   19195          166        2.16   False           2024
3   19895          153        1.93   False           2024
4   15466          144        1.91   False           2024
5   18841          181        1.84   False           2024
6   14796          175        1.59   False           2024
7   12294          180        1.54   False           2024
8   15856          132        1.53    True           2024
9   18079          132        1.47    True           2024
10  23950           68        1.47   False           2024
11  17538          168        1.46   False           2024
12  22085          151        1.46   False           2024
13  17646          179        1.46   False           2024
14  18586          187        1.42   False           2024

================================================================================
Player dg_id 10091
Star power (dec_wgh_sg): 2.492

Baseline strokes gained (L40/L24/L12, pre season):
  L40: OTT +0.911, APP +0.868, ARG +0.207, PUTT +0.345, TOTAL +2.235 (n=40)  (rank 1/15 in shortlist)
  L24: OTT +0.682, APP +0.128, ARG +0.144, PUTT +0.728, TOTAL +1.930 (n=24)  (rank 2/15 in shortlist)
  L12: OTT +nan, APP +nan, ARG +nan, PUTT +nan, TOTAL +1.776 (n=12)  (rank 4/15 in shortlist)

Big-event history since 2017 (MAJOR + SIGNATURE, no playoffs):
  Masters Tournament (event_id 14)
    Starts: 6, Cuts made: 5, Top10: 4, Top25: 5
    Best finish: 2, Worst: 21, Avg: 8.0, Avg SG event: +7.58
  PGA Championship (event_id 33)
    Starts: 7, Cuts made: 7, Top10: 3, Top25: 4
    Best finish: 7, Worst: 50, Avg: 25.3, Avg SG event: +6.99
  The Open Championship (event_id 100)
    Starts: 6, Cuts made: 5, Top10: 4, Top25: 4
    Best finish: 2, Worst: 46, Avg: 12.2, Avg SG event: +8.47
  U.S. Open (event_id 26)
    Starts: 6, Cuts made: 4, Top10: 4, Top25: 4
    Best finish: 2, Worst: 9, Avg: 6.0, Avg SG event: +7.71
  AT&T Pebble Beach Pro-Am (event_id 5)
    Starts: 1, Cuts made: 0, Top10: 0, Top25: 0
    Best finish: NA, Worst: NA, Avg: NA, Avg SG event: -0.69
  Arnold Palmer Invitational presented by Mastercard (event_id 9)
    Starts: 7, Cuts made: 7, Top10: 6, Top25: 7
    Best finish: 1, Worst: 13, Avg: 5.9, Avg SG event: +10.58
  RBC Heritage (event_id 12)
    Starts: 1, Cuts made: 1, Top10: 0, Top25: 0
    Best finish: 41, Worst: 41, Avg: 41.0, Avg SG event: +2.78
  THE PLAYERS Championship (event_id 11)
    Starts: 7, Cuts made: 4, Top10: 1, Top25: 1
    Best finish: 1, Worst: 83, Avg: 38.0, Avg SG event: +1.28
  The Genesis Invitational (event_id 7)
    Starts: 6, Cuts made: 5, Top10: 3, Top25: 4
    Best finish: 4, Worst: 29, Avg: 13.6, Avg SG event: +5.13
  Travelers Championship (event_id 34)
    Starts: 5, Cuts made: 5, Top10: 1, Top25: 5
    Best finish: 7, Worst: 19, Avg: 13.2, Avg SG event: +7.89
  Wells Fargo Championship (event_id 480)
    Starts: 5, Cuts made: 5, Top10: 3, Top25: 4
    Best finish: 1, Worst: 47, Avg: 15.4, Avg SG event: +8.46
  the Memorial Tournament presented by Workday (event_id 23)
    Starts: 6, Cuts made: 5, Top10: 2, Top25: 4
    Best finish: 7, Worst: 32, Avg: 16.6, Avg SG event: +5.36


================================================================================
Player dg_id 18417
Star power (dec_wgh_sg): 2.406

Baseline strokes gained (L40/L24/L12, pre season):
  L40: OTT +0.986, APP +1.281, ARG +0.374, PUTT -0.639, TOTAL +2.002 (n=40)  (rank 3/15 in shortlist)
  L24: OTT +0.972, APP +0.844, ARG +0.251, PUTT -0.693, TOTAL +1.373 (n=24)  (rank 11/15 in shortlist)
  L12: OTT +0.942, APP +0.502, ARG +0.352, PUTT -0.609, TOTAL +1.187 (n=12)  (rank 10/15 in shortlist)

Big-event history since 2017 (MAJOR + SIGNATURE, no playoffs):
  Masters Tournament (event_id 14)
    Starts: 3, Cuts made: 3, Top10: 2, Top25: 3
    Best finish: 1, Worst: 19, Avg: 10.0, Avg SG event: +10.21
  PGA Championship (event_id 33)
    Starts: 4, Cuts made: 3, Top10: 3, Top25: 3
    Best finish: 2, Worst: 8, Avg: 4.7, Avg SG event: +9.35
  The Open Championship (event_id 100)
    Starts: 3, Cuts made: 3, Top10: 1, Top25: 3
    Best finish: 8, Worst: 23, Avg: 17.3, Avg SG event: +6.99
  U.S. Open (event_id 26)
    Starts: 4, Cuts made: 3, Top10: 2, Top25: 2
    Best finish: 2, Worst: 27, Avg: 10.7, Avg SG event: +8.56
  Arnold Palmer Invitational presented by Mastercard (event_id 9)
    Starts: 3, Cuts made: 3, Top10: 2, Top25: 3
    Best finish: 1, Worst: 15, Avg: 6.7, Avg SG event: +9.75
  RBC Heritage (event_id 12)
    Starts: 1, Cuts made: 1, Top10: 0, Top25: 1
    Best finish: 11, Worst: 11, Avg: 11.0, Avg SG event: +8.68
  THE PLAYERS Championship (event_id 11)
    Starts: 4, Cuts made: 3, Top10: 2, Top25: 2
    Best finish: 1, Worst: 55, Avg: 21.0, Avg SG event: +5.20
  The Genesis Invitational (event_id 7)
    Starts: 5, Cuts made: 4, Top10: 1, Top25: 3
    Best finish: 7, Worst: 30, Avg: 17.2, Avg SG event: +4.00
  Travelers Championship (event_id 34)
    Starts: 4, Cuts made: 3, Top10: 1, Top25: 2
    Best finish: 4, Worst: 47, Avg: 21.3, Avg SG event: +5.38
  the Memorial Tournament presented by Workday (event_id 23)
    Starts: 3, Cuts made: 3, Top10: 2, Top25: 3
    Best finish: 3, Worst: 22, Avg: 9.3, Avg SG event: +11.01


================================================================================
Player dg_id 19195
Star power (dec_wgh_sg): 2.159

Baseline strokes gained (L40/L24/L12, pre season):
  L40: OTT +0.130, APP +0.688, ARG -0.059, PUTT +0.016, TOTAL +1.284 (n=40)  (rank 11/15 in shortlist)
  L24: OTT -0.330, APP +0.130, ARG -0.159, PUTT -0.221, TOTAL +0.946 (n=24)  (rank 13/15 in shortlist)
  L12: OTT +nan, APP +nan, ARG +nan, PUTT +nan, TOTAL +2.472 (n=12)  (rank 2/15 in shortlist)

Big-event history since 2017 (MAJOR + SIGNATURE, no playoffs):
  Masters Tournament (event_id 14)
    Starts: 6, Cuts made: 6, Top10: 4, Top25: 4
    Best finish: 1, Worst: 27, Avg: 12.5, Avg SG event: +8.98
  PGA Championship (event_id 33)
    Starts: 7, Cuts made: 6, Top10: 2, Top25: 3
    Best finish: 4, Worst: 58, Avg: 30.2, Avg SG event: +5.16
  The Open Championship (event_id 100)
    Starts: 6, Cuts made: 5, Top10: 2, Top25: 3
    Best finish: 2, Worst: 44, Avg: 18.8, Avg SG event: +6.45
  U.S. Open (event_id 26)
    Starts: 6, Cuts made: 4, Top10: 2, Top25: 4
    Best finish: 3, Worst: 23, Avg: 12.0, Avg SG event: +5.04
  AT&T Pebble Beach Pro-Am (event_id 5)
    Starts: 2, Cuts made: 2, Top10: 1, Top25: 1
    Best finish: 5, Worst: 26, Avg: 15.5, Avg SG event: +9.67
  Arnold Palmer Invitational presented by Mastercard (event_id 9)
    Starts: 2, Cuts made: 2, Top10: 0, Top25: 1
    Best finish: 17, Worst: 39, Avg: 28.0, Avg SG event: +3.82
  RBC Heritage (event_id 12)
    Starts: 2, Cuts made: 2, Top10: 0, Top25: 1
    Best finish: 15, Worst: 33, Avg: 24.0, Avg SG event: +5.73
  THE PLAYERS Championship (event_id 11)
    Starts: 7, Cuts made: 7, Top10: 1, Top25: 3
    Best finish: 9, Worst: 72, Avg: 38.8, Avg SG event: +2.72
  The Genesis Invitational (event_id 7)
    Starts: 5, Cuts made: 5, Top10: 3, Top25: 5
    Best finish: 1, Worst: 21, Avg: 10.6, Avg SG event: +8.75
  Travelers Championship (event_id 34)
    Starts: 2, Cuts made: 1, Top10: 0, Top25: 0
    Best finish: 37, Worst: 37, Avg: 37.0, Avg SG event: +1.38
  Wells Fargo Championship (event_id 480)
    Starts: 2, Cuts made: 1, Top10: 1, Top25: 1
    Best finish: 4, Worst: 4, Avg: 4.0, Avg SG event: +4.79
  the Memorial Tournament presented by Workday (event_id 23)
    Starts: 5, Cuts made: 4, Top10: 2, Top25: 3
    Best finish: 1, Worst: 16, Avg: 9.0, Avg SG event: +9.79


================================================================================
Player dg_id 19895
Star power (dec_wgh_sg): 1.930

Baseline strokes gained (L40/L24/L12, pre season):
  L40: OTT +0.359, APP +0.726, ARG +0.023, PUTT +0.542, TOTAL +1.484 (n=40)  (rank 9/15 in shortlist)
  L24: OTT +0.430, APP +0.773, ARG +0.293, PUTT +0.264, TOTAL +1.469 (n=24)  (rank 8/15 in shortlist)
  L12: OTT +0.619, APP +1.022, ARG +0.486, PUTT +0.309, TOTAL +1.628 (n=12)  (rank 5/15 in shortlist)

Big-event history since 2017 (MAJOR + SIGNATURE, no playoffs):
  Masters Tournament (event_id 14)
    Starts: 5, Cuts made: 4, Top10: 2, Top25: 3
    Best finish: 2, Worst: 50, Avg: 19.8, Avg SG event: +3.37
  PGA Championship (event_id 33)
    Starts: 7, Cuts made: 5, Top10: 1, Top25: 4
    Best finish: 10, Worst: 35, Avg: 18.4, Avg SG event: +4.60
  The Open Championship (event_id 100)
    Starts: 6, Cuts made: 6, Top10: 1, Top25: 4
    Best finish: 2, Worst: 41, Avg: 20.2, Avg SG event: +6.69
  U.S. Open (event_id 26)
    Starts: 6, Cuts made: 6, Top10: 5, Top25: 6
    Best finish: 3, Worst: 14, Avg: 7.2, Avg SG event: +11.45
  AT&T Pebble Beach Pro-Am (event_id 5)
    Starts: 1, Cuts made: 1, Top10: 0, Top25: 0
    Best finish: 66, Worst: 66, Avg: 66.0, Avg SG event: +1.86
  Arnold Palmer Invitational presented by Mastercard (event_id 9)
    Starts: 2, Cuts made: 2, Top10: 0, Top25: 1
    Best finish: 24, Worst: 39, Avg: 31.5, Avg SG event: +3.03
  RBC Heritage (event_id 12)
    Starts: 4, Cuts made: 4, Top10: 1, Top25: 1
    Best finish: 4, Worst: 64, Avg: 40.8, Avg SG event: +2.16
  THE PLAYERS Championship (event_id 11)
    Starts: 6, Cuts made: 3, Top10: 1, Top25: 2
    Best finish: 2, Worst: 37, Avg: 19.3, Avg SG event: +1.84
  The Genesis Invitational (event_id 7)
    Starts: 6, Cuts made: 6, Top10: 1, Top25: 5
    Best finish: 9, Worst: 33, Avg: 18.0, Avg SG event: +6.01
  Travelers Championship (event_id 34)
    Starts: 5, Cuts made: 4, Top10: 1, Top25: 4
    Best finish: 1, Worst: 20, Avg: 13.5, Avg SG event: +7.29
  Wells Fargo Championship (event_id 480)
    Starts: 4, Cuts made: 4, Top10: 1, Top25: 3
    Best finish: 2, Worst: 72, Avg: 28.0, Avg SG event: +6.18
  the Memorial Tournament presented by Workday (event_id 23)
    Starts: 6, Cuts made: 5, Top10: 0, Top25: 5
    Best finish: 11, Worst: 24, Avg: 16.0, Avg SG event: +5.28


================================================================================
Player dg_id 15466
Star power (dec_wgh_sg): 1.909

Baseline strokes gained (L40/L24/L12, pre season):
  L40: OTT +0.832, APP +0.356, ARG +0.305, PUTT +0.096, TOTAL +1.587 (n=40)  (rank 7/15 in shortlist)
  L24: OTT +0.670, APP +0.497, ARG +0.454, PUTT -0.230, TOTAL +1.390 (n=24)  (rank 10/15 in shortlist)
  L12: OTT +0.498, APP +0.627, ARG +0.135, PUTT -0.264, TOTAL +0.996 (n=12)  (rank 12/15 in shortlist)

Big-event history since 2017 (MAJOR + SIGNATURE, no playoffs):
  Masters Tournament (event_id 14)
    Starts: 5, Cuts made: 4, Top10: 1, Top25: 3
    Best finish: 9, Worst: 39, Avg: 19.8, Avg SG event: +4.01
  PGA Championship (event_id 33)
    Starts: 7, Cuts made: 6, Top10: 2, Top25: 3
    Best finish: 3, Worst: 43, Avg: 23.0, Avg SG event: +5.44
  The Open Championship (event_id 100)
    Starts: 5, Cuts made: 4, Top10: 1, Top25: 2
    Best finish: 8, Worst: 41, Avg: 23.5, Avg SG event: +4.71
  U.S. Open (event_id 26)
    Starts: 5, Cuts made: 5, Top10: 0, Top25: 3
    Best finish: 14, Worst: 45, Avg: 27.4, Avg SG event: +5.63
  AT&T Pebble Beach Pro-Am (event_id 5)
    Starts: 5, Cuts made: 5, Top10: 2, Top25: 3
    Best finish: 3, Worst: 48, Avg: 20.2, Avg SG event: +7.50
  Arnold Palmer Invitational presented by Mastercard (event_id 9)
    Starts: 1, Cuts made: 1, Top10: 1, Top25: 1
    Best finish: 4, Worst: 4, Avg: 4.0, Avg SG event: +9.45
  RBC Heritage (event_id 12)
    Starts: 6, Cuts made: 5, Top10: 5, Top25: 5
    Best finish: 2, Worst: 7, Avg: 3.6, Avg SG event: +8.56
  THE PLAYERS Championship (event_id 11)
    Starts: 7, Cuts made: 4, Top10: 1, Top25: 4
    Best finish: 5, Worst: 23, Avg: 17.2, Avg SG event: +1.95
  The Genesis Invitational (event_id 7)
    Starts: 6, Cuts made: 6, Top10: 2, Top25: 5
    Best finish: 3, Worst: 33, Avg: 14.5, Avg SG event: +7.68
  Travelers Championship (event_id 34)
    Starts: 6, Cuts made: 6, Top10: 1, Top25: 6
    Best finish: 4, Worst: 15, Avg: 11.8, Avg SG event: +8.09
  Wells Fargo Championship (event_id 480)
    Starts: 2, Cuts made: 1, Top10: 0, Top25: 1
    Best finish: 21, Worst: 21, Avg: 21.0, Avg SG event: +3.14
  the Memorial Tournament presented by Workday (event_id 23)
    Starts: 7, Cuts made: 7, Top10: 4, Top25: 4
    Best finish: 1, Worst: 35, Avg: 15.1, Avg SG event: +10.18


================================================================================
Player dg_id 18841
Star power (dec_wgh_sg): 1.840

Baseline strokes gained (L40/L24/L12, pre season):
  L40: OTT +0.730, APP +0.545, ARG +0.110, PUTT +0.299, TOTAL +1.907 (n=40)  (rank 4/15 in shortlist)
  L24: OTT +1.044, APP +0.302, ARG +0.115, PUTT +0.520, TOTAL +2.255 (n=24)  (rank 1/15 in shortlist)
  L12: OTT +0.894, APP -0.534, ARG +0.187, PUTT -0.146, TOTAL +1.102 (n=12)  (rank 11/15 in shortlist)

Big-event history since 2017 (MAJOR + SIGNATURE, no playoffs):
  Masters Tournament (event_id 14)
    Starts: 3, Cuts made: 3, Top10: 1, Top25: 1
    Best finish: 7, Worst: 32, Avg: 22.0, Avg SG event: +5.18
  PGA Championship (event_id 33)
    Starts: 4, Cuts made: 4, Top10: 1, Top25: 1
    Best finish: 2, Worst: 41, Avg: 26.5, Avg SG event: +7.81
  The Open Championship (event_id 100)
    Starts: 3, Cuts made: 3, Top10: 1, Top25: 3
    Best finish: 4, Worst: 13, Avg: 9.7, Avg SG event: +9.32
  U.S. Open (event_id 26)
    Starts: 4, Cuts made: 3, Top10: 0, Top25: 3
    Best finish: 12, Worst: 19, Avg: 14.7, Avg SG event: +5.74
  AT&T Pebble Beach Pro-Am (event_id 5)
    Starts: 2, Cuts made: 2, Top10: 0, Top25: 1
    Best finish: 13, Worst: 38, Avg: 25.5, Avg SG event: +5.39
  Arnold Palmer Invitational presented by Mastercard (event_id 9)
    Starts: 5, Cuts made: 5, Top10: 2, Top25: 2
    Best finish: 2, Worst: 49, Avg: 28.6, Avg SG event: +4.78
  RBC Heritage (event_id 12)
    Starts: 2, Cuts made: 2, Top10: 0, Top25: 1
    Best finish: 21, Worst: 59, Avg: 40.0, Avg SG event: +1.73
  THE PLAYERS Championship (event_id 11)
    Starts: 4, Cuts made: 3, Top10: 3, Top25: 3
    Best finish: 3, Worst: 9, Avg: 6.3, Avg SG event: +5.45
  The Genesis Invitational (event_id 7)
    Starts: 3, Cuts made: 3, Top10: 2, Top25: 3
    Best finish: 4, Worst: 20, Avg: 9.7, Avg SG event: +8.23
  Travelers Championship (event_id 34)
    Starts: 3, Cuts made: 3, Top10: 0, Top25: 1
    Best finish: 11, Worst: 54, Avg: 31.3, Avg SG event: +4.14
  Wells Fargo Championship (event_id 480)
    Starts: 2, Cuts made: 2, Top10: 1, Top25: 1
    Best finish: 3, Worst: 43, Avg: 23.0, Avg SG event: +7.13
  the Memorial Tournament presented by Workday (event_id 23)
    Starts: 4, Cuts made: 4, Top10: 1, Top25: 1
    Best finish: 1, Worst: 51, Avg: 36.8, Avg SG event: +3.35


================================================================================
Player dg_id 14796
Star power (dec_wgh_sg): 1.591

Baseline strokes gained (L40/L24/L12, pre season):
  L40: OTT -0.045, APP +0.249, ARG +0.330, PUTT +0.431, TOTAL +1.173 (n=40)  (rank 14/15 in shortlist)
  L24: OTT -0.235, APP -0.105, ARG +0.577, PUTT +0.341, TOTAL +1.087 (n=24)  (rank 12/15 in shortlist)
  L12: OTT -0.265, APP +0.243, ARG +0.831, PUTT +0.378, TOTAL +1.605 (n=12)  (rank 7/15 in shortlist)

Big-event history since 2017 (MAJOR + SIGNATURE, no playoffs):
  Masters Tournament (event_id 14)
    Starts: 6, Cuts made: 4, Top10: 0, Top25: 0
    Best finish: 34, Worst: 56, Avg: 46.5, Avg SG event: -4.73
  PGA Championship (event_id 33)
    Starts: 7, Cuts made: 5, Top10: 1, Top25: 3
    Best finish: 10, Worst: 48, Avg: 24.8, Avg SG event: +4.75
  The Open Championship (event_id 100)
    Starts: 6, Cuts made: 4, Top10: 1, Top25: 3
    Best finish: 6, Worst: 51, Avg: 22.0, Avg SG event: +3.42
  U.S. Open (event_id 26)
    Starts: 6, Cuts made: 4, Top10: 1, Top25: 2
    Best finish: 6, Worst: 56, Avg: 27.5, Avg SG event: +2.55
  Arnold Palmer Invitational presented by Mastercard (event_id 9)
    Starts: 7, Cuts made: 7, Top10: 4, Top25: 5
    Best finish: 1, Worst: 69, Avg: 18.6, Avg SG event: +7.58
  RBC Heritage (event_id 12)
    Starts: 6, Cuts made: 5, Top10: 1, Top25: 2
    Best finish: 3, Worst: 39, Avg: 23.2, Avg SG event: +4.32
  THE PLAYERS Championship (event_id 11)
    Starts: 7, Cuts made: 4, Top10: 1, Top25: 3
    Best finish: 2, Worst: 41, Avg: 19.5, Avg SG event: +2.56
  The Genesis Invitational (event_id 7)
    Starts: 2, Cuts made: 1, Top10: 0, Top25: 0
    Best finish: 40, Worst: 40, Avg: 40.0, Avg SG event: -0.65
  Wells Fargo Championship (event_id 480)
    Starts: 3, Cuts made: 3, Top10: 1, Top25: 1
    Best finish: 3, Worst: 42, Avg: 27.3, Avg SG event: +6.07
  the Memorial Tournament presented by Workday (event_id 23)
    Starts: 2, Cuts made: 2, Top10: 0, Top25: 1
    Best finish: 12, Worst: 33, Avg: 22.5, Avg SG event: +5.20


================================================================================
Player dg_id 12294
Star power (dec_wgh_sg): 1.538

Baseline strokes gained (L40/L24/L12, pre season):
  L40: OTT +0.187, APP +0.043, ARG +0.255, PUTT +0.492, TOTAL +1.559 (n=40)  (rank 8/15 in shortlist)
  L24: OTT -0.139, APP -0.255, ARG +0.645, PUTT +0.037, TOTAL +1.774 (n=24)  (rank 3/15 in shortlist)
  L12: OTT -0.532, APP -1.133, ARG +0.699, PUTT -0.418, TOTAL +1.501 (n=12)  (rank 9/15 in shortlist)

Big-event history since 2017 (MAJOR + SIGNATURE, no playoffs):
  Masters Tournament (event_id 14)
    Starts: 6, Cuts made: 5, Top10: 0, Top25: 3
    Best finish: 14, Worst: 36, Avg: 23.8, Avg SG event: +2.76
  PGA Championship (event_id 33)
    Starts: 7, Cuts made: 6, Top10: 1, Top25: 2
    Best finish: 5, Worst: 61, Avg: 32.7, Avg SG event: +4.46
  The Open Championship (event_id 100)
    Starts: 6, Cuts made: 6, Top10: 3, Top25: 4
    Best finish: 2, Worst: 33, Avg: 14.7, Avg SG event: +8.52
  U.S. Open (event_id 26)
    Starts: 6, Cuts made: 4, Top10: 3, Top25: 3
    Best finish: 2, Worst: 65, Avg: 19.0, Avg SG event: +6.60
  AT&T Pebble Beach Pro-Am (event_id 5)
    Starts: 1, Cuts made: 1, Top10: 0, Top25: 0
    Best finish: 45, Worst: 45, Avg: 45.0, Avg SG event: +1.93
  Arnold Palmer Invitational presented by Mastercard (event_id 9)
    Starts: 7, Cuts made: 6, Top10: 3, Top25: 4
    Best finish: 3, Worst: 61, Avg: 21.7, Avg SG event: +4.30
  RBC Heritage (event_id 12)
    Starts: 4, Cuts made: 3, Top10: 1, Top25: 3
    Best finish: 10, Worst: 25, Avg: 16.7, Avg SG event: +5.56
  THE PLAYERS Championship (event_id 11)
    Starts: 7, Cuts made: 6, Top10: 2, Top25: 3
    Best finish: 5, Worst: 140, Avg: 40.3, Avg SG event: +3.93
  The Genesis Invitational (event_id 7)
    Starts: 3, Cuts made: 3, Top10: 0, Top25: 1
    Best finish: 20, Worst: 37, Avg: 28.3, Avg SG event: +4.36
  Travelers Championship (event_id 34)
    Starts: 3, Cuts made: 2, Top10: 0, Top25: 1
    Best finish: 13, Worst: 46, Avg: 29.5, Avg SG event: +3.08
  Wells Fargo Championship (event_id 480)
    Starts: 3, Cuts made: 2, Top10: 1, Top25: 2
    Best finish: 5, Worst: 14, Avg: 9.5, Avg SG event: +5.19
  the Memorial Tournament presented by Workday (event_id 23)
    Starts: 1, Cuts made: 0, Top10: 0, Top25: 0
    Best finish: NA, Worst: NA, Avg: NA, Avg SG event: -7.36


================================================================================
Player dg_id 15856
Star power (dec_wgh_sg): 1.525

Baseline strokes gained (L40/L24/L12, pre season):
  L40: OTT -0.086, APP +0.868, ARG +0.274, PUTT +1.323, TOTAL +1.302 (n=40)  (rank 10/15 in shortlist)
  L24: OTT +0.120, APP +0.689, ARG +0.259, PUTT +0.110, TOTAL +0.477 (n=24)  (rank 15/15 in shortlist)
  L12: OTT +nan, APP +nan, ARG +nan, PUTT +nan, TOTAL -0.553 (n=12)  (rank 15/15 in shortlist)

Big-event history since 2017 (MAJOR + SIGNATURE, no playoffs):
  Masters Tournament (event_id 14)
    Starts: 5, Cuts made: 5, Top10: 3, Top25: 3
    Best finish: 2, Worst: 51, Avg: 19.0, Avg SG event: +6.96
  PGA Championship (event_id 33)
    Starts: 7, Cuts made: 6, Top10: 1, Top25: 2
    Best finish: 9, Worst: 64, Avg: 40.7, Avg SG event: +2.13
  The Open Championship (event_id 100)
    Starts: 6, Cuts made: 5, Top10: 1, Top25: 2
    Best finish: 1, Worst: 78, Avg: 33.0, Avg SG event: +4.00
  U.S. Open (event_id 26)
    Starts: 5, Cuts made: 3, Top10: 1, Top25: 1
    Best finish: 4, Worst: 72, Avg: 38.0, Avg SG event: +2.00
  AT&T Pebble Beach Pro-Am (event_id 5)
    Starts: 1, Cuts made: 0, Top10: 0, Top25: 0
    Best finish: NA, Worst: NA, Avg: NA, Avg SG event: -0.13
  Arnold Palmer Invitational presented by Mastercard (event_id 9)
    Starts: 2, Cuts made: 1, Top10: 0, Top25: 0
    Best finish: 34, Worst: 34, Avg: 34.0, Avg SG event: -0.76
  RBC Heritage (event_id 12)
    Starts: 6, Cuts made: 3, Top10: 1, Top25: 1
    Best finish: 9, Worst: 32, Avg: 23.3, Avg SG event: +1.71
  THE PLAYERS Championship (event_id 11)

In [22]:
INDEX = 0
EVENT_ID = int(schedule_df.iloc[INDEX]["event_id"])

weekly_raw = build_weekly_view(SEASON_YEAR, EVENT_ID)  # unfiltered
weekly, used_ids = apply_used_filter_to_weekly(weekly_raw.copy(), paths.picks_path)

print(f"Building weekly view for {SEASON_YEAR}, event_id = {EVENT_ID}")
print(f"Used players from manual picks: {len(used_ids)} dg_ids filtered out.")

display(weekly["schedule_row"])

condensed = build_condensed_table(weekly)
display(condensed.
        head(20))

Building weekly view for 2024, event_id = 6
Used players from manual picks: 1 dg_ids filtered out.

   year           start_date           event_name    purse winner_share event_id           course_name course_num rank           event_date avg_skill x_score Event_Tier
0  2024  2024-01-14 00:00:00  Sony Open in Hawaii  8300000      1494000        6  Waialae Country Club          6   25  2024-01-14 00:00:00     –0.07    0.92    REGULAR

    dg_id  is_shortlist decision_context course_type  decision_score  pct_ytd_avg_sg_total  pct_ytd_made_cut_pct  pct_event_hist_sg  pct_course_hist_sg  final_rank_score  oad_score  pct_sg_total_L12  pct_ev_current_adj  pct_oad_score  decimal_odds  ev_current_adj  ev_future_max  ev_current_to_future_max_ratio  sg_total_L40  sg_total_L24  sg_total_L12  starts_event  made_cut_pct_event  top25_event  top10_event  top5_event  wins_event  prev_finish_num_event  ytd_starts  ytd_made_cut_pct  ytd_top25  ytd_top10  ytd_top5  ytd_wins  ytd_avg_sg_total
0   12423         False    regular|mixed       mixed            0.94                  1.00                  0.50               0.75                0.86              0.92       0.74              0.90                0.97           0.97         23.00      375,604.95     225,225.23                            1.60          0.62          0.53          1.31          7.00                0.57         3.00         3.00        2.00        0.00                   3.00        1.00              1.00       1.00       1.00      1.00      1.00              2.61
1   21554         False    regular|mixed       mixed            0.88                  0.91                  0.50               0.51                0.50              0.89       0.67              0.86                0.93           0.95         31.00      278,674.64     378,787.88                            0.71          1.53          1.13          1.09          6.00                0.67         2.00         0.00        0.00        0.00                  21.00        1.00              1.00       1.00       1.00      1.00      0.00              1.61
2   23014         False    regular|mixed       mixed            0.79                  0.97                  0.50               0.42                0.36              0.80       0.62              0.73                0.91           0.86         36.00      239,969.83     490,196.08                            0.47          1.02          1.46          0.81          1.00                1.00         0.00         0.00        0.00        0.00                  48.00        1.00              1.00       1.00       1.00      1.00      0.00              2.36
3   14459         False    regular|mixed       mixed            0.78                  0.95                  0.50               0.96                0.94              0.72       0.65              0.57                0.95           0.89         29.00      297,893.58     378,787.88                            0.76          0.97          1.22          0.38          1.00                1.00         1.00         0.00        0.00        0.00                  12.00        1.00              1.00       1.00       1.00      1.00      0.00              1.86
4   13997         False    regular|mixed       mixed            0.71                  0.49                  0.50               0.83                0.77              0.78       0.57              0.73                0.89           0.73         41.00      210,705.22     190,839.69                            1.06          0.85          0.80          0.82          3.00                1.00         1.00         1.00        0.00        0.00                  41.00        1.00              1.00       0.00       0.00      0.00      0.00             -0.14
5   14577         False    regular|mixed       mixed            0.70                  0.73                  0.50               0.42                0.40              0.85       0.57              0.87                0.89           0.68         41.00      210,705.22     328,947.37                            0.62          0.83          0.74          1.16          6.00                0.83         1.00         0.00        0.00        0.00                  73.00        1.00              1.00       1.00       0.00      0.00      0.00              0.86
6   14578         False    regular|mixed       mixed            0.69                  0.08                  0.50               0.77                0.78              0.72       0.65              0.57                0.98           0.92         21.00      411,376.85     609,756.10                            0.65          1.22          0.87          0.31          7.00                0.71         3.00         1.00        1.00        0.00                  32.00        1.00              1.00       0.00       0.00      0.00      0.00             -1.89
7   14704         False    regular|mixed       mixed            0.69                  0.41                  0.50               0.65                0.65              0.71       0.59              0.62                0.87           0.78         46.00      187,802.48     138,121.55                            1.31          0.45          0.61          0.55          6.00                0.83         2.00         2.00        2.00        0.00                   4.00        1.00              1.00       0.00       0.00      0.00      0.00             -0.64
8   21756         False    regular|mixed       mixed            0.69                  0.82                  0.50               0.38                0.35              0.91       0.57              0.96                0.93           0.59         31.00      278,674.64     609,756.10                            0.44          1.51          1.77          1.64          1.00                1.00         0.00         0.00        0.00        0.00                  61.00        1.00              1.00       1.00       0.00      0.00      0.00              0.86
9   17576         False    regular|mixed       mixed            0.67                  0.49                  0.50               0.98                0.97              0.64       0.61              0.45                0.95           0.84         29.00      297,893.58     378,787.88                            0.76          0.68          0.16         -0.08          5.00                1.00         4.00         1.00        1.00        0.00                  12.00        1.00              1.00       0.00       0.00      0.00      0.00             -0.14
10  12425         False    regular|mixed       mixed            0.61                  0.49                  0.50               0.73                0.65              0.70       0.57              0.62                0.91           0.62         36.00      239,969.83     190,839.69                            1.21          0.87          0.62          0.55          4.00                1.00         2.00         0.00        0.00        0.00                  21.00        1.00              1.00       0.00       0.00      0.00      0.00             -0.14
11  14796          True    regular|mixed       mixed            0.61                  0.73                  0.50                NaN                 NaN              0.93       0.53              0.97                1.00           0.54         17.00      508,171.41     961,538.46                            0.51          1.07          1.01          1.69           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN        1.00              1.00       1.00       0.00      0.00      0.00              0.86
12  14609         False    regular|mixed       mixed            0.59                  0.62                  0.50               0.72                0.69              0.54       0.58              0.32                0.91           0.76         36.00      239,969.83     274,725.27                            0.84          0.18         -0.15         -0.30          5.00                0.80         2.00         1.00        1.00        1.00                   1.00        1.00              1.00       1.00       0.00      0.00      0.00              0.36
13  19870         False    regular|mixed       mixed            0.58                  0.32                  0.50               0.60                0.51              0.76       0.55              0.71                0.93           0.57         31.00      278,674.64     378,787.88                            0.71          0.79         -0.19          0.77          2.00                1.00         0.00         0.00        0.00        0.00                  32.00        1.00              1.00       0.00       0.00      0.00      0.00             -0.89
14  17786         False    regular|mixed       mixed            0.58                  0.14                  0.50               0.58                0.62              0.69       0.57              0.59                0.87           0.70         46.00      187,802.48     543,478.26                            0.33          1.35          1.41          0.45          5.00                0.80         1.00         1.00        0.00        0.00                  32.00        1.00              1.00       0.00       0.00      0.00      0.00             -1.89
15   6093         False    regular|mixed       mixed            0.54                  0.35                  0.50               1.00                1.00              0.59       0.57              0.41                0.93           0.65         31.00      278,674.64     352,112.68                            0.76          0.23         -0.17         -0.15          1.00                1.00         1.00         1.00        1.00        0.00                   2.00        1.00              1.00       0.00       0.00      0.00      0.00             -0.64
16  13562         False    regular|mixed       mixed            0.53                  0.03                  0.50               0.90                0.90              0.44       0.59              0.15                0.89           0.81         41.00      210,705.22     490,196.08                            0.41          0.28         -0.28         -0.90          6.00                1.00         3.00         1.00        1.00        1.00                  48.00        1.00              1.00       0.00       0.00      0.00      0.00             -2.64
17  23950          True    regular|mixed       mixed            0.52                  0.23                  0.50                NaN                 NaN              0.89       0.52              0.92                0.98           0.49         21.00      411,376.85   1,666,666.67                            0.24          1.97          1.81          1.43           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN        1.00              1.00       0.00       0.00      0.00      0.00             -1.39
18  17646          True    regular|mixed       mixed            0.51                  0.82                  0.50                NaN                 NaN              0.75       0.51              0.69                0.99           0.46         19.00      454,679.68   1,086,956.52                            0.40          1.17          1.43          0.73           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN        1.00              1.00       1.00       0.00      0.00      0.00              0.86
19  17550         False    regular|mixed       mixed            0.51                  0.66                  0.50               0.64                0.63              0.76       0.48              0.91                0.61           0.27        131.00       65,945.91     165,562.91                            0.38          1.56          1.44          1.42          2.00                0.50         1.00         0.00        0.00        0.00                  20.00        1.00              1.00       1.00       0.00      0.00      0.00              0.61

In [13]:
condensed.info

<bound method DataFrame.info of     dg_id  is_shortlist decision_context course_type  decision_score  pct_ytd_avg_sg_total  pct_ytd_made_cut_pct  pct_event_hist_sg  pct_course_hist_sg  final_rank_score  oad_score  pct_sg_total_L12  pct_ev_current_adj  pct_oad_score  decimal_odds  ev_current_adj ev_future_max  ev_current_to_future_max_ratio  sg_total_L40  sg_total_L24  sg_total_L12  starts_event  made_cut_pct_event  top25_event  top10_event  top5_event  wins_event  prev_finish_num_event  ytd_starts  ytd_made_cut_pct  ytd_top25  ytd_top10  ytd_top5  ytd_wins  ytd_avg_sg_total
0   17780         False  signature|mixed       mixed            0.71                  0.59                  0.07               0.95                 NaN              0.76       0.43              0.90                0.27           0.69         76.00      464,829.52           NaN                             NaN          1.16          1.06          1.73          1.00                1.00         1.00         1.00        0.00        0.00                   8.00          21              0.67         11          6         3         1              0.87
1   19483         False  signature|mixed       mixed            0.70                  0.73                  0.60               0.84                 NaN              0.70       0.48              0.73                0.51           0.73         51.00      692,687.13           NaN                             NaN          1.05          1.27          0.96          3.00                1.00         3.00         1.00        0.00        0.00                  15.00          19              0.84         10          7         2         0              0.99
2   18841          True  signature|mixed       mixed            0.62                  0.31                  0.48               0.71                 NaN              0.70       0.47              0.64                0.93           0.71         17.00    2,078,061.38           NaN                             NaN          0.77          0.56          0.71          4.00                1.00         2.00         1.00        1.00        1.00                   1.00          15              0.80          7          2         2         0              0.54
3    9771         False  signature|mixed       mixed            0.60                  0.47                  0.64               0.16                 NaN              0.70       0.42              0.71                0.66           0.67         41.00      861,635.21           NaN                             NaN          0.60          0.57          0.85          5.00                1.00         2.00         1.00        1.00        0.00                  45.00          20              0.85          9          5         1         0              0.74
4   13872         False  signature|mixed       mixed            0.56                  0.27                  0.48               0.34                 NaN              0.63       0.42              0.67                0.46           0.63         56.00      630,840.06           NaN                             NaN          0.86          0.65          0.77          6.00                1.00         1.00         1.00        1.00        1.00                  29.00          20              0.80          7          2         2         0              0.38
5   18103         False  signature|mixed       mixed            0.47                  0.82                  0.40               0.87                 NaN              0.41       0.35              0.43                0.33           0.43         71.00      497,563.99           NaN                             NaN          0.80          0.42          0.19          1.00                1.00         1.00         0.00        0.00        0.00                  12.00          23              0.78         14          4         3         0              1.12
6   23465         False  signature|mixed       mixed            0.46                  0.53                  0.12                NaN                 NaN              0.66       0.33              0.84                0.27           0.37         76.00      464,829.52           NaN                             NaN          0.96          1.36          1.36           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN          22              0.68          7          3         2         0              0.80
7   19870         False  signature|mixed       mixed            0.46                  0.39                  0.54               0.59                 NaN              0.48       0.37              0.57                0.12           0.45        101.00      349,772.71           NaN                             NaN          0.55          0.41          0.56          2.00                1.00         1.00         1.00        0.00        0.00                  10.00          22              0.82          7          4         1         0              0.64
8   14459         False  signature|mixed       mixed            0.46                  0.45                  0.48               0.39                 NaN              0.52       0.38              0.49                0.66           0.49         41.00      861,635.21           NaN                             NaN          0.55          0.41          0.44          4.00                1.00         1.00         0.00        0.00        0.00                  43.00          20              0.80         11          5         4         0              0.70
9   14609         False  signature|mixed       mixed            0.35                  0.43                  0.83               0.00                 NaN              0.36       0.35              0.33                0.46           0.41         56.00      630,840.06           NaN                             NaN          0.29          0.25          0.02          6.00                1.00         0.00         0.00        0.00        0.00                  31.00          22              0.91         10          1         0         0              0.66
10  23014         False  signature|mixed       mixed            0.32                  0.57                  0.67               0.66                 NaN              0.16       0.34              0.08                0.22           0.39         81.00      436,136.34           NaN                             NaN          0.23          0.14         -0.52          2.00                1.00         2.00         0.00        0.00        0.00                  15.00          21              0.86         10          7         4         0              0.85
11  21756         False  signature|mixed       mixed            0.31                  0.14                  0.16               0.42                 NaN              0.34       0.31              0.39                0.12           0.33        101.00      349,772.71           NaN                             NaN          0.45          0.93          0.13          1.00                1.00         1.00         0.00        0.00        0.00                  25.00          27              0.70         10          4         0         0              0.25
12  28270         False  signature|mixed       mixed            0.30                  0.06                  0.02                NaN                 NaN              0.60       0.28              0.78                0.40           0.18         61.00      579,131.86           NaN                             NaN          0.61          0.81          1.10           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN          21              0.62          7          4         3         2              0.19
13  23323         False  signature|mixed       mixed            0.28                  0.37                  0.00                NaN                 NaN              0.49       0.28              0.61                0.40           0.16         61.00      579,131.86           NaN                             NaN          1.38          0.97          0.67           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN          22              0.55          7          5         2         2              0.63
14  17646          True  signature|mixed       mixed            0.27                  0.24                  0.27               0.92                 NaN              0.18       0.31              0.04                0.57           0.35         46.00      767,979.21           NaN                             NaN         -0.05         -0.34         -0.68          3.00                1.00         2.00         2.00        1.00        0.00                   2.00          20              0.75          8          3         2         0              0.37
15  15575         False  signature|mixed       mixed            0.24                  0.41                  0.57               0.05                 NaN              0.18       0.30              0.18                0.03           0.27        151.00      233,953.93           NaN                             NaN          0.38          0.04         -0.26          4.00                1.00         1.00         0.00        0.00        0.00                  21.00          23              0.83         10          3         1         0              0.64
16  13965         False  signature|mixed       mixed            0.22                  0.16                  0.12               0.24                 NaN              0.24       0.28              0.27                0.12           0.22        101.00      349,772.71           NaN                             NaN          0.01         -0.13         -0.05          6.00                1.00         1.00         0.00        0.00        0.00                  44.00          22              0.68          5          4         3         0              0.29
17  14181         False  signature|mixed       mixed            0.21                  0.29                  0.27                NaN                 NaN              0.35       0.26              0.47                0.12           0.12        101.00      349,772.71           NaN                             NaN          0.48          0.30          0.34           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN          20              0.75          7          4         3         0              0.49
18  26096         False  signature|mixed       mixed            0.21                  0.63                  0.07                NaN                 NaN              0.32       0.26              0.37                0.40           0.10         61.00      579,131.86           NaN                             NaN          0.61          0.90          0.07           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN          24              0.67         12          3         3         1              0.89
19  12423         False  signature|mixed       mixed            0.21                  0.10                  0.43               0.03                 NaN              0.28       0.28              0.35                0.06           0.20        111.00      318,261.65           NaN                             NaN         -0.07          0.09          0.07          4.00                1.00         0.00         0.00        0.00        0.00                  29.00          19              0.79          4          2         1         1              0.23
20  26653         False  signature|mixed       mixed            0.20                  0.20                  0.36                NaN                 NaN              0.39       0.24              0.55                0.12           0.08        101.00      349,772.71           NaN                             NaN         -0.04          0.01          0.54           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN          22              0.77          6          2         1         1              0.35
21  17786         False  signature|mixed       mixed            0.20                  0.00                  0.31               0.18                 NaN              0.27       0.29              0.22                0.51           0.24         51.00      692,687.13           NaN                             NaN         -0.12          0.43         -0.09          3.00                1.00         0.00         0.00        0.00        0.00                  40.00          21              0.76          6          1         1         1             -0.23
22  19428         False  signature|mixed       mixed            0.16                  0.08                  0.04               0.55                 NaN              0.31       0.19              0.41                0.27           0.04         76.00      464,829.52           NaN                             NaN         -0.12         -0.05          0.17          1.00                0.00         0.00         0.00        0.00        0.00                    NaN          19              0.63          5          3         2         0              0.20
23  17511         False  signature|mixed       mixed            0.14                  0.18                  0.18               0.21                 NaN              0.15       0.26              0.14                0.19           0.14         91.00      388,209.27           NaN                             NaN          0.34          0.07         -0.31          2.00                1.00         0.00         0.00        0.00        0.00                  37.00          21              0.71          9          4         3         0              0.32
24  17538          True  signature|mixed       mixed            0.05                  0.02                  0.60               0.11                 NaN              0.15       0.23              0.02                0.84           0.06         26.00    1,358,732.44           NaN                             NaN         -0.69         -1.30         -1.81          5.00                1.00         2.00         1.00        1.00        0.00                   5.00          19              0.84          8          3         1         0              0.13
25  16394         False  signature|mixed       mixed            0.04                  0.12                  0.12                NaN                 NaN              0.05       0.14              0.06                0.03           0.02        151.00      233,953.93           NaN                             NaN         -0.41         -0.58         -0.66           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN          22              0.68          8          3         3         1              0.23
26  19960         False  signature|mixed       mixed            0.00                  0.04                  0.48                NaN                 NaN              0.00       0.11              0.00                0.00           0.00        201.00      175,756.44           NaN                             NaN         -1.10         -0.81         -2.15           NaN                 NaN          NaN          NaN         NaN         NaN                    NaN          20              0.80          7          5         4         1              0.18>

In [18]:
PICK_DG_ID = 8825

picks_log = log_pick(
    SEASON_YEAR,
    EVENT_ID,
    PICK_DG_ID,
    weekly_raw,      # MUST be unfiltered
    odds_df,
    paths.picks_log_path,
)

preview_pick_result(picks_log)

Latest Pick Summary:
---------------------
Player:        Harman, Brian (dg_id 8825)
Finish:        18
Winnings:      $106,102
Cumulative:    $106,102

In [20]:
import pandas as pd
print(pd.read_csv(paths.picks_path).head(10))
print(pd.read_csv(paths.picks_log_path).head(10))

   year  event_id           event_name  dg_id  decimal_odds  ev_current  ev_future_total  ev_current_pct_of_future  finish_num finish_text  winnings  player_name_x  player_name_y    player_name
0  2024         6  Sony Open in Hawaii   8825         19.00  436,842.00     9,358,696.00                       NaN          18         T18    106102            NaN            NaN  Harman, Brian
   year  event_id           event_name  dg_id  decimal_odds  ev_current  ev_future_total  ev_current_pct_of_future  finish_num finish_text  winnings  player_name_x  player_name_y    player_name
0  2024         6  Sony Open in Hawaii   8825         19.00  436,842.00     9,358,696.00                       NaN          18         T18    106102            NaN            NaN  Harman, Brian

In [19]:
print("after log_pick rows:", len(picks_log))
display(picks_log.tail(5))

# also read the file back from disk (proves persistence)
import pandas as pd
re = pd.read_csv(paths.picks_log_path)
print("reloaded rows:", len(re))
display(re.tail(5))

after log_pick rows: 1

   year event_id           event_name dg_id  decimal_odds  ev_current  ev_future_total  ev_current_pct_of_future finish_num finish_text winnings player_name_x player_name_y    player_name
0  2024        6  Sony Open in Hawaii  8825         19.00  436,842.00     9,358,696.00                       NaN         18         T18   106102           NaN           NaN  Harman, Brian

reloaded rows: 1

   year  event_id           event_name  dg_id  decimal_odds  ev_current  ev_future_total  ev_current_pct_of_future  finish_num finish_text  winnings  player_name_x  player_name_y    player_name
0  2024         6  Sony Open in Hawaii   8825         19.00  436,842.00     9,358,696.00                       NaN          18         T18    106102            NaN            NaN  Harman, Brian

In [15]:
FOCUS_DG_IDS = []  # [] => default top 25

focus_ids = FOCUS_DG_IDS or condensed.head(25)["dg_id"].astype(int).tolist()
weekly_f = filter_top_tables_by_ids(weekly, focus_ids)

display(weekly_f["table_performance_top50"])
display(weekly_f["table_event_history_top50"])
display(weekly_f["table_ytd_top50"])

    dg_id  oad_score  pct_sg_total_L12  pct_ev_current_adj  pct_oad_score  final_rank_score  decision_score decision_context  decimal_odds   ev_current  ev_current_adj ev_future_total ev_future_max  ev_future_total_adj  ev_future_max_adj  ev_current_to_future_max_ratio  z_sg_recent  z_ytd  z_history  z_ev_current course_fit_score  is_shortlist  tagged_here  pattern_score_winner  pattern_score_top5  sg_total_L40  sg_app_L40  sg_putt_L40  round_score_L40  sg_total_L24  sg_app_L24  sg_putt_L24  round_score_L24  sg_total_L12  sg_app_L12  sg_putt_L12  round_score_L12
11  17780       0.43              0.90                0.27           0.69              0.76            0.71  signature|mixed         76.00   263,158.00      464,829.52             NaN           NaN                  NaN                NaN                             NaN         0.69   0.29       0.44          0.06              NaN         False        False                     9                   8          1.16        0.36         0.52            69.42          1.06        0.55         0.29            68.58          1.73        0.75         0.71            68.17
16  19483       0.48              0.73                0.51           0.73              0.70            0.70  signature|mixed         51.00   392,157.00      692,687.13             NaN           NaN                  NaN                NaN                             NaN         0.64   0.55       0.50          0.11              NaN         False        False                     8                  10          1.05        0.11         0.53            69.90          1.27       -0.10         1.08            69.62          0.96        0.36         1.14            69.33
21  18841       0.47              0.64                0.93           0.71              0.70            0.62  signature|mixed         17.00 1,176,471.00    2,078,061.38             NaN           NaN                  NaN                NaN                             NaN         0.54   0.36       0.58          0.42              NaN          True        False                     4                   4          0.77        0.60         0.03            70.08          0.56        0.43         0.03            69.62          0.71        0.83        -0.40            69.58
29   9771       0.42              0.71                0.66           0.67              0.70            0.60  signature|mixed         41.00   487,805.00      861,635.21             NaN           NaN                  NaN                NaN                             NaN         0.54   0.51       0.41          0.15              NaN         False        False                     7                   7          0.60       -0.28         0.69            69.95          0.57       -0.17         0.62            69.50          0.85       -0.39         0.90            69.33
0   13872       0.42              0.67                0.46           0.63              0.63            0.56  signature|mixed         56.00   357,143.00      630,840.06             NaN           NaN                  NaN                NaN                             NaN         0.56   0.36       0.55          0.10              NaN         False        False                     5                   5          0.86        0.27         0.22            69.92          0.65        0.30         0.04            69.50          0.77        0.35        -0.15            68.83
30  18103       0.35              0.43                0.33           0.43              0.41            0.47  signature|mixed         71.00   281,690.00      497,563.99             NaN           NaN                  NaN                NaN                             NaN         0.48   0.39       0.36          0.07              NaN         False        False                     9                   6          0.80        0.11         0.42            69.97          0.42       -0.03         0.32            69.50          0.19        0.28        -0.02            69.42

    dg_id  starts_event  made_cuts_event  made_cut_pct_event  top25_event  top10_event  top5_event  wins_event  prev_finish_num_event  avg_score_event  avg_sg_total_event
11  17780          1.00             1.00                1.00         1.00         1.00        0.00        0.00                   8.00            68.75                1.50
16  19483          3.00             3.00                1.00         3.00         1.00        0.00        0.00                  15.00            68.42                1.19
21  18841          4.00             4.00                1.00         2.00         1.00        1.00        1.00                   1.00            69.12                1.03
29   9771          5.00             5.00                1.00         2.00         1.00        1.00        0.00                  45.00            70.10               -0.48
0   13872          6.00             6.00                1.00         1.00         1.00        1.00        1.00                  29.00            69.46               -0.17
30  18103          1.00             1.00                1.00         1.00         0.00        0.00        0.00                  12.00            69.00                1.25

    dg_id  ytd_starts  ytd_made_cuts  ytd_made_cut_pct  ytd_top25  ytd_top10  ytd_top5  ytd_wins  ytd_avg_score  ytd_avg_sg_total
11  17780          21             14              0.67         11          6         3         1          69.52              0.87
16  19483          19             16              0.84         10          7         2         0          69.65              0.99
21  18841          15             12              0.80          7          2         2         0          70.09              0.54
29   9771          20             17              0.85          9          5         1         0          69.71              0.74
0   13872          20             16              0.80          7          2         2         0          70.35              0.38
30  18103          23             18              0.78         14          4         3         0          69.46              1.12

In [16]:
print_event_history_for_player(weekly, 16283)

dg_focus = [16283]
slices = subset_weekly_for_players(weekly, dg_focus)

display(plot_ev_current_vs_future_max(slices["performance"]))

plot_course_vs_players_radar_from_skills(
    weekly,
    course_fit_df,
    player_skills_df,
    dg_focus,
)

Event history for dg_id 16283 at BMW Championship (event_id 28), years 2017–2023

   year  finish_num fin_text  sg_event
0  2023       37.00      T37     -4.54

Summary:
Starts: 1
Best finish: 37.0
Top-10s: 0
Top-25s: 0
Wins: 0
No data in performance slice.

Empty DataFrame
Columns: [dg_id, oad_score, pct_sg_total_L12, pct_ev_current_adj, pct_oad_score, final_rank_score, decision_score, decision_context, decimal_odds, ev_current, ev_current_adj, ev_future_total, ev_future_max, ev_future_total_adj, ev_future_max_adj, ev_current_to_future_max_ratio, z_sg_recent, z_ytd, z_history, z_ev_current, course_fit_score, is_shortlist, tagged_here, pattern_score_winner, pattern_score_top5, sg_total_L40, sg_app_L40, sg_putt_L40, round_score_L40, sg_total_L24, sg_app_L24, sg_putt_L24, round_score_L24, sg_total_L12, sg_app_L12, sg_putt_L12, round_score_L12]
Index: []

No course_fit row found for course_num=406

In [17]:
picks_with_names = add_player_names_to_picks_file(paths.picks_path, rounds_df, overwrite=True)
display(picks_with_names.head(35))

MergeError: Passing 'suffixes' which cause duplicate columns {'player_name_x'} is not allowed.

In [10]:
row = weekly_raw["schedule_row"].iloc[0]
eid = int(row["event_id"])
ename = row["event_name"]
sched_date = pd.to_datetime(row["event_date"], errors="coerce")

print("event:", ename, "event_id:", eid)
print("schedule event_date:", sched_date)

# what does odds/results say for completion date?
tmp = odds_df[(odds_df["year"] == SEASON_YEAR) & (odds_df["event_id"] == eid)].copy()
if "event_completed" in tmp.columns:
    tmp["event_completed"] = pd.to_datetime(tmp["event_completed"], errors="coerce")
    print("odds event_completed (min/max):", tmp["event_completed"].min(), tmp["event_completed"].max())
else:
    print("odds_df has no event_completed column")

# what as_of_date are we passing into YTD / features?
# (you have to print whatever variable you pass; if build_weekly_view constructs it internally, add it to weekly dict once)
print("weekly keys:", weekly_raw.keys())

event: The Open Championship event_id: 100
schedule event_date: 2025-07-20 00:00:00
odds event_completed (min/max): 2025-07-20 00:00:00 2025-07-20 00:00:00
weekly keys: dict_keys(['schedule_row', 'field', 'rolling', 'event_history', 'ytd', 'course_fit', 'course_history', 'ev_current', 'ev_future', 'summary', 'table_performance', 'table_event_history', 'table_ytd', 'table_performance_top50', 'table_event_history_top50', 'table_ytd_top50', 'pattern_candidates', 'patterns_summary_text', 'patterns_winners_features', 'patterns_top5_features'])

In [11]:
print("odds_df rows for player before cutoff:",
      odds_df[(odds_df["dg_id"] == 8825) & (pd.to_datetime(odds_df["event_completed"]) < cutoff_date)].shape[0]
)

NameError: name 'cutoff_date' is not defined

In [7]:
doc = "/Users/joshmacbook/python_projects/OAD/Data/in Use/combined_rounds_all_2017_2025.csv"
df = pd.read_csv(doc)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311040 entries, 0 to 311039
Data columns (total 37 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   tour              311040 non-null  object
 1   year              311040 non-null  int64
 2   season            311040 non-null  int64
 3   event_completed   311040 non-null  object
 4   event_name        311040 non-null  object
 5   event_id          311040 non-null  int64
 6   player_name       311040 non-null  object
 7   dg_id             311040 non-null  int64
 8   fin_text          311040 non-null  object
 9   round_num         311040 non-null  int64
 10  course_name       311040 non-null  object
 11  course_num        311040 non-null  int64
 12  course_par        306528 non-null  float64
 13  start_hole        298526 non-null  float64
 14  teetime           298526 non-null  object
 15  round_score       310116 non-null  float64
 16  sg_putt           134025 non-null  float64
 17  sg_arg            134025 non-null  float64
 18  sg_app            134025 non-null  float64
 19  sg_ott            134025 non-null  float64
 20  sg_t2g            134025 non-null  float64
 21  sg_total          311040 non-null  float64
 22  driving_dist      146242 non-null  float64
 23  driving_acc       152065 non-null  float64
 24  gir               149916 non-null  float64
 25  scrambling        125499 non-null  float64
 26  prox_rgh          121808 non-null  float64
 27  prox_fw           125553 non-null  float64
 28  great_shots       125553 non-null  float64
 29  poor_shots        125553 non-null  float64
 30  eagles_or_better  305060 non-null  float64
 31  birdies           305060 non-null  float64
 32  pars              305060 non-null  float64
 33  bogies            305060 non-null  float64
 34  doubles_or_worse  305060 non-null  float64
 35  finish_num        311040 non-null  object
 36  round_date        148712 non-null  object
dtypes: float64(22), int64(6), object(9)
memory usage: 87.8+ MB

In [3]:
import pandas as pd
oad = "/Users/joshmacbook/python_projects/OAD/Data/in Use/combined_rounds_all_2017_2025.csv"
oad_df = pd.read_csv(oad)
oad_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311040 entries, 0 to 311039
Data columns (total 37 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   tour              311040 non-null  object
 1   year              311040 non-null  int64
 2   season            311040 non-null  int64
 3   event_completed   311040 non-null  object
 4   event_name        311040 non-null  object
 5   event_id          311040 non-null  int64
 6   player_name       311040 non-null  object
 7   dg_id             311040 non-null  int64
 8   fin_text          311040 non-null  object
 9   round_num         311040 non-null  int64
 10  course_name       311040 non-null  object
 11  course_num        311040 non-null  int64
 12  course_par        306528 non-null  float64
 13  start_hole        298526 non-null  float64
 14  teetime           298526 non-null  object
 15  round_score       310116 non-null  float64
 16  sg_putt           134025 non-null  float64
 17  sg_arg            134025 non-null  float64
 18  sg_app            134025 non-null  float64
 19  sg_ott            134025 non-null  float64
 20  sg_t2g            134025 non-null  float64
 21  sg_total          311040 non-null  float64
 22  driving_dist      146242 non-null  float64
 23  driving_acc       152065 non-null  float64
 24  gir               149916 non-null  float64
 25  scrambling        125499 non-null  float64
 26  prox_rgh          121808 non-null  float64
 27  prox_fw           125553 non-null  float64
 28  great_shots       125553 non-null  float64
 29  poor_shots        125553 non-null  float64
 30  eagles_or_better  305060 non-null  float64
 31  birdies           305060 non-null  float64
 32  pars              305060 non-null  float64
 33  bogies            305060 non-null  float64
 34  doubles_or_worse  305060 non-null  float64
 35  finish_num        311040 non-null  object
 36  round_date        148712 non-null  object
dtypes: float64(22), int64(6), object(9)
memory usage: 87.8+ MB

/var/folders/85/gv9dnstn1tn96gql2f7mj15h0000gn/T/ipykernel_85995/1272692513.py:3: DtypeWarning: Columns (36) have mixed types. Specify dtype option on import or set low_memory=False.
  oad_df = pd.read_csv(oad)

In [2]:
weekly_raw = build_weekly_view(SEASON_YEAR, EVENT_ID)
weekly_raw["summary"][["dg_id","decision_score","decision_context","pct_form","pct_ytd_avg_sg_total","pct_event_hist_sg","pct_course_hist_sg"]].head(10)

NameError: name 'EVENT_ID' is not defined

In [18]:
weekly_raw = build_weekly_view(SEASON_YEAR, EVENT_ID)

print("schedule_row type:", type(weekly_raw.get("schedule_row")))
print("schedule_row columns:", list(getattr(weekly_raw.get("schedule_row"), "columns", []))[:50])

print("summary cols contains decision_context:", "decision_context" in weekly_raw["summary"].columns)
print("summary cols contains course_type:", "course_type" in weekly_raw["summary"].columns)

print("summary decision_context value counts:")
print(weekly_raw["summary"]["decision_context"].value_counts(dropna=False).head(10))

print("summary course_type value counts:")
print(weekly_raw["summary"]["course_type"].value_counts(dropna=False).head(10))

schedule_row type: <class 'pandas.core.frame.DataFrame'>
schedule_row columns: ['year', 'start_date', 'event_name', 'purse', 'winner_share', 'event_id', 'course_name', 'course_num', 'rank', 'event_date', 'avg_skill', 'x_score', 'Event_Tier']
summary cols contains decision_context: True
summary cols contains course_type: True
summary decision_context value counts:
decision_context
signature|mixed    50
Name: count, dtype: int64
summary course_type value counts:
course_type
mixed    50
Name: count, dtype: int64

In [1]:
import pandas as pd
from pathlib import Path

SCHEDULE_XLSX = {
    2024: Path("/Users/joshmacbook/python_projects/OAD/Data/in Use/OAD_2024.xlsx"),
    2025: Path("/Users/joshmacbook/python_projects/OAD/Data/in Use/OAD_2025.xlsx"),
}

season = 2025
df = pd.read_excel(SCHEDULE_XLSX[season])
print(df.columns.tolist())

['year', 'start_date', 'event_name', 'purse', 'winner_share', 'event_id', 'course_name', 'course_num', 'rank']

In [5]:
import pandas as pd

league2025 = "/Users/joshmacbook/python_projects/OAD/Data/Clean/Leagues/2025_small_normalized.csv"
league2025 = pd.read_csv(league2025)

league2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1483 entries, 0 to 1482
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   season        1483 non-null   int64
 1   league_id     1483 non-null   object
 2   event_name    1483 non-null   object
 3   event_date    1483 non-null   object
 4   event_key     1483 non-null   object
 5   event_id      1483 non-null   int64
 6   entry_id      1483 non-null   object
 7   username      1483 non-null   object
 8   player_name   1483 non-null   object
 9   dg_id         1483 non-null   float64
 10  raw_winnings  1483 non-null   float64
dtypes: float64(2), int64(2), object(7)
memory usage: 127.6+ KB

In [21]:
from Scripts.weekly_view import build_weekly_view

weekly_raw = build_weekly_view(2024, 6)  # same event as your pick row
weekly_filtered, used_ids = apply_used_filter_to_weekly(weekly_raw.copy(), paths.picks_path)

print("used_ids:", used_ids)
print("used_ids contains 8825:", 8825 in set(map(int, used_ids)))

raw_ids = set(weekly_raw["summary"]["dg_id"].dropna().astype(int))
flt_ids = set(weekly_filtered["summary"]["dg_id"].dropna().astype(int))

print("raw has 8825:", 8825 in raw_ids)
print("filtered has 8825:", 8825 in flt_ids)

used_ids: {8825}
used_ids contains 8825: True
raw has 8825: True
filtered has 8825: True

In [23]:
def find_dgid(weekly_obj, dgid=8825):
    out = {}
    for k, v in weekly_obj.items():
        if isinstance(v, pd.DataFrame) and "dg_id" in v.columns:
            s = pd.to_numeric(v["dg_id"], errors="coerce").fillna(-1).astype(int)
            out[k] = int((s == int(dgid)).sum())
    return out

print("used_ids:", used_ids)
print("counts by table:", find_dgid(weekly_raw, 8825))
print("counts by table (filtered):", find_dgid(weekly, 8825))

# also check summary rank position if still present
s = weekly["summary"].copy()
s["dg_id"] = pd.to_numeric(s["dg_id"], errors="coerce").fillna(-1).astype(int)
hit = s[s["dg_id"] == 8825]
print("in filtered summary rows:", len(hit))
if not hit.empty:
    display(hit.head(5))

used_ids: {8825}
counts by table: {'field': 1, 'rolling': 1, 'event_history': 1, 'ytd': 1, 'course_fit': 1, 'course_history': 1, 'ev_current': 1, 'ev_future': 31, 'summary': 1, 'table_performance': 1, 'table_event_history': 1, 'table_ytd': 1, 'table_performance_top50': 1, 'table_event_history_top50': 1, 'table_ytd_top50': 1, 'pattern_candidates': 1, 'patterns_winners_features': 0, 'patterns_top5_features': 0}
counts by table (filtered): {'field': 1, 'rolling': 1, 'event_history': 1, 'ytd': 1, 'course_fit': 1, 'course_history': 1, 'ev_current': 1, 'ev_future': 31, 'summary': 1, 'table_performance': 0, 'table_event_history': 0, 'table_ytd': 0, 'table_performance_top50': 0, 'table_event_history_top50': 0, 'table_ytd_top50': 0, 'pattern_candidates': 0, 'patterns_winners_features': 0, 'patterns_top5_features': 0}
in filtered summary rows: 1

    year  event_id  dg_id    player_name Event_Tier  close_odds  sg_total_L40  sg_app_L40  sg_arg_L40  sg_putt_L40  driving_dist_L40  driving_acc_L40  round_score_L40  sg_total_L24  sg_app_L24  sg_arg_L24  sg_putt_L24  driving_dist_L24  driving_acc_L24  round_score_L24  sg_total_L12  sg_app_L12  sg_arg_L12  sg_putt_L12  driving_dist_L12  driving_acc_L12  round_score_L12  starts_event  made_cuts_event  made_cut_pct_event  top25_event  top10_event  top5_event  wins_event  prev_finish_num_event prev_finish_text_event  avg_score_event  avg_sg_total_event  ytd_made_cuts  ytd_top25  ytd_top10  ytd_top5  ytd_wins  ytd_starts  ytd_made_cut_pct  ytd_avg_score  ytd_avg_sg_total  course_fit_score  decimal_odds  ev_current  ev_future_total  ev_future_max  course_starts  course_avg_sg_total  course_avg_score  course_num course_type  ev_current_vs_future_max_pct  ev_current_pct_of_future is_liv  tag_event_1  tag_event_2  tag_event_3  tag_event_4  is_shortlist  tagged_here  ev_current_adj  ev_future_total_adj  ev_future_max_adj  ev_current_to_future_max_ratio  z_sg_recent  z_ytd  event_hist_raw  event_hist_z  history_metric  z_history  z_ev_current  oad_score  pct_sg_total_L12  pct_ev_current_adj  pct_oad_score  pct_form  final_rank_score  pct_ytd_avg_sg_total  pct_ytd_made_cut_pct  pct_event_hist_sg  pct_course_hist_sg  decision_score decision_context  pattern_score_winner  pattern_flag_winner  pattern_score_top5  pattern_flag_top5
12  2024         6   8825  Harman, Brian    REGULAR       19.00          1.43        0.15        0.33         1.03            291.57             0.63            67.92          0.72       -0.02        0.44         0.59            297.72             0.57            68.17          0.84        0.01        0.53         0.48            303.77             0.60            67.92          7.00             6.00                0.86         2.00         1.00        1.00        0.00                  32.00                     32            68.36                0.33           1.00       1.00       1.00      1.00      0.00        1.00              1.00          66.75              1.61             -0.11         19.00  436,842.11     9,358,695.65     543,478.26           7.00                 0.60             68.04           6       mixed                          0.80                      0.05    NaN         <NA>         <NA>         <NA>         <NA>         False        False      454,679.68         9,740,839.27         565,670.11                            0.80         0.94   0.40            0.67          0.81            0.81       0.81          0.89       0.75              0.75                0.99           1.00      0.75              0.85                  0.91                  0.50               0.57                0.58            0.89    regular|mixed                     7                 True                   7               True